// CHC Financials API Route
// Auto-generated by Script 19 v2 — DO NOT hand edit

const express = require('express');
const router  = express.Router();
const data    = require('../data/chcFinancials');

router.get('/', (req, res) => {
  res.json({ success: true, data, generatedAt: new Date().toISOString() });
});

router.get('/consolidated', (req, res) => {
  const { consolidated, MONTHS } = data;
  const i = MONTHS.length - 1;
  const ciagRev = data.ciag.monthly.retainerRevenue[i] + data.ciag.monthly.projectRevenue[i];
  res.json({
    success: true,
    data: {
      currentMonth: MONTHS[i],
      mrrTotal:  data.coreIdentity.monthly.revenue[i] + ciagRev,
      arrTotal:  (data.coreIdentity.monthly.revenue[i] + ciagRev) * 12,
      netProfit: consolidated.profit[i],
      netMargin: consolidated.margin[i],
      monthly:   consolidated
    }
  });
});

router.get('/coreidentity', (req, res) => res.json({ success: true, data: data.coreIdentity }));
router.get('/ciag',         (req, res) => res.json({ success: true, data: data.ciag }));
router.get('/clients',      (req, res) => res.json({ success: true, data: data.clients }));

module.exports = router;
