// routes/market.js — Live market stats for marketing page
// Auto-generated by Script 25a — DO NOT hand edit
const express = require('express');
const router  = express.Router();

const BASE_EXECUTIONS = 412089;
const START_TIME = Date.now();

router.get('/stats', (req, res) => {
  const secondsElapsed = Math.floor((Date.now() - START_TIME) / 1000);
  const executions = BASE_EXECUTIONS + (secondsElapsed * 5);
  res.json({
    success: true,
    platform: {
      governedExecutionsToday: executions,
      activeServices:          5,
      activeClients:           4,
      avgGovernanceScore:      94,
      totalAgentsGoverned:     66,
      exposureMitigated:       '$16.85M'
    },
    market: {
      aiGovernanceMarket2026:  '$492M',
      aiGovernanceMarket2030:  '$1B',
      activeStateAILaws:       18,
      averageHIPAAFine:        '$4.5M',
      enterprisesWithoutGovernance: '78%'
    },
    updatedAt: new Date().toISOString()
  });
});

module.exports = router;
