// routes/onboard.js — Prospect assessment engine
// Auto-generated by Script 25a — DO NOT hand edit
const express = require('express');
const router  = express.Router();

const RISK_PROFILES = {
  'Healthcare':          { perAgent: 85000, frameworks: ['HIPAA','HITECH','CCPA','CMS'],              tier: 'Professional', priority: 'CRITICAL' },
  'Financial Services':  { perAgent: 45000, frameworks: ['GLBA','FFIEC','SOX','CCPA','PCI-DSS'],      tier: 'Enterprise',   priority: 'CRITICAL' },
  'Retail':              { perAgent: 32000, frameworks: ['CCPA','PCI-DSS','CPPA','TX_RAIGA'],          tier: 'Starter',      priority: 'HIGH'     },
  'Legal':               { perAgent: 38000, frameworks: ['ABA Model Rules','State Bar CA','CCPA'],     tier: 'Professional', priority: 'HIGH'     },
  'Insurance':           { perAgent: 55000, frameworks: ['NAIC','CCPA','GLBA'],                        tier: 'Professional', priority: 'CRITICAL' },
  'Technology':          { perAgent: 28000, frameworks: ['CCPA','SOC2','Colorado AI Act'],             tier: 'Starter',      priority: 'MEDIUM'   },
  'Manufacturing':       { perAgent: 22000, frameworks: ['CCPA','OSHA AI','Colorado AI Act'],          tier: 'Starter',      priority: 'MEDIUM'   },
  'Education':           { perAgent: 18000, frameworks: ['FERPA','CCPA','Colorado AI Act'],            tier: 'Starter',      priority: 'MEDIUM'   },
  'Government':          { perAgent: 65000, frameworks: ['FedRAMP','FISMA','CCPA','Section508'],       tier: 'Enterprise',   priority: 'CRITICAL' },
  'Real Estate':         { perAgent: 24000, frameworks: ['CCPA','Fair Housing AI','CFPB'],             tier: 'Starter',      priority: 'MEDIUM'   },
  'Logistics':           { perAgent: 20000, frameworks: ['CCPA','FMCSA','Colorado AI Act'],            tier: 'Starter',      priority: 'LOW'      },
  'Media':               { perAgent: 16000, frameworks: ['CCPA','COPPA','FTC'],                        tier: 'Starter',      priority: 'MEDIUM'   },
  'default':             { perAgent: 30000, frameworks: ['CCPA','Colorado AI Act'],                    tier: 'Starter',      priority: 'MEDIUM'   }
};

const TIERS = {
  'Starter':      { monthlyPrice: 4500,  agentLimit: 25,  annualDiscount: 0.15, supportLevel: 'Standard',  deploymentDays: 7  },
  'Professional': { monthlyPrice: 12500, agentLimit: 100, annualDiscount: 0.15, supportLevel: 'Priority',  deploymentDays: 3  },
  'Enterprise':   { monthlyPrice: 35000, agentLimit: 999, annualDiscount: 0.20, supportLevel: 'Dedicated', deploymentDays: 1  }
};

const LEADS = [];

// POST /api/onboard/assess
router.post('/assess', (req, res) => {
  const {
    company, industry, agentCount, currentScore,
    categories, email, name, title, employees, revenue
  } = req.body;

  if (!industry || !agentCount) {
    return res.status(400).json({ success: false, error: 'industry and agentCount required' });
  }

  const profile   = RISK_PROFILES[industry] || RISK_PROFILES['default'];
  const score     = Math.max(5, Math.min(95, currentScore || 20));
  const ungov     = Math.round(agentCount * (100 - score) / 100);
  const exposure  = ungov * profile.perAgent;
  const projected = Math.min(96, score + Math.round((100 - score) * 0.42));

  const tier      = agentCount > 75 ? 'Enterprise' : agentCount > 20 ? 'Professional' : 'Starter';
  const tierData  = TIERS[tier];
  const monthly   = tierData.monthlyPrice;
  const annual    = monthly * 12 * (1 - tierData.annualDiscount);
  const roi       = exposure > 0 ? Math.round((exposure - monthly * 12) / (monthly * 12) * 100) : 0;
  const payback   = exposure > 0 ? Math.round((monthly * 12 / exposure) * 365) : 0;

  const criticalAgents = (categories || []).filter(c =>
    ['Fraud Detection / Risk','Clinical / Medical Decision','Compliance / Regulatory'].includes(c)
  );

  const reportId = 'RPT-' + Date.now();

  if (email) {
    LEADS.push({
      company, industry, agentCount, currentScore: score,
      email, name, title, employees, revenue,
      assessedAt: new Date().toISOString(),
      reportId, exposure, tier, roi
    });
  }

  res.json({
    success: true,
    reportId,
    company:  company || 'Your Company',
    industry,
    assessment: {
      currentScore:    score,
      ungoverned:      ungov,
      governed:        agentCount - ungov,
      projectedScore:  projected,
      improvement:     projected - score,
      priority:        profile.priority
    },
    financials: {
      exposurePerIncident: exposure,
      annualExposure:      Math.round(exposure * 1.4),
      monthlyPlatformCost: monthly,
      annualPlatformCost:  Math.round(annual),
      roi:                 roi,
      paybackDays:         payback,
      exposureMitigated:   exposure
    },
    recommendation: {
      tier,
      monthlyPrice:    monthly,
      annualPrice:     Math.round(annual),
      agentLimit:      tierData.agentLimit,
      deploymentDays:  tierData.deploymentDays,
      supportLevel:    tierData.supportLevel,
      frameworks:      profile.frameworks,
      criticalAgents:  criticalAgents,
      urgency:         profile.priority === 'CRITICAL' ? 'Immediate governance required' : 'Governance recommended within 90 days'
    },
    generatedAt: new Date().toISOString()
  });
});

// GET /api/onboard/leads — internal CRM view
router.get('/leads', (req, res) => {
  res.json({ success: true, count: LEADS.length, data: LEADS.slice(-50).reverse() });
});

// POST /api/pilot/request
router.post('/pilot', (req, res) => {
  const { company, email, name, industry, agentCount, notes } = req.body;
  if (!email || !company) return res.status(400).json({ success: false, error: 'email and company required' });
  const pilot = { company, email, name, industry, agentCount, notes, requestedAt: new Date().toISOString(), pilotId: 'PILOT-' + Date.now() };
  LEADS.push({ ...pilot, type: 'PILOT_REQUEST' });
  res.json({ success: true, message: 'Pilot request received', pilotId: pilot.pilotId, nextStep: 'Our team will contact you within 24 hours' });
});

module.exports = router;
