// routes/pricing.js — Pricing tiers + ROI calculator
// Auto-generated by Script 25a — DO NOT hand edit
const express = require('express');
const router  = express.Router();

const TIERS = [
  {
    id:           'starter',
    name:         'Starter',
    tagline:      'Governance for growing teams',
    monthlyPrice: 4500,
    annualPrice:  45900,
    agentLimit:   25,
    highlight:    false,
    color:        '#3b82f6',
    features: [
      'Up to 25 AI agents governed',
      'Sentinel OS policy gate',
      'Full audit trail + execution log',
      'CCPA + Colorado AI Act coverage',
      'Standard API access',
      'Email support (24hr SLA)',
      '7-day deployment',
      'Monthly governance report',
      '30-day free pilot'
    ],
    notIncluded: [
      'Priority support',
      'Custom framework mapping',
      'CIAG advisory hours',
      'Dedicated success manager'
    ]
  },
  {
    id:           'professional',
    name:         'Professional',
    tagline:      'Full governance for regulated industries',
    monthlyPrice: 12500,
    annualPrice:  127500,
    agentLimit:   100,
    highlight:    true,
    color:        '#d4a843',
    features: [
      'Up to 100 AI agents governed',
      'Sentinel OS + Nexus OS + AGO Modules',
      'Full audit trail + real-time telemetry',
      'ALL regulatory frameworks (HIPAA, GLBA, ABA, PCI-DSS, CCPA)',
      'SmartNation AI continuous monitoring',
      'Priority API access (5x rate limits)',
      'Priority support (4hr SLA)',
      '3-day deployment',
      'Weekly executive reports',
      '4hr CIAG advisory per month',
      '30-day free pilot'
    ],
    notIncluded: [
      'Dedicated success manager',
      'Custom vertical handlers',
      'On-prem deployment'
    ]
  },
  {
    id:           'enterprise',
    name:         'Enterprise',
    tagline:      'Unlimited governance at institutional scale',
    monthlyPrice: 35000,
    annualPrice:  336000,
    agentLimit:   999,
    highlight:    false,
    color:        '#a855f7',
    features: [
      'Unlimited AI agents governed',
      'Full 4-plane platform (Sentinel + SmartNation + Nexus + AGO)',
      'Real-time audit trail + bidirectional telemetry sync',
      'Custom regulatory framework mapping',
      'Custom vertical AGO handlers',
      'Dedicated success manager',
      'SLA: 99.9% uptime',
      '1-day deployment',
      'Daily governance reports',
      'Unlimited CIAG advisory hours',
      'On-prem or private cloud deployment option',
      'White-label licensing available',
      'Sovereign nation deployments',
      '30-day free pilot'
    ],
    notIncluded: []
  }
];

const ADDONS = [
  { id: 'ciag-retainer',   name: 'CIAG Advisory Retainer',    price: 22000, unit: '/month', desc: 'Dedicated CIAG advisor, unlimited governance consulting, board-ready reports' },
  { id: 'extra-agents',    name: 'Additional Agent Pack',      price: 800,   unit: '/25 agents/mo', desc: 'Expand agent capacity beyond tier limit' },
  { id: 'custom-vertical', name: 'Custom Vertical Handler',    price: 15000, unit: 'one-time', desc: 'Purpose-built AGO module for your specific regulatory context' },
  { id: 'white-label',     name: 'White-Label License',        price: 50000, unit: '/year', desc: 'Deploy CoreIdentity under your own brand' },
  { id: 'on-prem',         name: 'On-Premises Deployment',     price: 25000, unit: 'setup + $5K/mo', desc: 'Air-gapped, private cloud, or on-prem deployment' },
];

router.get('/tiers', (req, res) => {
  res.json({ success: true, tiers: TIERS, addons: ADDONS, currency: 'USD', updatedAt: new Date().toISOString() });
});

router.post('/calculate', (req, res) => {
  const { industry, agentCount, billing } = req.body;
  const RISK_MULTIPLIER = { Healthcare: 0.026, 'Financial Services': 0.018, Retail: 0.009, Legal: 0.014, Insurance: 0.022, default: 0.012 };
  const PER_AGENT_EXPOSURE = { Healthcare: 85000, 'Financial Services': 45000, Retail: 32000, Legal: 38000, Insurance: 55000, default: 30000 };
  const mult     = RISK_MULTIPLIER[industry] || RISK_MULTIPLIER.default;
  const perAgent = PER_AGENT_EXPOSURE[industry] || PER_AGENT_EXPOSURE.default;
  const tier     = agentCount > 75 ? TIERS[2] : agentCount > 20 ? TIERS[1] : TIERS[0];
  const exposure = agentCount * perAgent;
  const monthly  = billing === 'annual' ? Math.round(tier.annualPrice / 12) : tier.monthlyPrice;
  const roi      = Math.round((exposure - monthly * 12) / (monthly * 12) * 100);
  res.json({ success: true, recommended: tier.id, monthly, annual: tier.annualPrice, exposure, roi, paybackDays: Math.round((monthly * 12 / exposure) * 365) });
});

module.exports = router;
