// Telemetry Ingest + Query — /api/telemetry
// Auto-generated by Script 23 — DO NOT hand edit

const express = require('express');
const router  = express.Router();
const { addExecution, addSync, getRecent, store } = require('../store/telemetry');

// POST /api/telemetry/ingest — GCP pushes execution telemetry here
router.post('/ingest', (req, res) => {
  const { source, executions, syncType, timestamp } = req.body;
  if (!source || !executions || !Array.isArray(executions)) {
    return res.status(400).json({ success: false, error: 'source and executions[] required' });
  }
  for (const exec of executions) {
    addExecution({ ...exec, source, ingestedAt: new Date().toISOString() });
  }
  addSync({ source, count: executions.length, syncType: syncType || 'GCP_PUSH', timestamp: timestamp || new Date().toISOString() });
  res.json({
    success:   true,
    ingested:  executions.length,
    totalNow:  store.stats.totalExecutions,
    message:   'Telemetry ingested successfully'
  });
});

// GET /api/telemetry/executions — live execution feed
router.get('/executions', (req, res) => {
  const limit    = Math.min(parseInt(req.query.limit) || 50, 200);
  const clientId = req.query.clientId || null;
  res.json({
    success: true,
    total:   store.stats.totalExecutions,
    count:   limit,
    data:    getRecent(limit, clientId)
  });
});

// GET /api/telemetry/stats — governance stats across all clients
router.get('/stats', (req, res) => {
  res.json({ success: true, data: store.stats });
});

// GET /api/telemetry/syncs — sync event log
router.get('/syncs', (req, res) => {
  res.json({
    success: true,
    count:   store.syncs.length,
    data:    store.syncs.slice(-20).reverse()
  });
});

module.exports = router;
