// FoundersDashboard.jsx — LIVE DATA
// Auto-generated by Script 20 v2 — DO NOT hand edit
// Fetches: /api/live-data → GCP Corporate API + GCP Virtual Bank

import { useState, useEffect, useCallback } from 'react';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, Line } from 'recharts';

const C = { bg:'#0a0e1a', surface:'#111827', border:'#1f2937', gold:'#d4a843', goldDim:'#92722d', blue:'#3b82f6', teal:'#14b8a6', red:'#ef4444', green:'#22c55e', slate:'#94a3b8', white:'#f1f5f9', orange:'#f97316' };
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

// Fallback data (shown during load or on error)
const FB = {
  ciRev:  [78000,82000,88000,92000,98000,105000,112000,118000,122000,128000,135000,142000],
  ciTgt:  [85000,90000,96000,102000,109000,116000,123000,130000,136000,142000,149000,156000],
  ciCost: [21000,21500,22000,22500,23000,23500,24000,24500,25000,25500,26000,26500],
  cgRet:  [48000,52000,54000,60000,66000,70000,72000,72000,78000,82000,85000,88000],
  cgProj: [15000,22000,35000,28000,42000,38000,55000,48000,62000,58000,72000,65000],
  cgTgt:  [70000,78000,90000,92000,115000,112000,130000,125000,145000,145000,162000,158000],
  cgCost: [38000,39000,40000,41000,42000,43000,44000,45000,46000,47000,48000,49000],
};
FB.cgRev = FB.cgRet.map((r,i) => r + FB.cgProj[i]);

const fmtK  = n => !n ? '$0' : n >= 1000000 ? '$'+(n/1000000).toFixed(2)+'M' : '$'+(n/1000).toFixed(0)+'K';
const last  = a => a?.[a.length-1] ?? 0;
const delta = (a,b) => b ? ((a-b)/b*100).toFixed(1) : '0.0';

function trend(rev, cost, tgt) {
  return MONTHS.map((m,i) => ({ month:m, Revenue:(rev||FB.ciRev)[i], Costs:(cost||FB.ciCost)[i], Profit:(rev||FB.ciRev)[i]-(cost||FB.ciCost)[i], Target:(tgt||FB.ciTgt)[i] }));
}
function variance(rev, tgt) {
  return MONTHS.map((m,i) => ({ month:m, Actual:(rev||FB.ciRev)[i], Target:(tgt||FB.ciTgt)[i], Variance:(rev||FB.ciRev)[i]-(tgt||FB.ciTgt)[i] }));
}

function Card({label, value, sub, accent, trend: t}) {
  const tc = t === undefined ? C.slate : t >= 0 ? C.green : C.red;
  return (
    <div style={{background:C.surface, border:'1px solid '+C.border, borderRadius:8, padding:'20px 24px', flex:1, minWidth:160}}>
      <div style={{color:C.slate, fontSize:11, letterSpacing:'0.1em', textTransform:'uppercase', marginBottom:8}}>{label}</div>
      <div style={{color:accent||C.gold, fontSize:28, fontWeight:700, fontFamily:'monospace'}}>{value}</div>
      {sub && <div style={{color:tc, fontSize:12, marginTop:6}}>{t !== undefined && (t >= 0 ? '▲ ' : '▼ ')}{sub}</div>}
    </div>
  );
}
function SecHdr({title, live}) {
  return (
    <div style={{borderBottom:'1px solid '+C.border, paddingBottom:10, marginBottom:16, display:'flex', justifyContent:'space-between', alignItems:'center'}}>
      <span style={{color:C.slate, fontSize:11, letterSpacing:'0.12em', textTransform:'uppercase'}}>{title}</span>
      {live && <span style={{background:C.green+'22', color:C.green, border:'1px solid '+C.green+'44', borderRadius:4, fontSize:9, padding:'2px 8px', fontWeight:600}}>● LIVE</span>}
    </div>
  );
}
function Pill({label, color}) {
  return <span style={{background:color+'22', color, border:'1px solid '+color+'44', borderRadius:4, fontSize:10, padding:'2px 8px', fontWeight:600, textTransform:'uppercase'}}>{label}</span>;
}
function Bar2({value, color}) {
  return <div style={{background:C.border, borderRadius:4, height:6, width:'100%', overflow:'hidden'}}><div style={{width:Math.min(value,100)+'%', height:'100%', background:color||C.gold, borderRadius:4}}/></div>;
}
function Tip({active, payload, label}) {
  if (!active || !payload?.length) return null;
  return <div style={{background:'#1a2035', border:'1px solid '+C.border, borderRadius:6, padding:'10px 14px'}}><div style={{color:C.slate, fontSize:11, marginBottom:6}}>{label}</div>{payload.map((p,i) => <div key={i} style={{color:p.color, fontSize:13, fontFamily:'monospace'}}>{p.name}: {fmtK(p.value)}</div>)}</div>;
}

function ConsolidatedView({vm, d}) {
  const ciRev  = d?.coreIdentity?.monthly?.revenue || FB.ciRev;
  const ciCost = d?.coreIdentity?.monthly?.costs   || FB.ciCost;
  const ciTgt  = d?.coreIdentity?.monthly?.targets || FB.ciTgt;
  const cgRev  = d?.ciag?.monthly ? d.ciag.monthly.retainerRevenue.map((r,i) => r + d.ciag.monthly.projectRevenue[i]) : FB.cgRev;
  const cgCost = d?.ciag?.monthly?.costs   || FB.cgCost;
  const cgTgt  = d?.ciag?.monthly?.targets || FB.cgTgt;
  const chcRev  = ciRev.map((r,i) => r + cgRev[i]);
  const chcCost = ciCost.map((c,i) => c + cgCost[i]);
  const chcTgt  = ciTgt.map((t,i) => t + cgTgt[i]);
  const chcProf = chcRev.map((r,i) => r - chcCost[i]);
  const curRev=last(chcRev), curCost=last(chcCost), curProf=last(chcProf), curMgn=curRev?Math.round(curProf/curRev*100):74;
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Total MRR"  value={fmtK(curRev)}    sub={delta(curRev,chcRev[10])+'% MoM'}   trend={parseFloat(delta(curRev,chcRev[10]))} />
        <Card label="ARR"        value={fmtK(curRev*12)} sub="Annualized run rate"                  accent={C.blue} />
        <Card label="Net Profit" value={fmtK(curProf)}   sub={delta(curProf,chcProf[10])+'% MoM'}  trend={parseFloat(delta(curProf,chcProf[10]))} accent={C.green} />
        <Card label="Net Margin" value={curMgn+'%'}      sub="Blended CHC margin"                   accent={C.teal} />
        <Card label="CHC Agents" value={d?.agents?.total||23} sub="All governed (100%)"             accent={C.gold} />
      </div>
      {vm==='trend' && (<><SecHdr title="12-Month Revenue · Costs · Profit" live={!!d}/><ResponsiveContainer width="100%" height={260}><AreaChart data={trend(chcRev,chcCost,chcTgt)}><defs><linearGradient id="gR" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.gold} stopOpacity={0.2}/><stop offset="95%" stopColor={C.gold} stopOpacity={0}/></linearGradient><linearGradient id="gP" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.green} stopOpacity={0.2}/><stop offset="95%" stopColor={C.green} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.gold}  fill="url(#gR)" strokeWidth={2}/><Area type="monotone" dataKey="Profit"  stroke={C.green} fill="url(#gP)" strokeWidth={2}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="Actuals vs Targets" live={!!d}/><ResponsiveContainer width="100%" height={260}><BarChart data={variance(chcRev,chcTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.gold} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer><div style={{marginTop:16, display:'flex', gap:12, flexWrap:'wrap'}}>{variance(chcRev,chcTgt).slice(-3).map(d2 => (<div key={d2.month} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'10px 16px',minWidth:140}}><div style={{color:C.slate,fontSize:11}}>{d2.month}</div><div style={{color:d2.Variance>=0?C.green:C.red,fontFamily:'monospace',fontSize:14}}>{d2.Variance>=0?'+':''}{fmtK(d2.Variance)}</div><div style={{color:C.slate,fontSize:11}}>{d2.Variance>=0?'Beat':'Miss'} {Math.abs(Math.round(d2.Variance/d2.Target*100))}%</div></div>))}</div></>)}
      {vm==='actuals' && (
        <><SecHdr title="Subsidiary P&L — Current Month" live={!!d}/>
        <table style={{width:'100%', borderCollapse:'collapse', fontSize:13}}>
          <thead><tr style={{borderBottom:'1px solid '+C.border}}>{['Entity','Type','Revenue','Costs','Net Profit','Margin','Agents'].map(h => <th key={h} style={{textAlign:'left',padding:'8px 12px',color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em'}}>{h}</th>)}</tr></thead>
          <tbody>
            <tr style={{borderBottom:'1px solid '+C.border}}>
              <td style={{padding:'12px',color:C.white,fontWeight:600}}>CoreIdentity</td><td style={{padding:'12px',color:C.slate}}>SaaS Platform</td>
              <td style={{padding:'12px',color:C.gold,fontFamily:'monospace'}}>{fmtK(last(ciRev))}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace'}}>{fmtK(last(ciCost))}</td>
              <td style={{padding:'12px',color:C.green,fontFamily:'monospace'}}>{fmtK(last(ciRev)-last(ciCost))}</td>
              <td style={{padding:'12px',color:C.teal}}>{Math.round((last(ciRev)-last(ciCost))/last(ciRev)*100)}%</td>
              <td style={{padding:'12px',color:C.white}}>{d?.coreIdentity?.agents?.length||15}</td>
            </tr>
            <tr style={{borderBottom:'1px solid '+C.border}}>
              <td style={{padding:'12px',color:C.white,fontWeight:600}}>CIAG</td><td style={{padding:'12px',color:C.slate}}>Advisory Group</td>
              <td style={{padding:'12px',color:C.gold,fontFamily:'monospace'}}>{fmtK(last(cgRev))}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace'}}>{fmtK(last(cgCost))}</td>
              <td style={{padding:'12px',color:C.green,fontFamily:'monospace'}}>{fmtK(last(cgRev)-last(cgCost))}</td>
              <td style={{padding:'12px',color:C.teal}}>{Math.round((last(cgRev)-last(cgCost))/last(cgRev)*100)}%</td>
              <td style={{padding:'12px',color:C.white}}>{d?.ciag?.agents?.length||8}</td>
            </tr>
            <tr style={{background:C.border+'33'}}>
              <td style={{padding:'12px',color:C.gold,fontWeight:700}}>CHC Consolidated</td><td style={{padding:'12px',color:C.slate}}>Holding Company</td>
              <td style={{padding:'12px',color:C.gold,fontFamily:'monospace',fontWeight:700}}>{fmtK(curRev)}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace',fontWeight:700}}>{fmtK(curCost)}</td>
              <td style={{padding:'12px',color:C.green,fontFamily:'monospace',fontWeight:700}}>{fmtK(curProf)}</td>
              <td style={{padding:'12px',color:C.teal,fontWeight:700}}>{curMgn}%</td>
              <td style={{padding:'12px',color:C.white,fontWeight:700}}>{d?.agents?.total||23}</td>
            </tr>
          </tbody>
        </table></>
      )}
    </div>
  );
}

function CoreIdentityView({vm, d}) {
  const ci     = d?.coreIdentity;
  const ciRev  = ci?.monthly?.revenue  || FB.ciRev;
  const ciCost = ci?.monthly?.costs    || FB.ciCost;
  const ciTgt  = ci?.monthly?.targets  || FB.ciTgt;
  const agents = ci?.agents || [];
  const curRev=last(ciRev), curCost=last(ciCost), curProf=curRev-curCost;
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="MRR"        value={fmtK(curRev)}    sub={delta(curRev,ciRev[10])+'% MoM'} trend={parseFloat(delta(curRev,ciRev[10]))} />
        <Card label="ARR"        value={fmtK(curRev*12)} sub="Platform run rate"                accent={C.blue} />
        <Card label="Net Profit" value={fmtK(curProf)}   sub={Math.round(curProf/curRev*100)+'% margin'} accent={C.green} />
        <Card label="NRR"        value={(ci?.nrr||118)+'%'} sub="Net revenue retention"         accent={C.teal} trend={18} />
        <Card label="Customers"  value={ci?.customers||8}   sub="Enterprise clients"            accent={C.gold} />
        <Card label="Agents"     value={agents.length||15}  sub="100% governed"                 accent={C.gold} />
      </div>
      {vm==='trend' && (<><SecHdr title="CoreIdentity — 12-Month Trend" live={!!ci}/><ResponsiveContainer width="100%" height={240}><AreaChart data={trend(ciRev,ciCost,ciTgt)}><defs><linearGradient id="ciG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.blue} stopOpacity={0.3}/><stop offset="95%" stopColor={C.blue} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.blue} fill="url(#ciG)" strokeWidth={2}/><Line type="monotone" dataKey="Target" stroke={C.slate} strokeWidth={1} strokeDasharray="4 4" dot={false}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="CoreIdentity — vs Targets" live={!!ci}/><ResponsiveContainer width="100%" height={240}><BarChart data={variance(ciRev,ciTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.blue} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></>)}
      <div style={{marginTop:24}}>
        <SecHdr title={'Platform Agents ('+(agents.length||15)+' · 100% governed)'} live={!!ci}/>
        <table style={{width:'100%', borderCollapse:'collapse', fontSize:12}}>
          <thead><tr style={{borderBottom:'1px solid '+C.border}}>{['Agent','Category','Status','Executions','Uptime','Governed'].map(h => <th key={h} style={{textAlign:'left',padding:'8px 10px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>{h}</th>)}</tr></thead>
          <tbody>{(agents.length ? agents : [{name:'Loading…',category:'—',status:'ACTIVE',executions:0,uptime:0,governed:true}]).map((a,i) => (
            <tr key={i} style={{borderBottom:'1px solid '+C.border+'66'}}>
              <td style={{padding:'10px',color:C.white}}>{a.name}</td><td style={{padding:'10px',color:C.slate}}>{a.category}</td>
              <td style={{padding:'10px'}}><Pill label={a.status||'Active'} color={C.green}/></td>
              <td style={{padding:'10px',color:C.gold,fontFamily:'monospace'}}>{(a.executions||0).toLocaleString()}</td>
              <td style={{padding:'10px',color:C.teal,fontFamily:'monospace'}}>{a.uptime||'—'}%</td>
              <td style={{padding:'10px'}}><Pill label={a.governed?'Yes':'No'} color={a.governed?C.teal:C.red}/></td>
            </tr>
          ))}</tbody>
        </table>
      </div>
    </div>
  );
}

function CIAGView({vm, d}) {
  const cg      = d?.ciag;
  const cgRev   = cg?.monthly ? cg.monthly.retainerRevenue.map((r,i) => r + cg.monthly.projectRevenue[i]) : FB.cgRev;
  const cgCost  = cg?.monthly?.costs   || FB.cgCost;
  const cgTgt   = cg?.monthly?.targets || FB.cgTgt;
  const retainers = cg?.retainers || [];
  const projects  = cg?.projects  || [];
  const agents    = cg?.agents    || [];
  const curRev=last(cgRev), curCost=last(cgCost), curProf=curRev-curCost;
  const pipeline = projects.reduce((s,p) => s+(p.value||0), 0);
  const FB_RET = [{client:'Meridian Wealth Partners LLC',monthly:22000,since:'Mar 2025',frameworks:['GLBA','CCPA']},{client:'Harbor Point Investment Group',monthly:18000,since:'May 2025',frameworks:['GLBA','SOX']},{client:'Pacific Crest Financial Services',monthly:28000,since:'Jun 2025',frameworks:['CCPA','PCI-DSS']},{client:'Summit Valley Bank',monthly:20000,since:'Sep 2025',frameworks:['FFIEC','GLBA']}];
  const FB_PROJ = [{name:'AI Governance Readiness Assessment',client:'Westlake Regional CU',value:85000,completion:68},{name:'CCPA + GLBA Compliance Mapping',client:'Meridian Wealth Partners',value:45000,completion:82},{name:'Texas RAIGA Implementation Plan',client:'Regional Bank Consortium',value:120000,completion:35}];
  const FB_AG = [{name:'Client Assessment Agent',executions:3204},{name:'Regulatory Mapping Agent',executions:2891},{name:'Compliance Gap Analyzer',executions:4102},{name:'Executive Report Generator',executions:1203},{name:'Risk Scoring Agent',executions:5671},{name:'Remediation Planner',executions:2341},{name:'Client Portal Agent',executions:8934},{name:'Engagement Tracker',executions:1567}];
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Total Revenue"    value={fmtK(curRev)}     sub={delta(curRev,cgRev[10])+'% MoM'} trend={parseFloat(delta(curRev,cgRev[10]))} />
        <Card label="Retainer MRR"     value={fmtK(cg?.metrics?.retainerMrr||last(FB.cgRet))} sub={(retainers.length||4)+' retainers'} accent={C.blue} />
        <Card label="Project Revenue"  value={fmtK(cg?.metrics?.projectRevenue||last(FB.cgProj))} sub={(projects.length||3)+' projects'} accent={C.teal} />
        <Card label="Net Profit"       value={fmtK(curProf)}    sub={Math.round(curProf/curRev*100)+'% margin'} accent={C.green} />
        <Card label="Pipeline"         value={fmtK(pipeline||250000)} sub="Contracted value" accent={C.gold} />
      </div>
      {vm==='trend' && (<><SecHdr title="CIAG — 12-Month Trend" live={!!cg}/><ResponsiveContainer width="100%" height={240}><AreaChart data={trend(cgRev,cgCost,cgTgt)}><defs><linearGradient id="cgG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.teal} stopOpacity={0.3}/><stop offset="95%" stopColor={C.teal} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.teal} fill="url(#cgG)" strokeWidth={2}/><Line type="monotone" dataKey="Target" stroke={C.slate} strokeWidth={1} strokeDasharray="4 4" dot={false}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="CIAG — vs Targets" live={!!cg}/><ResponsiveContainer width="100%" height={240}><BarChart data={variance(cgRev,cgTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.teal} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></>)}
      <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, marginTop:24}}>
        <div>
          <SecHdr title={'Retainers ('+(retainers.length||4)+')'} live={!!cg}/>
          {(retainers.length ? retainers : FB_RET).map((r,i) => (
            <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'12px 16px',marginBottom:8}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}>
                <div style={{color:C.white,fontSize:13,fontWeight:500,marginBottom:4}}>{r.client}</div>
                <div style={{color:C.gold,fontFamily:'monospace',fontWeight:600}}>{fmtK(r.monthly)}<span style={{color:C.slate,fontWeight:400}}>/mo</span></div>
              </div>
              <div style={{color:C.slate,fontSize:11}}>{Array.isArray(r.frameworks)?r.frameworks.join(' · '):r.frameworks} · Since {r.since||r.started}</div>
            </div>
          ))}
        </div>
        <div>
          <SecHdr title={'Projects ('+(projects.length||3)+')'} live={!!cg}/>
          {(projects.length ? projects : FB_PROJ).map((p,i) => (
            <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'12px 16px',marginBottom:8}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:6}}>
                <div style={{color:C.white,fontSize:12,fontWeight:500,maxWidth:'70%'}}>{p.name}</div>
                <div style={{color:C.gold,fontFamily:'monospace',fontWeight:600}}>{fmtK(p.value)}</div>
              </div>
              <div style={{color:C.slate,fontSize:11,marginBottom:8}}>{p.client}{p.eta?' · '+p.eta:''}</div>
              <div style={{display:'flex',alignItems:'center',gap:10}}>
                <Bar2 value={p.completion||0} color={(p.completion||0)>70?C.green:(p.completion||0)>40?C.gold:C.blue}/>
                <span style={{color:C.slate,fontSize:11,whiteSpace:'nowrap'}}>{p.completion||0}%</span>
              </div>
            </div>
          ))}
          <div style={{marginTop:16}}>
            <SecHdr title={'Advisory Agents ('+(agents.length||8)+')'} live={!!cg}/>
            {(agents.length ? agents : FB_AG).map((a,i) => (
              <div key={i} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid '+C.border+'44',fontSize:12}}>
                <span style={{color:C.white}}>{a.name}</span>
                <span style={{color:C.gold,fontFamily:'monospace'}}>{(a.executions||0).toLocaleString()}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function ClientPortfolioView({d}) {
  const clients = d?.clients || [];
  const b = clients[0];
  if (!b) return (
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:200,color:C.slate}}>
      <div style={{textAlign:'center'}}><div style={{fontSize:24,marginBottom:8}}>⏳</div><div>Loading live bank data from GCP…</div></div>
    </div>
  );
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Client Accounts"   value={clients.length}        sub="Pilot client onboarded"  accent={C.gold} />
        <Card label="Agents Governed"   value={b.aiAgentsActive||23}  sub="100% of client agents"   accent={C.green} />
        <Card label="Penalty Mitigated" value={b.penaltyMitigated}    sub={b.name}                  accent={C.teal} trend={100} />
        <Card label="Compliance Lift"   value={'+'+(((b.complianceAfter||94)-b.complianceBefore)+'pts')} sub={b.complianceBefore+'% → '+(b.complianceAfter||94)+'%'} accent={C.blue} trend={29} />
      </div>
      <SecHdr title={'Client: '+b.name} live={true}/>
      <div style={{background:C.surface,border:'1px solid '+C.border,borderRadius:8,padding:24,marginBottom:24}}>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:24,marginBottom:24}}>
          <div>
            <div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:8}}>Client Details</div>
            <div style={{color:C.white,marginBottom:4}}>{b.name}</div>
            <div style={{color:C.slate,fontSize:12}}>{b.vertical}</div>
            <div style={{color:C.slate,fontSize:12}}>Assets: {fmtK(b.totalAssets||95100000)}</div>
            <div style={{color:C.slate,fontSize:12}}>Onboarded: {b.onboarded}</div>
            {b.criticalFindings > 0 && <div style={{color:C.orange,fontSize:12,marginTop:4}}>⚠ {b.criticalFindings} critical findings</div>}
          </div>
          <div>
            <div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:8}}>Live Compliance Score</div>
            <div style={{display:'flex',alignItems:'center',gap:12,marginBottom:8}}>
              <span style={{color:C.red,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{b.complianceBefore}%</span>
              <span style={{color:C.slate}}>→</span>
              <span style={{color:C.green,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{b.complianceAfter||94}%</span>
            </div>
            <Bar2 value={b.complianceAfter||94} color={C.green}/>
            {b.complianceStatus && <div style={{color:C.slate,fontSize:11,marginTop:6}}>{b.complianceStatus}</div>}
          </div>
          <div>
            <div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:8}}>AI Agents</div>
            <div style={{color:C.white,fontSize:22,fontWeight:700,fontFamily:'monospace',marginBottom:4}}>{b.aiAgentsActive||23}<span style={{color:C.slate,fontSize:13}}>/{b.aiAgentsActive||23} governed</span></div>
            <Pill label="Fully Governed" color={C.green}/>
            {b.fetchedAt && <div style={{color:C.slate,fontSize:10,marginTop:8}}>Live · {new Date(b.fetchedAt).toLocaleTimeString()}</div>}
          </div>
        </div>
        <div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:10}}>Regulatory Frameworks</div>
        <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(b.frameworks||[]).map(f => <Pill key={f} label={f} color={C.blue}/>)}</div>
      </div>
      <div style={{background:C.surface,border:'1px solid '+C.goldDim,borderRadius:8,padding:20,display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <div>
          <div style={{color:C.gold,fontSize:12,letterSpacing:'0.08em',textTransform:'uppercase',marginBottom:6}}>Regulatory Penalty Exposure Mitigated — Live GCP</div>
          <div style={{color:C.white,fontSize:13}}>CCPA violations · GLBA ($1M/day) · FFIEC regulatory action risk</div>
          {b.liveDataSource && <div style={{color:C.slate,fontSize:11,marginTop:4}}>Source: {b.liveDataSource}</div>}
        </div>
        <div style={{color:C.gold,fontFamily:'monospace',fontSize:36,fontWeight:700,whiteSpace:'nowrap'}}>{b.penaltyMitigated}</div>
      </div>
    </div>
  );
}

export default function FoundersDashboard() {
  const [tab, setTab]           = useState('consolidated');
  const [vm,  setVm]            = useState('actuals');
  const [liveData, setLiveData] = useState(null);
  const [loading,  setLoading]  = useState(true);
  const [meta,     setMeta]     = useState(null);
  const [err,      setErr]      = useState(null);

  const fetchData = useCallback(async () => {
    try {
      const res  = await fetch('/api/live-data');
      const json = await res.json();
      if (json.data) { setLiveData(json.data); setMeta({ fetchedAt: json.fetchedAt, latencyMs: json.latencyMs }); setErr(json.errors||null); }
    } catch(e) { setErr({ fetch: e.message }); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchData(); const t = setInterval(fetchData, 60000); return () => clearInterval(t); }, [fetchData]);

  const TABS  = [{id:'consolidated',label:'CHC Consolidated'},{id:'coreidentity',label:'CoreIdentity'},{id:'ciag',label:'CIAG'},{id:'clients',label:'Client Portfolio'}];
  const VIEWS = [{id:'actuals',label:'Actuals'},{id:'vs-targets',label:'vs Targets'},{id:'trend',label:'12-Month Trend'}];

  const ciRev   = liveData?.coreIdentity?.monthly?.revenue || FB.ciRev;
  const cgRev   = liveData?.ciag?.monthly ? liveData.ciag.monthly.retainerRevenue.map((r,i) => r + liveData.ciag.monthly.projectRevenue[i]) : FB.cgRev;
  const ciCost  = liveData?.coreIdentity?.monthly?.costs || FB.ciCost;
  const cgCost  = liveData?.ciag?.monthly?.costs || FB.cgCost;
  const chcRev  = ciRev.map((r,i) => r + cgRev[i]);
  const chcProf = chcRev.map((r,i) => r - ciCost[i] - cgCost[i]);
  const now     = new Date().toLocaleString('en-US', {month:'short', year:'numeric'});

  return (
    <div style={{background:C.bg, minHeight:'100vh', color:C.white, fontFamily:'-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'}}>
      <div style={{borderBottom:'1px solid '+C.border, padding:'18px 32px', display:'flex', justifyContent:'space-between', alignItems:'center'}}>
        <div>
          <div style={{fontSize:10, color:C.slate, letterSpacing:'0.15em', textTransform:'uppercase', marginBottom:4}}>Core Holding Corp</div>
          <div style={{fontSize:20, fontWeight:600}}>Founders Dashboard</div>
        </div>
        <div style={{display:'flex', gap:24, alignItems:'center'}}>
          <div style={{textAlign:'right'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>CHC Monthly Revenue</div><div style={{color:C.gold,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{fmtK(last(chcRev))}</div></div>
          <div style={{textAlign:'right'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>Net Profit</div><div style={{color:C.green,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{fmtK(last(chcProf))}</div></div>
          <div style={{display:'flex',flexDirection:'column',gap:4,alignItems:'flex-end'}}>
            <div style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'6px 14px',color:C.slate,fontSize:12}}>{now}</div>
            <button onClick={fetchData} style={{background:'none',border:'1px solid '+C.border,borderRadius:4,color:C.slate,fontSize:10,padding:'3px 10px',cursor:'pointer',letterSpacing:'0.08em'}}>↻ REFRESH</button>
          </div>
        </div>
      </div>
      <div style={{background:C.surface, borderBottom:'1px solid '+C.border, padding:'8px 32px', display:'flex', justifyContent:'space-between', fontSize:11}}>
        <span style={{color: loading ? C.slate : err ? C.orange : C.green}}>
          {loading ? '⏳ Loading live data…' : err ? '⚠ Partial data — some sources unavailable' : '● Live — both GCP services healthy'}
        </span>
        {meta && <span style={{color:C.slate}}>Updated {new Date(meta.fetchedAt).toLocaleTimeString()} · {meta.latencyMs}ms · Auto-refresh 60s</span>}
      </div>
      <div style={{borderBottom:'1px solid '+C.border, padding:'0 32px', display:'flex'}}>
        {TABS.map(t => <button key={t.id} onClick={()=>setTab(t.id)} style={{background:'none',border:'none',cursor:'pointer',padding:'14px 20px',fontSize:13,fontWeight:500,color:tab===t.id?C.gold:C.slate,borderBottom:tab===t.id?'2px solid '+C.gold:'2px solid transparent'}}>{t.label}</button>)}
      </div>
      <div style={{padding:'16px 32px', display:'flex', justifyContent:'flex-end', borderBottom:'1px solid '+C.border+'55'}}>
        <div style={{display:'flex', background:C.surface, border:'1px solid '+C.border, borderRadius:6, overflow:'hidden'}}>
          {VIEWS.map(v => <button key={v.id} onClick={()=>setVm(v.id)} style={{background:vm===v.id?C.border:'none',border:'none',cursor:'pointer',padding:'6px 16px',fontSize:12,color:vm===v.id?C.white:C.slate}}>{v.label}</button>)}
        </div>
      </div>
      <div style={{padding:'28px 32px'}}>
        {tab==='consolidated' && <ConsolidatedView vm={vm} d={liveData}/>}
        {tab==='coreidentity' && <CoreIdentityView vm={vm} d={liveData}/>}
        {tab==='ciag'         && <CIAGView         vm={vm} d={liveData}/>}
        {tab==='clients'      && <ClientPortfolioView d={liveData}/>}
      </div>
    </div>
  );
}
