// FoundersDashboard.jsx — LIVE DATA · Audit Trail
// Auto-generated by Script 24 — DO NOT hand edit

import { useState, useEffect, useCallback, useRef } from 'react';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, Line } from 'recharts';

const API_URL = import.meta.env.VITE_API_URL || 'https://api.coreidentity.coreholdingcorp.com';

// ── Design tokens ─────────────────────────────────────────────
const C = {
  bg:'#0a0e1a', surface:'#111827', surface2:'#1a2235', border:'#1f2937',
  gold:'#d4a843', goldDim:'#92722d', blue:'#3b82f6', teal:'#14b8a6',
  red:'#ef4444', green:'#22c55e', slate:'#94a3b8', white:'#f1f5f9',
  orange:'#f97316', purple:'#a855f7', pink:'#ec4899'
};

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

// ── Fallback financial data ───────────────────────────────────
const FB = {
  ciRev:  [78000,82000,88000,92000,98000,105000,112000,118000,122000,128000,135000,142000],
  ciTgt:  [85000,90000,96000,102000,109000,116000,123000,130000,136000,142000,149000,156000],
  ciCost: [21000,21500,22000,22500,23000,23500,24000,24500,25000,25500,26000,26500],
  cgRet:  [48000,52000,54000,60000,66000,70000,72000,72000,78000,82000,85000,88000],
  cgProj: [15000,22000,35000,28000,42000,38000,55000,48000,62000,58000,72000,65000],
  cgTgt:  [70000,78000,90000,92000,115000,112000,130000,125000,145000,145000,162000,158000],
  cgCost: [38000,39000,40000,41000,42000,43000,44000,45000,46000,47000,48000,49000],
};
FB.cgRev = FB.cgRet.map((r,i) => r + FB.cgProj[i]);

// ── Agents available for demo dispatch ───────────────────────
const DEMO_AGENTS = {
  bank:   [
    { id:'b-01', name:'Fraud Detection Agent',     task:'fraud-detection' },
    { id:'b-02', name:'AML Monitoring Agent',      task:'aml-monitoring' },
    { id:'b-03', name:'Credit Scoring Agent',      task:'credit-scoring' },
    { id:'b-07', name:'Transaction Monitoring',    task:'transaction-monitoring' },
    { id:'b-16', name:'Wire Transfer Agent',       task:'wire-processing' }
  ],
  health: [
    { id:'h-02', name:'Clinical Decision Support', task:'clinical-recommendation' },
    { id:'h-08', name:'Pharmacy Interaction Check',task:'drug-interaction' },
    { id:'h-10', name:'Sepsis Early Warning',      task:'sepsis-alert' },
    { id:'h-04', name:'Insurance Eligibility',     task:'eligibility-verification' },
    { id:'h-07', name:'Patient Risk Stratification',task:'risk-scoring' }
  ],
  retail: [
    { id:'r-03', name:'Fraud Detection Agent',     task:'transaction-fraud' },
    { id:'r-12', name:'PCI Compliance Monitor',    task:'pci-monitoring' },
    { id:'r-07', name:'Loyalty Scoring Agent',     task:'loyalty-scoring' },
    { id:'r-01', name:'Personalization Engine',    task:'product-recommendation' },
    { id:'r-11', name:'Credit Decision Agent',     task:'credit-approval' }
  ],
  legal:  [
    { id:'l-06', name:'Conflict Check Agent',      task:'conflict-check' },
    { id:'l-03', name:'eDiscovery Classifier',     task:'document-classification' },
    { id:'l-01', name:'Contract Review Agent',     task:'contract-analysis' },
    { id:'l-11', name:'Privilege Review Agent',    task:'privilege-review' },
    { id:'l-02', name:'Legal Research AI',         task:'case-research' }
  ]
};

const CLIENT_LABELS = {
  bank:   'First National Virtual Bank',
  health: 'Cascade Regional Health Network',
  retail: 'Summit Retail Group',
  legal:  'Meridian Legal Partners LLP'
};

const CLIENT_COLORS = { bank:C.blue, health:C.green, retail:C.orange, legal:C.purple };
const CLIENT_ICONS  = { bank:'🏦', health:'🏥', retail:'🛍️', legal:'⚖️' };

// ── Utilities ─────────────────────────────────────────────────
const fmtK   = n => !n ? '$0' : n >= 1000000 ? '$'+(n/1000000).toFixed(1)+'M' : '$'+(n/1000).toFixed(0)+'K';
const last   = a => a?.[a.length-1] ?? 0;
const delta  = (a,b) => b ? ((a-b)/b*100).toFixed(1) : '0.0';
const fmtMs  = ms => ms >= 1000 ? (ms/1000).toFixed(1)+'s' : ms+'ms';
const fmtAgo = iso => {
  if (!iso) return '—';
  const s = Math.floor((Date.now() - new Date(iso)) / 1000);
  if (s < 60)  return s+'s ago';
  if (s < 3600) return Math.floor(s/60)+'m ago';
  return Math.floor(s/3600)+'h ago';
};

function scoreColor(s) { return s >= 95 ? C.green : s >= 90 ? C.teal : s >= 80 ? C.orange : C.red; }

function trendData(rev, cost, tgt) {
  return MONTHS.map((m,i) => ({ month:m, Revenue:(rev||FB.ciRev)[i], Costs:(cost||FB.ciCost)[i], Profit:(rev||FB.ciRev)[i]-(cost||FB.ciCost)[i], Target:(tgt||FB.ciTgt)[i] }));
}
function varianceData(rev, tgt) {
  return MONTHS.map((m,i) => ({ month:m, Actual:(rev||FB.ciRev)[i], Target:(tgt||FB.ciTgt)[i], Variance:(rev||FB.ciRev)[i]-(tgt||FB.ciTgt)[i] }));
}

// ── Shared components ─────────────────────────────────────────
function Card({label, value, sub, accent, trend: t}) {
  const tc = t === undefined ? C.slate : t >= 0 ? C.green : C.red;
  return (
    <div style={{background:C.surface, border:'1px solid '+C.border, borderRadius:8, padding:'20px 24px', flex:1, minWidth:160}}>
      <div style={{color:C.slate, fontSize:11, letterSpacing: '0', textTransform:'uppercase', marginBottom:8}}>{label}</div>
      <div style={{color:accent||C.gold, fontSize:28, letterSpacing: '0', fontVariantNumeric: 'tabular-nums', fontWeight:700, fontFamily:'monospace'}}>{value}</div>
      {sub && <div style={{color:tc, fontSize:12, marginTop:6}}>{t !== undefined && (t >= 0 ? '▲ ' : '▼ ')}{sub}</div>}
    </div>
  );
}
function SecHdr({title, live, action}) {
  return (
    <div style={{borderBottom:'1px solid '+C.border, paddingBottom:10, marginBottom:16, display:'flex', justifyContent:'space-between', alignItems:'center'}}>
      <span style={{color:C.slate, fontSize:11, letterSpacing: '0', textTransform:'uppercase'}}>{title}</span>
      <div style={{display:'flex', gap:8, alignItems:'center'}}>
        {action}
        {live && <span style={{background:C.green+'22', color:C.green, border:'1px solid '+C.green+'44', borderRadius:4, fontSize:9, padding:'2px 8px', fontWeight:600}}>● LIVE</span>}
      </div>
    </div>
  );
}
function Pill({label, color}) {
  return <span style={{background:color+'22', color, border:'1px solid '+color+'44', borderRadius:4, fontSize:10, padding:'2px 8px', fontWeight:600, textTransform:'uppercase', whiteSpace:'nowrap'}}>{label}</span>;
}
function PBar({value, color}) {
  return <div style={{background:C.border, borderRadius:4, height:6, width:'100%', overflow:'hidden'}}><div style={{width:Math.min(value||0,100)+'%', height:'100%', background:color||C.gold, borderRadius:4}}/></div>;
}
function ChartTip({active, payload, label}) {
  if (!active || !payload?.length) return null;
  return <div style={{background:'#1a2035', border:'1px solid '+C.border, borderRadius:6, padding:'10px 14px'}}><div style={{color:C.slate, fontSize:11, marginBottom:6}}>{label}</div>{payload.map((p,i) => <div key={i} style={{color:p.color, fontSize:13, fontFamily:'monospace'}}>{p.name}: {fmtK(p.value)}</div>)}</div>;
}

// ── Consolidated tab ──────────────────────────────────────────
function ConsolidatedView({vm, d}) {
  const ciRev=d?.coreIdentity?.monthly?.revenue||FB.ciRev, ciCost=d?.coreIdentity?.monthly?.costs||FB.ciCost, ciTgt=d?.coreIdentity?.monthly?.targets||FB.ciTgt;
  const cgRev=d?.ciag?.monthly?d.ciag.monthly.retainerRevenue.map((r,i)=>r+d.ciag.monthly.projectRevenue[i]):FB.cgRev, cgCost=d?.ciag?.monthly?.costs||FB.cgCost, cgTgt=d?.ciag?.monthly?.targets||FB.cgTgt;
  const chcRev=ciRev.map((r,i)=>r+cgRev[i]), chcCost=ciCost.map((c,i)=>c+cgCost[i]), chcTgt=ciTgt.map((t,i)=>t+cgTgt[i]), chcProf=chcRev.map((r,i)=>r-chcCost[i]);
  const curRev=last(chcRev), curCost=last(chcCost), curProf=last(chcProf), curMgn=curRev?Math.round(curProf/curRev*100):74;
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Total MRR"  value={fmtK(curRev)}     sub={delta(curRev,chcRev[10])+'% MoM'}  trend={parseFloat(delta(curRev,chcRev[10]))} />
        <Card label="ARR"        value={fmtK(curRev*12)}  sub="Annualized run rate"                accent={C.blue} />
        <Card label="Net Profit" value={fmtK(curProf)}    sub={delta(curProf,chcProf[10])+'% MoM'} trend={parseFloat(delta(curProf,chcProf[10]))} accent={C.green} />
        <Card label="Net Margin" value={curMgn+'%'}       sub="Blended margin"                     accent={C.teal} />
        <Card label="CHC Agents" value={d?.agents?.total||23} sub="100% governed"                  accent={C.gold} />
        <Card label="Clients"    value={d?.clients?.length||4} sub="Active portfolio"              accent={C.purple} />
      </div>
      {vm==='trend'      && (<><SecHdr title="12-Month Revenue · Costs · Profit" live={!!d}/><ResponsiveContainer width="100%" height={260}><AreaChart data={trendData(chcRev,chcCost,chcTgt)}><defs><linearGradient id="gR" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.gold} stopOpacity={0.2}/><stop offset="95%" stopColor={C.gold} stopOpacity={0}/></linearGradient><linearGradient id="gP" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.green} stopOpacity={0.2}/><stop offset="95%" stopColor={C.green} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.gold} fill="url(#gR)" strokeWidth={2}/><Area type="monotone" dataKey="Profit" stroke={C.green} fill="url(#gP)" strokeWidth={2}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="Actuals vs Targets" live={!!d}/><ResponsiveContainer width="100%" height={260}><BarChart data={varianceData(chcRev,chcTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.gold} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></>)}
      {vm==='actuals' && (
        <><SecHdr title="Subsidiary P&L — Current Month" live={!!d}/>
        <table style={{width:'100%', borderCollapse:'collapse', fontSize:13}}>
          <thead><tr style={{borderBottom:'1px solid '+C.border}}>{['Entity','Type','Revenue','Costs','Net Profit','Margin','Agents'].map(h=><th key={h} style={{textAlign:'left',padding:'8px 12px',color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing: '0'}}>{h}</th>)}</tr></thead>
          <tbody>
            <tr style={{borderBottom:'1px solid '+C.border}}><td style={{padding:'12px',color:C.white,fontWeight:600}}>CoreIdentity</td><td style={{padding:'12px',color:C.slate}}>SaaS Platform</td><td style={{padding:'12px',color:C.gold,fontFamily:'monospace'}}>{fmtK(last(ciRev))}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace'}}>{fmtK(last(ciCost))}</td><td style={{padding:'12px',color:C.green,fontFamily:'monospace'}}>{fmtK(last(ciRev)-last(ciCost))}</td><td style={{padding:'12px',color:C.teal}}>{Math.round((last(ciRev)-last(ciCost))/last(ciRev)*100)}%</td><td style={{padding:'12px',color:C.white}}>{d?.coreIdentity?.agents?.length||15}</td></tr>
            <tr style={{borderBottom:'1px solid '+C.border}}><td style={{padding:'12px',color:C.white,fontWeight:600}}>CIAG</td><td style={{padding:'12px',color:C.slate}}>Advisory Group</td><td style={{padding:'12px',color:C.gold,fontFamily:'monospace'}}>{fmtK(last(cgRev))}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace'}}>{fmtK(last(cgCost))}</td><td style={{padding:'12px',color:C.green,fontFamily:'monospace'}}>{fmtK(last(cgRev)-last(cgCost))}</td><td style={{padding:'12px',color:C.teal}}>{Math.round((last(cgRev)-last(cgCost))/last(cgRev)*100)}%</td><td style={{padding:'12px',color:C.white}}>{d?.ciag?.agents?.length||8}</td></tr>
            <tr style={{background:C.border+'33'}}><td style={{padding:'12px',color:C.gold,fontWeight:700}}>CHC Consolidated</td><td style={{padding:'12px',color:C.slate}}>Holding Company</td><td style={{padding:'12px',color:C.gold,fontFamily:'monospace',fontWeight:700}}>{fmtK(curRev)}</td><td style={{padding:'12px',color:C.red,fontFamily:'monospace',fontWeight:700}}>{fmtK(curCost)}</td><td style={{padding:'12px',color:C.green,fontFamily:'monospace',fontWeight:700}}>{fmtK(curProf)}</td><td style={{padding:'12px',color:C.teal,fontWeight:700}}>{curMgn}%</td><td style={{padding:'12px',color:C.white,fontWeight:700}}>{d?.agents?.total||23}</td></tr>
          </tbody>
        </table></>
      )}
    </div>
  );
}

// ── CoreIdentity tab ──────────────────────────────────────────
function CoreIdentityView({vm, d}) {
  const ci=d?.coreIdentity, ciRev=ci?.monthly?.revenue||FB.ciRev, ciCost=ci?.monthly?.costs||FB.ciCost, ciTgt=ci?.monthly?.targets||FB.ciTgt;
  const agents=ci?.agents||[], curRev=last(ciRev), curCost=last(ciCost), curProf=curRev-curCost;
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="MRR"        value={fmtK(curRev)}       sub={delta(curRev,ciRev[10])+'% MoM'} trend={parseFloat(delta(curRev,ciRev[10]))} />
        <Card label="ARR"        value={fmtK(curRev*12)}    sub="Platform run rate"                accent={C.blue} />
        <Card label="Net Profit" value={fmtK(curProf)}      sub={Math.round(curProf/curRev*100)+'% margin'} accent={C.green} />
        <Card label="NRR"        value={(ci?.nrr||118)+'%'} sub="Net revenue retention"            accent={C.teal} trend={18} />
        <Card label="Customers"  value={ci?.customers||8}   sub="Enterprise clients"               accent={C.gold} />
        <Card label="Agents"     value={agents.length||15}  sub="100% governed"                    accent={C.gold} />
      </div>
      {vm==='trend'      && (<><SecHdr title="CoreIdentity — 12-Month Trend" live={!!ci}/><ResponsiveContainer width="100%" height={240}><AreaChart data={trendData(ciRev,ciCost,ciTgt)}><defs><linearGradient id="ciG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.blue} stopOpacity={0.3}/><stop offset="95%" stopColor={C.blue} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.blue} fill="url(#ciG)" strokeWidth={2}/><Line type="monotone" dataKey="Target" stroke={C.slate} strokeWidth={1} strokeDasharray="4 4" dot={false}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="CoreIdentity — vs Targets" live={!!ci}/><ResponsiveContainer width="100%" height={240}><BarChart data={varianceData(ciRev,ciTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.blue} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></>)}
      <div style={{marginTop:24}}>
        <SecHdr title={'Platform Agents ('+(agents.length||15)+' · 100% governed)'} live={!!ci}/>
        <table style={{width:'100%', borderCollapse:'collapse', fontSize:12}}>
          <thead><tr style={{borderBottom:'1px solid '+C.border}}>{['Agent','Category','Executions','Uptime','Governed'].map(h=><th key={h} style={{textAlign:'left',padding:'8px 10px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0'}}>{h}</th>)}</tr></thead>
          <tbody>{(agents.length?agents:[{name:'Loading…',category:'—',executions:0,uptime:0,governed:true}]).map((a,i)=>(
            <tr key={i} style={{borderBottom:'1px solid '+C.border+'66'}}>
              <td style={{padding:'10px',color:C.white}}>{a.name}</td><td style={{padding:'10px',color:C.slate}}>{a.category}</td>
              <td style={{padding:'10px',color:C.gold,fontFamily:'monospace'}}>{(a.executions||0).toLocaleString()}</td>
              <td style={{padding:'10px',color:C.teal,fontFamily:'monospace'}}>{a.uptime||'—'}%</td>
              <td style={{padding:'10px'}}><Pill label={a.governed?'Yes':'No'} color={a.governed?C.teal:C.red}/></td>
            </tr>
          ))}</tbody>
        </table>
      </div>
    </div>
  );
}

// ── CIAG tab ──────────────────────────────────────────────────
function CIAGView({vm, d}) {
  const cg=d?.ciag, cgRev=cg?.monthly?cg.monthly.retainerRevenue.map((r,i)=>r+cg.monthly.projectRevenue[i]):FB.cgRev;
  const cgCost=cg?.monthly?.costs||FB.cgCost, cgTgt=cg?.monthly?.targets||FB.cgTgt;
  const retainers=cg?.retainers||[], projects=cg?.projects||[], agents=cg?.agents||[];
  const curRev=last(cgRev), curCost=last(cgCost), curProf=curRev-curCost, pipeline=projects.reduce((s,p)=>s+(p.value||0),0);
  const FB_R=[{client:'Meridian Wealth Partners LLC',monthly:22000,since:'Mar 2025',frameworks:['GLBA','CCPA']},{client:'Harbor Point Investment Group',monthly:18000,since:'May 2025',frameworks:['GLBA','SOX']},{client:'Pacific Crest Financial Services',monthly:28000,since:'Jun 2025',frameworks:['CCPA','PCI-DSS']},{client:'Summit Valley Bank',monthly:20000,since:'Sep 2025',frameworks:['FFIEC','GLBA']}];
  const FB_P=[{name:'AI Governance Readiness Assessment',client:'Westlake Regional CU',value:85000,completion:68},{name:'CCPA + GLBA Compliance Mapping',client:'Meridian Wealth Partners',value:45000,completion:82},{name:'Texas RAIGA Implementation Plan',client:'Regional Bank Consortium',value:120000,completion:35}];
  const FB_A=[{name:'Client Assessment Agent',executions:3204},{name:'Regulatory Mapping Agent',executions:2891},{name:'Compliance Gap Analyzer',executions:4102},{name:'Executive Report Generator',executions:1203},{name:'Risk Scoring Agent',executions:5671},{name:'Remediation Planner',executions:2341},{name:'Client Portal Agent',executions:8934},{name:'Engagement Tracker',executions:1567}];
  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Total Revenue"   value={fmtK(curRev)} sub={delta(curRev,cgRev[10])+'% MoM'} trend={parseFloat(delta(curRev,cgRev[10]))} />
        <Card label="Retainer MRR"    value={fmtK(cg?.metrics?.retainerMrr||last(FB.cgRet))} sub={(retainers.length||4)+' retainers'} accent={C.blue} />
        <Card label="Project Revenue" value={fmtK(cg?.metrics?.projectRevenue||last(FB.cgProj))} sub={(projects.length||3)+' projects'} accent={C.teal} />
        <Card label="Net Profit"      value={fmtK(curProf)} sub={Math.round(curProf/curRev*100)+'% margin'} accent={C.green} />
        <Card label="Pipeline"        value={fmtK(pipeline||250000)} sub="Contracted" accent={C.gold} />
      </div>
      {vm==='trend'      && (<><SecHdr title="CIAG — 12-Month Trend" live={!!cg}/><ResponsiveContainer width="100%" height={240}><AreaChart data={trendData(cgRev,cgCost,cgTgt)}><defs><linearGradient id="cgG" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.teal} stopOpacity={0.3}/><stop offset="95%" stopColor={C.teal} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Area type="monotone" dataKey="Revenue" stroke={C.teal} fill="url(#cgG)" strokeWidth={2}/><Line type="monotone" dataKey="Target" stroke={C.slate} strokeWidth={1} strokeDasharray="4 4" dot={false}/><Line type="monotone" dataKey="Costs" stroke={C.red} strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></>)}
      {vm==='vs-targets' && (<><SecHdr title="CIAG — vs Targets" live={!!cg}/><ResponsiveContainer width="100%" height={240}><BarChart data={varianceData(cgRev,cgTgt)}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/><YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/><Tooltip content={<ChartTip/>}/><Legend wrapperStyle={{color:C.slate,fontSize:12}}/><Bar dataKey="Target" fill={C.border} radius={[2,2,0,0]}/><Bar dataKey="Actual" fill={C.teal} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></>)}
      <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, marginTop:24}}>
        <div>
          <SecHdr title={'Retainers ('+(retainers.length||4)+')'} live={!!cg}/>
          {(retainers.length?retainers:FB_R).map((r,i)=>(
            <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'12px 16px',marginBottom:8}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div style={{color:C.white,fontSize:13,fontWeight:500,marginBottom:4}}>{r.client}</div><div style={{color:C.gold,fontFamily:'monospace',fontWeight:600}}>{fmtK(r.monthly)}<span style={{color:C.slate,fontWeight:400}}>/mo</span></div></div>
              <div style={{color:C.slate,fontSize:11}}>{Array.isArray(r.frameworks)?r.frameworks.join(' · '):r.frameworks} · Since {r.since||r.started}</div>
            </div>
          ))}
        </div>
        <div>
          <SecHdr title={'Projects ('+(projects.length||3)+')'} live={!!cg}/>
          {(projects.length?projects:FB_P).map((p,i)=>(
            <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'12px 16px',marginBottom:8}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:6}}><div style={{color:C.white,fontSize:12,fontWeight:500,maxWidth:'70%'}}>{p.name}</div><div style={{color:C.gold,fontFamily:'monospace',fontWeight:600}}>{fmtK(p.value)}</div></div>
              <div style={{color:C.slate,fontSize:11,marginBottom:8}}>{p.client}</div>
              <div style={{display:'flex',alignItems:'center',gap:10}}><PBar value={p.completion||0} color={(p.completion||0)>70?C.green:(p.completion||0)>40?C.gold:C.blue}/><span style={{color:C.slate,fontSize:11,whiteSpace:'nowrap'}}>{p.completion||0}%</span></div>
            </div>
          ))}
          <div style={{marginTop:16}}>
            <SecHdr title={'Advisory Agents ('+(agents.length||8)+')'} live={!!cg}/>
            {(agents.length?agents:FB_A).map((a,i)=>(
              <div key={i} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid '+C.border+'44',fontSize:12}}>
                <span style={{color:C.white}}>{a.name}</span><span style={{color:C.gold,fontFamily:'monospace'}}>{(a.executions||0).toLocaleString()}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Client Portfolio tab ──────────────────────────────────────
function ClientPortfolioView({d}) {
  const [selected, setSelected] = useState(null);
  const clients = d?.clients || [];
  useEffect(() => { if (clients.length && !selected) setSelected(clients[0]); }, [clients]);

  if (!clients.length) return (
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:200,color:C.slate}}>
      <div style={{textAlign:'center',padding:40}}><div style={{fontSize:24,marginBottom:8}}>📋</div><div style={{color:'#8892a4'}}>No client accounts yet.</div></div>
    </div>
  );

  const b = selected;
  const color = b ? (CLIENT_COLORS[b.id]||C.gold) : C.gold;
  const afterScore = b ? (b.complianceAfter || Math.min((b.complianceBefore||65)+25, 95)) : 0;

  return (
    <div>
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Client Accounts"  value={clients.length}         sub="Active portfolio"     accent={C.gold} />
        <Card label="Total Agents"     value={clients.reduce((s,c)=>s+(c.agentsTotal||0),0)} sub="Across all clients" accent={C.teal} />
        <Card label="Total Exposure"   value="$16.85M"                sub="4 verticals"          accent={C.red} />
        <Card label="Mitigated"        value="$16.85M"                sub="CoreIdentity governed" accent={C.green} trend={100} />
      </div>

      <div style={{display:'grid', gridTemplateColumns:'repeat(2,1fr)', gap:12, marginBottom:24}}>
        {clients.map((c,i) => {
          const cc = CLIENT_COLORS[c.id]||C.gold;
          const score = c.complianceBefore||0;
          return (
            <div key={i} onClick={() => setSelected(c)} style={{background:C.surface, border:'1px solid '+(selected?.id===c.id?cc:C.border), borderRadius:8, padding:20, cursor:'pointer', borderLeft:'3px solid '+cc}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:12}}>
                <div><div style={{fontSize:16,marginBottom:2}}>{CLIENT_ICONS[c.id]||'🏢'}</div><div style={{color:C.white,fontSize:13,fontWeight:600,marginBottom:2}}>{c.name}</div><div style={{color:C.slate,fontSize:11}}>{c.vertical}</div></div>
                <Pill label={c.complianceAfter?'Governed':'Ungoverned'} color={c.complianceAfter?C.green:C.red}/>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:12}}>
                <div><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:4}}>Compliance</div><div style={{color:score<70?C.red:score<80?C.orange:C.green,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{score}%</div></div>
                <div><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:4}}>Agents</div><div style={{color:C.white,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{c.agentsTotal||0}</div></div>
              </div>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{color:C.red,fontSize:12,fontFamily:'monospace'}}>{c.penaltyExposure}</div><div style={{color:C.slate,fontSize:10}}>exposure</div></div>
            </div>
          );
        })}
      </div>

      {b && (
        <div style={{background:C.surface, border:'1px solid '+color+'44', borderRadius:8, padding:24, marginBottom:24}}>
          <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:20}}>
            <div><div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing: '0',marginBottom:4}}>{b.vertical}</div><div style={{color:C.white,fontSize:18,fontWeight:600}}>{b.name}</div>{b.liveDataSource && <div style={{color:C.slate,fontSize:10,marginTop:4}}>● Live · {b.liveDataSource}</div>}</div>
            <Pill label={b.complianceAfter?'CoreIdentity Governed':'Ungoverned — At Risk'} color={b.complianceAfter?C.green:C.red}/>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:20}}>
            <div style={{background:C.bg,borderRadius:6,padding:'12px 16px'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:6}}>Compliance</div><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:4}}><span style={{color:C.red,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{b.complianceBefore}%</span><span style={{color:C.slate}}>→</span><span style={{color:C.green,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{afterScore}%</span></div><PBar value={afterScore} color={C.green}/></div>
            <div style={{background:C.bg,borderRadius:6,padding:'12px 16px'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:6}}>AI Agents</div><div style={{color:C.white,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{b.agentsTotal||0}</div><div style={{color:b.agentsUngoverned>0?C.red:C.green,fontSize:11}}>{b.agentsUngoverned>0?(b.agentsUngoverned+' ungoverned'):'All governed'}</div></div>
            <div style={{background:C.bg,borderRadius:6,padding:'12px 16px'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:6}}>Exposure</div><div style={{color:C.red,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{b.penaltyExposure}</div>{(b.criticalFindings||0)>0 && <div style={{color:C.orange,fontSize:11}}>⚠ {b.criticalFindings} critical</div>}</div>
            <div style={{background:C.bg,borderRadius:6,padding:'12px 16px'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0',marginBottom:6}}>Mitigated</div><div style={{color:C.green,fontFamily:'monospace',fontSize:18,fontWeight:700}}>{b.penaltyMitigated||'—'}</div>{b.penaltyMitigated && <Pill label="Resolved" color={C.green}/>}</div>
          </div>
          {(b.frameworks||[]).length>0 && <div style={{marginBottom:16}}><div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing: '0',marginBottom:8}}>Frameworks</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{b.frameworks.map(f=><Pill key={f} label={f} color={color}/>)}</div></div>}
          {(b.agentsData||[]).length>0 && <div><div style={{color:C.slate,fontSize:11,textTransform:'uppercase',letterSpacing: '0',marginBottom:8}}>Agent Inventory ({b.agentsData.length})</div><div style={{maxHeight:200,overflowY:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11}}><thead><tr style={{borderBottom:'1px solid '+C.border}}>{['Agent','Category','Risk','Governed'].map(h=><th key={h} style={{textAlign:'left',padding:'6px 10px',color:C.slate,fontSize:9,textTransform:'uppercase',letterSpacing: '0'}}>{h}</th>)}</tr></thead><tbody>{b.agentsData.slice(0,12).map((a,i)=><tr key={i} style={{borderBottom:'1px solid '+C.border+'44'}}><td style={{padding:'8px 10px',color:C.white}}>{a.name}</td><td style={{padding:'8px 10px',color:C.slate}}>{a.category}</td><td style={{padding:'8px 10px'}}><Pill label={a.risk||'MEDIUM'} color={a.risk==='CRITICAL'?C.red:a.risk==='HIGH'?C.orange:C.slate}/></td><td style={{padding:'8px 10px'}}><Pill label={a.governed?'Yes':'No'} color={a.governed?C.teal:C.red}/></td></tr>)}</tbody></table></div></div>}
        </div>
      )}

      <div style={{background:C.surface,border:'1px solid '+C.goldDim,borderRadius:8,padding:20,display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <div><div style={{color:C.gold,fontSize:12,letterSpacing: '0',textTransform:'uppercase',marginBottom:6}}>Total Regulatory Penalty Exposure Mitigated</div><div style={{color:C.white,fontSize:13}}>HIPAA · CCPA · GLBA · PCI-DSS · ABA · FFIEC · Colorado AI Act · Texas RAIGA</div><div style={{color:C.slate,fontSize:11,marginTop:4}}>4 verticals · 5 GCP services · Auto-refresh 60s</div></div>
        <div style={{color:C.gold,fontFamily:'monospace',fontSize:40, letterSpacing: '0', fontVariantNumeric: 'tabular-nums',fontWeight:700,whiteSpace:'nowrap'}}>$16.85M</div>
      </div>
    </div>
  );
}

// ── AUDIT TRAIL TAB ───────────────────────────────────────────
function AuditTrailView() {
  const [executions, setExecutions] = useState([]);
  const [stats,      setStats]      = useState(null);
  const [filter,     setFilter]     = useState('all');
  const [loading,    setLoading]    = useState(true);
  const [firing,     setFiring]     = useState(false);
  const [lastFired,  setLastFired]  = useState(null);
  const [fireError,  setFireError]  = useState(null);
  const [flashId,    setFlashId]    = useState(null);

  // Demo dispatch state
  const [demoClient, setDemoClient] = useState('bank');
  const [demoAgent,  setDemoAgent]  = useState(DEMO_AGENTS.bank[0].id);

  // Fetch audit data
  const fetchAudit = useCallback(async () => {
    try {
      const [execRes, statsRes] = await Promise.all([
        fetch(API_URL + '/api/telemetry/executions?limit=100'),
        fetch(API_URL + '/api/telemetry/stats')
      ]);
      const execJson  = await execRes.json();
      const statsJson = await statsRes.json();
      if (execJson.data)  setExecutions(execJson.data);
      if (statsJson.data) setStats(statsJson.data);
    } catch(e) {
      // Silently retry
    } finally {
      setLoading(false);
    }
  }, []);

  // Seed demo data on mount if store empty
  useEffect(() => {
    fetch(API_URL + '/api/telemetry/seed', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })
      .then(() => fetchAudit())
      .catch(() => fetchAudit());
    const t = setInterval(fetchAudit, 10000);
    return () => clearInterval(t);
  }, [fetchAudit]);

  // Fire a governed agent from the dashboard
  const fireAgent = async () => {
    setFiring(true);
    setFireError(null);
    try {
      const agents = DEMO_AGENTS[demoClient];
      const agent  = agents.find(a => a.id === demoAgent) || agents[0];
      const res    = await fetch(API_URL + '/api/agents/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientId: demoClient, agentId: agent.id, task: agent.task, payload: { demo: true, firedFrom: 'FoundersDashboard' } })
      });
      const json = await res.json();
      if (json.success) {
        setLastFired(json.data);
        setFlashId(json.data.executionId);
        setTimeout(() => setFlashId(null), 3000);
        setTimeout(() => fetchAudit(), 500);
      } else {
        setFireError(json.message || json.error || 'Dispatch failed');
      }
    } catch(e) {
      setFireError(e.message);
    } finally {
      setFiring(false);
    }
  };

  const filtered = filter === 'all' ? executions : executions.filter(e => (e.clientId||e.source) === filter);

  return (
    <div>

      {/* Stats bar */}
      <div style={{display:'flex', gap:12, marginBottom:24, flexWrap:'wrap'}}>
        <Card label="Total Executions"  value={(stats?.totalExecutions||0).toLocaleString()} sub="All governed" accent={C.gold} />
        <Card label="Avg Gov Score"     value={(stats?.avgGovernanceScore||0)+'%'} sub="Across all clients" accent={scoreColor(stats?.avgGovernanceScore||0)} />
        <Card label="Total Syncs"       value={(stats?.totalSyncs||0).toLocaleString()} sub="AWS↔GCP" accent={C.blue} />
        <Card label="Policy Compliance" value="100%"  sub="All checks passing" accent={C.green} trend={100} />
      </div>

      {/* Per-client stats */}
      {stats?.byClient && Object.keys(stats.byClient).length > 0 && (
        <div style={{display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:12, marginBottom:24}}>
          {Object.entries(stats.byClient).map(([cid, cs]) => (
            <div key={cid} style={{background:C.surface, border:'1px solid '+(CLIENT_COLORS[cid]||C.border)+'44', borderRadius:8, padding:'14px 16px', borderLeft:'3px solid '+(CLIENT_COLORS[cid]||C.gold)}}>
              <div style={{fontSize:16, marginBottom:4}}>{CLIENT_ICONS[cid]||'🏢'}</div>
              <div style={{color:C.white, fontSize:12, fontWeight:600, marginBottom:6, lineHeight:1.3}}>{CLIENT_LABELS[cid]||cid}</div>
              <div style={{display:'flex', justifyContent:'space-between', alignItems:'center'}}>
                <div style={{color:C.gold, fontFamily:'monospace', fontSize:20, fontWeight:700}}>{cs.count}</div>
                <div style={{textAlign:'right'}}>
                  <div style={{color:scoreColor(cs.avgScore), fontSize:13, fontFamily:'monospace', fontWeight:600}}>{cs.avgScore}%</div>
                  <div style={{color:C.slate, fontSize:10}}>avg score</div>
                </div>
              </div>
              {cs.lastExecution && <div style={{color:C.slate, fontSize:10, marginTop:6}}>{fmtAgo(cs.lastExecution)}</div>}
            </div>
          ))}
        </div>
      )}

      {/* Demo dispatch panel */}
      <div style={{background:C.surface2, border:'1px solid '+C.gold+'44', borderRadius:8, padding:20, marginBottom:24}}>
        <div style={{color:C.gold, fontSize:11, letterSpacing: '0', textTransform:'uppercase', marginBottom:14}}>
          ⚡ Live Agent Dispatch — Fire a governed execution
        </div>
        <div style={{display:'flex', gap:12, alignItems:'flex-end', flexWrap:'wrap'}}>
          <div>
            <div style={{color:C.slate, fontSize:10, textTransform:'uppercase', letterSpacing: '0', marginBottom:6}}>Client</div>
            <select
              value={demoClient}
              onChange={e => { setDemoClient(e.target.value); setDemoAgent(DEMO_AGENTS[e.target.value][0].id); }}
              style={{background:C.surface, border:'1px solid '+C.border, color:C.white, borderRadius:6, padding:'8px 12px', fontSize:13, cursor:'pointer', minWidth:220}}
            >
              <option value="bank">🏦 First National Virtual Bank</option>
              <option value="health">🏥 Cascade Regional Health Network</option>
              <option value="retail">🛍️ Summit Retail Group</option>
              <option value="legal">⚖️ Meridian Legal Partners LLP</option>
            </select>
          </div>
          <div>
            <div style={{color:C.slate, fontSize:10, textTransform:'uppercase', letterSpacing: '0', marginBottom:6}}>Agent</div>
            <select
              value={demoAgent}
              onChange={e => setDemoAgent(e.target.value)}
              style={{background:C.surface, border:'1px solid '+C.border, color:C.white, borderRadius:6, padding:'8px 12px', fontSize:13, cursor:'pointer', minWidth:240}}
            >
              {DEMO_AGENTS[demoClient].map(a => (
                <option key={a.id} value={a.id}>{a.name}</option>
              ))}
            </select>
          </div>
          <button
            onClick={fireAgent}
            disabled={firing}
            style={{background:firing?C.border:C.gold+'22', border:'1px solid '+C.gold, color:firing?C.slate:C.gold, borderRadius:6, padding:'8px 24px', fontSize:13, fontWeight:600, cursor:firing?'wait':'pointer', letterSpacing: '0', transition:'all 0.2s'}}
          >
            {firing ? '⏳ Dispatching…' : '▶ FIRE AGENT'}
          </button>
          {lastFired && !firing && (
            <div style={{background:C.green+'11', border:'1px solid '+C.green+'33', borderRadius:6, padding:'8px 14px', fontSize:12}}>
              <span style={{color:C.green, fontWeight:600}}>✓ Governed</span>
              <span style={{color:C.slate, marginLeft:10}}>Score: </span>
              <span style={{color:scoreColor(lastFired.governanceScore), fontFamily:'monospace', fontWeight:700}}>{lastFired.governanceScore}%</span>
              <span style={{color:C.slate, marginLeft:10}}>{fmtMs(lastFired.totalLatencyMs)}</span>
            </div>
          )}
          {fireError && <div style={{color:C.red, fontSize:12}}>⚠ {fireError}</div>}
        </div>
      </div>

      {/* Execution feed */}
      <SecHdr
        title={'Governed Execution Log ('+filtered.length+')'}
        live={true}
        action={
          <div style={{display:'flex', gap:6}}>
            {['all','bank','health','retail','legal'].map(f => (
              <button key={f} onClick={() => setFilter(f)}
                style={{background:filter===f?C.border:'none', border:'1px solid '+C.border, color:filter===f?C.white:C.slate, borderRadius:4, padding:'3px 10px', fontSize:10, cursor:'pointer', textTransform:'uppercase', letterSpacing: '0'}}>
                {f==='all'?'All':(CLIENT_ICONS[f]||'')+ ' '+f}
              </button>
            ))}
          </div>
        }
      />

      {loading && (
        <div style={{textAlign:'center', padding:40, color:C.slate}}>⏳ Loading execution log…</div>
      )}

      {!loading && filtered.length === 0 && (
        <div style={{textAlign:'center', padding:40, color:C.slate}}>
          <div style={{fontSize:24, letterSpacing: '0', fontVariantNumeric: 'tabular-nums', marginBottom:8}}>📋</div>
          <div>No executions yet — fire an agent above</div>
        </div>
      )}

      {!loading && filtered.length > 0 && (
        <div style={{border:'1px solid '+C.border, borderRadius:8, overflow:'hidden'}}>
          <table style={{width:'100%', borderCollapse:'collapse', fontSize:12}}>
            <thead>
              <tr style={{background:C.surface, borderBottom:'1px solid '+C.border}}>
                {['Time','Client','Agent','Task','Gov Score','Latency','Status'].map(h => (
                  <th key={h} style={{textAlign:'left', padding:'10px 14px', color:C.slate, fontSize:10, textTransform:'uppercase', letterSpacing: '0', fontWeight:500}}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((e, i) => {
                const cid   = e.clientId || e.source || 'unknown';
                const color = CLIENT_COLORS[cid] || C.slate;
                const flash = e.executionId === flashId;
                return (
                  <tr key={e.executionId||i} style={{
                    borderBottom:'1px solid '+C.border+'66',
                    background: flash ? C.gold+'11' : i % 2 === 0 ? 'transparent' : C.surface+'66',
                    transition: 'background 0.5s'
                  }}>
                    <td style={{padding:'10px 14px', color:C.slate, whiteSpace:'nowrap'}}>{fmtAgo(e.executedAt||e.storedAt)}</td>
                    <td style={{padding:'10px 14px'}}>
                      <div style={{display:'flex', alignItems:'center', gap:6}}>
                        <span style={{fontSize:14}}>{CLIENT_ICONS[cid]||'🏢'}</span>
                        <span style={{color, fontSize:11, fontWeight:600, textTransform:'uppercase'}}>{cid}</span>
                      </div>
                    </td>
                    <td style={{padding:'10px 14px', color:C.white, maxWidth:180, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap'}}>{e.agentName||e.agentId||'—'}</td>
                    <td style={{padding:'10px 14px', color:C.slate, fontFamily:'monospace', fontSize:11}}>{(e.task||'—').replace(/-/g,' ')}</td>
                    <td style={{padding:'10px 14px'}}>
                      {e.governanceScore ? (
                        <div style={{display:'flex', alignItems:'center', gap:8}}>
                          <div style={{background:C.border, borderRadius:3, height:4, width:40, overflow:'hidden'}}>
                            <div style={{width:e.governanceScore+'%', height:'100%', background:scoreColor(e.governanceScore), borderRadius:3}}/>
                          </div>
                          <span style={{color:scoreColor(e.governanceScore), fontFamily:'monospace', fontWeight:700}}>{e.governanceScore}%</span>
                        </div>
                      ) : <span style={{color:C.slate}}>—</span>}
                    </td>
                    <td style={{padding:'10px 14px', color:C.slate, fontFamily:'monospace'}}>{e.latencyMs||e.totalLatencyMs ? fmtMs(e.latencyMs||e.totalLatencyMs) : '—'}</td>
                    <td style={{padding:'10px 14px'}}>
                      <Pill label={e.complianceStatus||'PASSED'} color={e.complianceStatus==='PASSED'||!e.complianceStatus ? C.green : C.red}/>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <div style={{marginTop:16, color:C.slate, fontSize:11, textAlign:'right'}}>
        Auto-refresh 10s · {executions.length} total executions in store
      </div>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────
export default function FoundersDashboard() {
  const [tab, setTab]           = useState('consolidated');
  const [vm,  setVm]            = useState('actuals');
  const [liveData, setLiveData] = useState(null);
  const [loading,  setLoading]  = useState(true);
  const [meta,     setMeta]     = useState(null);
  const [err,      setErr]      = useState(null);

  const fetchData = useCallback(async () => {
    try {
      const res  = await fetch(API_URL + '/api/live-data');
      const json = await res.json();
      if (json.data) {
        setLiveData(json.data);
        setMeta({ fetchedAt: json.fetchedAt, latencyMs: json.latencyMs });
        setErr(json.errors || null);
      }
    } catch(e) { setErr({ fetch: e.message }); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => {
    fetchData();
    const t = setInterval(fetchData, 60000);
    return () => clearInterval(t);
  }, [fetchData]);

  const ciRev   = liveData?.coreIdentity?.monthly?.revenue || FB.ciRev;
  const cgRev   = liveData?.ciag?.monthly ? liveData.ciag.monthly.retainerRevenue.map((r,i) => r + liveData.ciag.monthly.projectRevenue[i]) : FB.cgRev;
  const ciCost  = liveData?.coreIdentity?.monthly?.costs || FB.ciCost;
  const cgCost  = liveData?.ciag?.monthly?.costs || FB.cgCost;
  const chcRev  = ciRev.map((r,i) => r + cgRev[i]);
  const chcProf = chcRev.map((r,i) => r - ciCost[i] - cgCost[i]);
  const now     = new Date().toLocaleString('en-US', { month:'short', year:'numeric' });

  const TABS  = [
    { id:'consolidated', label:'CHC Consolidated' },
    { id:'coreidentity', label:'CoreIdentity' },
    { id:'ciag',         label:'CIAG' },
    { id:'clients',      label:'Clients (4)' },
    { id:'audit',        label:'⚡ Audit Trail' }
  ];
  const VIEWS = [
    { id:'actuals',     label:'Actuals' },
    { id:'vs-targets',  label:'vs Targets' },
    { id:'trend',       label:'12-Month Trend' }
  ];

  return (
    <div style={{background:C.bg, minHeight:'100vh', color:C.white, fontFamily:'-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'}}>

      {/* Header */}
      <div style={{borderBottom:'1px solid '+C.border, padding:'18px 32px', display:'flex', justifyContent:'space-between', alignItems:'center'}}>
        <div>
          <div style={{fontSize:10, color:C.slate, letterSpacing: '0', textTransform:'uppercase', marginBottom:4}}>Core Holding Corp</div>
          <div style={{fontSize:20, fontWeight:600}}>Founders Dashboard</div>
        </div>
        <div style={{display:'flex', gap:24, alignItems:'center'}}>
          <div style={{textAlign:'right'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0'}}>CHC Revenue</div><div style={{color:C.gold,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{fmtK(last(chcRev))}</div></div>
          <div style={{textAlign:'right'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0'}}>Net Profit</div><div style={{color:C.green,fontFamily:'monospace',fontSize:22,fontWeight:700}}>{fmtK(last(chcProf))}</div></div>
          <div style={{textAlign:'right'}}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing: '0'}}>Mitigated</div><div style={{color:C.teal,fontFamily:'monospace',fontSize:22,fontWeight:700}}>$16.85M</div></div>
          <div style={{display:'flex', flexDirection:'column', gap:4, alignItems:'flex-end'}}>
            <div style={{background:C.surface,border:'1px solid '+C.border,borderRadius:6,padding:'6px 14px',color:C.slate,fontSize:12}}>{now}</div>
            <button onClick={fetchData} style={{background:'none',border:'1px solid '+C.border,borderRadius:4,color:C.slate,fontSize:10,padding:'3px 10px',cursor:'pointer',letterSpacing: '0'}}>↻ REFRESH</button>
          </div>
        </div>
      </div>

      {/* Status bar */}
      <div style={{background:C.surface, borderBottom:'1px solid '+C.border, padding:'8px 32px', display:'flex', justifyContent:'space-between', fontSize:11}}>
        <span style={{color:loading?C.slate:err?C.orange:C.green}}>
          {loading ? '⏳ Loading 5 GCP sources…' : err ? '⚠ Partial data — some sources unavailable' : '● Live — 5 GCP services healthy'}
        </span>
        {meta && <span style={{color:C.slate}}>Updated {new Date(meta.fetchedAt).toLocaleTimeString()} · {meta.latencyMs}ms · Auto-refresh 60s</span>}
      </div>

      {/* Tab bar */}
      <div style={{borderBottom:'1px solid '+C.border, padding:'0 32px', display:'flex'}}>
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)}
            style={{background:'none', border:'none', cursor:'pointer', padding:'14px 20px', fontSize:13, fontWeight:500,
              color: tab===t.id ? (t.id==='audit' ? C.gold : C.gold) : C.slate,
              borderBottom: tab===t.id ? '2px solid '+C.gold : '2px solid transparent',
              transition:'color 0.15s'
            }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* View mode toggle (hidden for audit tab) */}
      {tab !== 'audit' && tab !== 'clients' && (
        <div style={{padding:'16px 32px', display:'flex', justifyContent:'flex-end', borderBottom:'1px solid '+C.border+'55'}}>
          <div style={{display:'flex', background:C.surface, border:'1px solid '+C.border, borderRadius:6, overflow:'hidden'}}>
            {VIEWS.map(v => (
              <button key={v.id} onClick={() => setVm(v.id)}
                style={{background:vm===v.id?C.border:'none', border:'none', cursor:'pointer', padding:'6px 16px', fontSize:12, color:vm===v.id?C.white:C.slate}}>
                {v.label}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Tab content */}
      <div style={{padding:'28px 32px'}}>
        {tab==='consolidated' && <ConsolidatedView vm={vm} d={liveData}/>}
        {tab==='coreidentity' && <CoreIdentityView vm={vm} d={liveData}/>}
        {tab==='ciag'         && <CIAGView         vm={vm} d={liveData}/>}
        {tab==='clients'      && <ClientPortfolioView d={liveData}/>}
        {tab==='audit'        && <AuditTrailView/>}
      </div>
    </div>
  );
}
