// LoginPage.jsx — CoreIdentity Governance Portal
// Auto-generated by Script 29 — DO NOT hand edit

import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';

const S = {
  root: {
    minHeight: '100vh',
    background: '#070c18',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'DM Sans','Segoe UI',sans-serif",
    padding: '24px 16px',
  },
  card: {
    width: '100%',
    maxWidth: 420,
    background: '#0d1526',
    border: '1px solid #1e2d4a',
    borderRadius: 16,
    padding: '40px 36px',
    boxShadow: '0 24px 64px rgba(0,0,0,0.6)',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 32,
  },
  logoMark: {
    width: 36,
    height: 36,
    background: 'linear-gradient(135deg, #2563eb, #0ea5e9)',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    fontWeight: 800,
    color: '#fff',
    flexShrink: 0,
  },
  logoName: { fontSize: 17, fontWeight: 700, color: '#e2e8f0', letterSpacing: '-0.3px' },
  logoSub:  { fontSize: 11, color: '#475569', letterSpacing: '0.08em', textTransform: 'uppercase' },
  h1:    { fontSize: 22, fontWeight: 700, color: '#e2e8f0', marginBottom: 4, letterSpacing: '-0.3px' },
  sub:   { fontSize: 14, color: '#64748b', marginBottom: 28 },
  label: {
    display: 'block',
    fontSize: 11,
    fontWeight: 600,
    color: '#94a3b8',
    marginBottom: 6,
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
  },
  input: {
    width: '100%',
    background: '#080f1e',
    border: '1px solid #1e2d4a',
    borderRadius: 8,
    padding: '11px 14px',
    fontSize: 14,
    color: '#e2e8f0',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: 16,
    transition: 'border-color 0.15s',
  },
  inputActive: { borderColor: '#2563eb' },
  error: {
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.25)',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    color: '#f87171',
    marginBottom: 16,
  },
  btn: {
    width: '100%',
    background: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
    border: 'none',
    borderRadius: 8,
    padding: '12px',
    fontSize: 15,
    fontWeight: 600,
    color: '#fff',
    cursor: 'pointer',
    marginTop: 4,
    letterSpacing: '-0.1px',
  },
  btnDisabled: { opacity: 0.55, cursor: 'not-allowed' },
  footer: { marginTop: 28, textAlign: 'center', fontSize: 12, color: '#1e293b' },
};

export default function LoginPage() {
  const { login, loading } = useAuth();
  const [email,    setEmail]    = useState('');
  const [password, setPassword] = useState('');
  const [error,    setError]    = useState('');
  const [focus,    setFocus]    = useState('');

  const submit = async (e) => {
    e.preventDefault();
    setError('');
    if (!email.trim() || !password.trim()) {
      setError('Email and password are required.');
      return;
    }
    const res = await login(email.trim(), password);
    if (!res?.success) setError(res?.error || 'Login failed — please try again.');
  };

  const inp = (field) => ({
    ...S.input,
    ...(focus === field ? S.inputActive : {}),
  });

  return (
    <div style={S.root}>
      <div style={S.card}>
        <div style={S.logoRow}>
          <div style={S.logoMark}>C</div>
          <div>
            <div style={S.logoName}>CoreIdentity</div>
            <div style={S.logoSub}>Core Holding Corp</div>
          </div>
        </div>

        <div style={S.h1}>Welcome back</div>
        <div style={S.sub}>Sign in to the governance portal</div>

        {error && <div style={S.error}>{error}</div>}

        <form onSubmit={submit} noValidate>
          <label style={S.label}>Email</label>
          <input
            type="email"
            value={email}
            onChange={e => setEmail(e.target.value)}
            onFocus={() => setFocus('email')}
            onBlur={() => setFocus('')}
            style={inp('email')}
            placeholder="you@coreholdingcorp.com"
            autoComplete="email"
            autoFocus
          />

          <label style={S.label}>Password</label>
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            onFocus={() => setFocus('pass')}
            onBlur={() => setFocus('')}
            style={inp('pass')}
            placeholder="••••••••"
            autoComplete="current-password"
          />

          <button
            type="submit"
            disabled={loading}
            style={{ ...S.btn, ...(loading ? S.btnDisabled : {}) }}
          >
            {loading ? 'Signing in…' : 'Sign in'}
          </button>
        </form>

        <div style={S.footer}>CoreIdentity Governance Portal · Core Holding Corp</div>
      </div>
    </div>
  );
}
