// MarketingPage.jsx — Mobile-responsive
// Auto-generated by Script 25-F — DO NOT hand edit
import { useState, useEffect } from 'react';
import { C, F, useWindowWidth } from '../chc-design.js';

const VERTICALS = [
  { icon:'🏥', name:'Healthcare',         penalty:'$8.2M',  agents:18, before:58, after:94, color:C.green  },
  { icon:'🏦', name:'Financial Services', penalty:'$4.75M', agents:23, before:65, after:94, color:C.blue   },
  { icon:'🛍️', name:'Retail',            penalty:'$2.1M',  agents:14, before:71, after:89, color:C.orange },
  { icon:'⚖️', name:'Legal',             penalty:'$1.8M',  agents:11, before:74, after:92, color:C.purple },
];
const STATS = [
  { v:'66',      l:'Ungoverned Agents',   s:'Live right now',              c:C.red    },
  { v:'$16.85M', l:'Exposure Mitigated',  s:'Across 4 client verticals',   c:C.gold   },
  { v:'18',      l:'Active AI Laws',      s:'US states + federal',         c:C.orange },
  { v:'94%',     l:'Avg Governance Score',s:'Post-CoreIdentity deployment', c:C.green  },
];
const LAWS = [
  { law:'HIPAA',           max:'$1.9M/yr',   who:'HHS OCR',       sector:'Healthcare' },
  { law:'GLBA',            max:'$100K/day',  who:'FTC / OCC',     sector:'Financial'  },
  { law:'CCPA / CPPA',     max:'Unlimited',  who:'CA CPPA',       sector:'All'        },
  { law:'ABA Rule 1.6',    max:'Disbarment', who:'State Bar',     sector:'Legal'      },
  { law:'PCI-DSS',         max:'$100K/mo',   who:'Card Networks', sector:'Retail'     },
  { law:'Colorado AI Act', max:'TBD',        who:'Colorado AG',   sector:'All'        },
  { law:'Texas RAIGA',     max:'TBD',        who:'Texas AG',      sector:'All'        },
  { law:'EU AI Act',       max:'€30M/7%',   who:'EU AI Office',  sector:'Global'     },
];
const PLANES = [
  { name:'Sentinel OS',    role:'Policy Gate',          desc:'Rate limit · permissions · data access · output safety. Blocks non-compliant executions before they run.',     color:C.red  },
  { name:'Nexus OS',       role:'Routing + Resilience', desc:'Circuit breaker routes to correct GCP client service. Handles retries, timeouts, fallback — zero data loss.', color:C.blue },
  { name:'AGO Modules',    role:'20 Vertical Handlers', desc:'HIPAA · GLBA · ABA · CCPA. Purpose-built compliance logic per industry vertical.',                             color:C.teal },
  { name:'SmartNation AI', role:'Continuous Monitor',   desc:'108 governance agents running continuously. Flags ungoverned drift, generates compliance telemetry every 30s.',color:C.gold },
];

export default function MarketingPage() {
  const w = useWindowWidth();
  const m = w < 768;
  const pad = m ? '0 16px' : '0 40px';
  const [count, setCount] = useState(412089);

  useEffect(() => {
    const t = setInterval(() => setCount(n => n + Math.floor(Math.random()*8)+2), 1200);
    return () => clearInterval(t);
  }, []);

  return (
    <div style={{ background:C.bg, color:C.white, fontFamily:F.body, overflowX:'hidden' }}>

      {/* Live ticker */}
      <div style={{ background:C.gold+'18', borderBottom:'1px solid '+C.gold+'33',
        padding:'8px 16px', display:'flex', flexDirection: m ? 'column' : 'row',
        justifyContent:'space-between', gap:m?4:0, fontSize:11 }}>
        <span style={{ color:C.gold, letterSpacing:'0.1em', textTransform:'uppercase', fontWeight:600 }}>
          ● LIVE — CoreIdentity Governance Platform
        </span>
        <div style={{ display:'flex', gap: m?16:32, color:C.slate, flexWrap:'wrap' }}>
          <span>Executions: <span style={{ color:C.gold, fontFamily:F.mono, fontWeight:700 }}>{count.toLocaleString()}</span></span>
          <span>Services: <span style={{ color:C.green }}>all healthy</span></span>
          <span>Score: <span style={{ color:C.green, fontFamily:F.mono }}>94%</span></span>
        </div>
      </div>

      {/* Hero */}
      <section style={{ padding: m ? '60px 16px 48px' : '100px 40px 80px',
        maxWidth:1200, margin:'0 auto' }}>
        <div style={{ display:'grid',
          gridTemplateColumns: m ? '1fr' : '1fr 1fr',
          gap: m ? 40 : 80, alignItems:'center' }}>
          <div>
            <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
              textTransform:'uppercase', marginBottom:20, display:'flex', alignItems:'center', gap:8 }}>
              <div style={{ width:24, height:1, background:C.gold }}/> AI Governance Infrastructure
            </div>
            <h1 style={{ fontFamily:F.display,
              fontSize: m ? 52 : 76,
              lineHeight:0.95, color:C.white, margin:'0 0 24px', letterSpacing:'0.02em' }}>
              YOUR AI<br/>AGENTS<br/><span style={{ color:C.red }}>HAVE NO</span><br/>OVERSIGHT.
            </h1>
            <p style={{ fontSize:16, color:C.slate, lineHeight:1.8, margin:'0 0 32px',
              fontWeight:300 }}>
              66 ungoverned agents making clinical decisions, credit approvals, and legal reviews —
              with <strong style={{ color:C.white }}>$16.85M</strong> in regulatory exposure and zero audit trail.
            </p>
            <div style={{ display:'flex', gap:12, flexWrap:'wrap' }}>
              <a href="#/demo" style={{ background:C.gold, color:C.bg, textDecoration:'none',
                padding:'14px 24px', borderRadius:8, fontSize:15, fontWeight:700, letterSpacing:'0.04em' }}>
                See Live Demo
              </a>
              <a href="#/onboard" style={{ background:'none', color:C.gold, textDecoration:'none',
                padding:'14px 24px', borderRadius:8, fontSize:15, fontWeight:500,
                border:'1px solid '+C.gold+'44' }}>
                Free Assessment →
              </a>
            </div>
          </div>

          {/* Exposure card */}
          <div style={{ background:C.surface, border:'1px solid '+C.border,
            borderRadius:12, padding: m ? 24 : 36, position:'relative', overflow:'hidden' }}>
            <div style={{ position:'absolute', top:0, left:0, right:0, height:3,
              background:`linear-gradient(90deg,${C.red},${C.gold})` }}/>
            <div style={{ color:C.slate, fontSize:10, letterSpacing:'0.15em',
              textTransform:'uppercase', marginBottom:16 }}>Unmitigated Regulatory Exposure</div>
            <div style={{ fontFamily:F.display, fontSize: m ? 44 : 60,
              color:C.red, letterSpacing:'0.04em', lineHeight:1, marginBottom:8 }}>$16.85M</div>
            <div style={{ color:C.slate, fontSize:13, marginBottom:20 }}>
              Across 4 industries · 66 ungoverned AI agents
            </div>
            {VERTICALS.map((v,i) => (
              <div key={i} style={{ display:'flex', justifyContent:'space-between',
                alignItems:'center', padding:'10px 0',
                borderTop: i>0 ? '1px solid '+C.border : 'none' }}>
                <div style={{ display:'flex', alignItems:'center', gap:8 }}>
                  <span style={{ fontSize:18 }}>{v.icon}</span>
                  <div>
                    <div style={{ color:C.white, fontSize:13, fontWeight:600 }}>{v.name}</div>
                    <div style={{ color:C.slate, fontSize:11 }}>{v.agents} agents</div>
                  </div>
                </div>
                <div style={{ textAlign:'right' }}>
                  <div style={{ color:v.color, fontFamily:F.mono, fontSize:13, fontWeight:700 }}>
                    {v.penalty}
                  </div>
                  <div style={{ color:C.slate, fontSize:11 }}>exposure</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section style={{ background:C.surface, borderTop:'1px solid '+C.border,
        borderBottom:'1px solid '+C.border, padding: m ? '32px 16px' : '40px' }}>
        <div style={{ maxWidth:1200, margin:'0 auto',
          display:'grid', gridTemplateColumns: m ? '1fr 1fr' : 'repeat(4,1fr)', gap:m?20:32 }}>
          {STATS.map((s,i) => (
            <div key={i} style={{ textAlign:'center' }}>
              <div style={{ fontFamily:F.display, fontSize: m ? 32 : 44,
                color:s.c, letterSpacing:'0.04em', lineHeight:1 }}>{s.v}</div>
              <div style={{ color:C.white, fontSize: m ? 12 : 14,
                fontWeight:600, marginTop:8 }}>{s.l}</div>
              <div style={{ color:C.slate, fontSize:11, marginTop:4 }}>{s.s}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Regulatory landscape */}
      <section style={{ padding: m ? '48px 16px' : '80px 40px', maxWidth:1200, margin:'0 auto' }}>
        <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
          textTransform:'uppercase', marginBottom:8 }}>Regulatory Landscape</div>
        <h2 style={{ fontFamily:F.display, fontSize: m ? 36 : 52,
          color:C.white, margin:'0 0 32px', letterSpacing:'0.04em' }}>
          18 LAWS. ZERO MARGIN FOR ERROR.
        </h2>
        <div style={{ display:'grid',
          gridTemplateColumns: m ? '1fr 1fr' : 'repeat(4,1fr)',
          gap:12 }}>
          {LAWS.map((l,i) => (
            <div key={i} style={{ background:C.surface, border:'1px solid '+C.border,
              borderRadius:8, padding: m ? '14px 12px' : '20px 16px' }}>
              <div style={{ fontFamily:F.display, fontSize: m ? 16 : 20,
                color:C.gold, letterSpacing:'0.06em', marginBottom:6 }}>{l.law}</div>
              <div style={{ color:C.red, fontSize: m ? 12 : 13,
                fontWeight:600, marginBottom:4 }}>Max: {l.max}</div>
              <div style={{ color:C.slate, fontSize:11 }}>{l.who} · {l.sector}</div>
            </div>
          ))}
        </div>
      </section>

      {/* 4-Plane platform */}
      <section style={{ padding: m ? '48px 16px' : '80px 40px',
        background:C.surface, borderTop:'1px solid '+C.border,
        borderBottom:'1px solid '+C.border }}>
        <div style={{ maxWidth:1200, margin:'0 auto' }}>
          <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
            textTransform:'uppercase', marginBottom:8 }}>The Platform</div>
          <h2 style={{ fontFamily:F.display, fontSize: m ? 36 : 52,
            color:C.white, margin:'0 0 32px', letterSpacing:'0.04em' }}>
            4-PLANE GOVERNANCE ARCHITECTURE
          </h2>
          <div style={{ display:'grid',
            gridTemplateColumns: m ? '1fr' : 'repeat(2,1fr)', gap:16 }}>
            {PLANES.map((p,i) => (
              <div key={i} style={{ background:C.bg, border:'1px solid '+p.color+'44',
                borderLeft:'3px solid '+p.color, borderRadius:8, padding:'20px 20px' }}>
                <div style={{ display:'flex', justifyContent:'space-between',
                  alignItems:'flex-start', marginBottom:8 }}>
                  <span style={{ color:p.color, fontFamily:F.display,
                    fontSize:18, letterSpacing:'0.06em' }}>{p.name}</span>
                  <span style={{ color:C.slate, fontSize:10, background:C.surface,
                    padding:'2px 8px', borderRadius:4 }}>{p.role}</span>
                </div>
                <div style={{ color:C.slate, fontSize:13, lineHeight:1.6 }}>{p.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Client portfolio */}
      <section style={{ padding: m ? '48px 16px' : '80px 40px', maxWidth:1200, margin:'0 auto' }}>
        <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
          textTransform:'uppercase', marginBottom:8 }}>Client Portfolio — Live</div>
        <h2 style={{ fontFamily:F.display, fontSize: m ? 36 : 52,
          color:C.white, margin:'0 0 32px', letterSpacing:'0.04em' }}>
          PRODUCTION. NOT PILOTS.
        </h2>
        <div style={{ display:'grid',
          gridTemplateColumns: m ? '1fr' : 'repeat(2,1fr)', gap:16 }}>
          {VERTICALS.map((v,i) => (
            <div key={i} style={{ background:C.surface, border:'1px solid '+v.color+'44',
              borderRadius:12, padding: m ? 20 : 28, borderLeft:'4px solid '+v.color }}>
              <div style={{ display:'flex', justifyContent:'space-between',
                alignItems:'flex-start', marginBottom:16 }}>
                <div style={{ display:'flex', alignItems:'center', gap:10 }}>
                  <span style={{ fontSize:28 }}>{v.icon}</span>
                  <div>
                    <div style={{ color:C.white, fontWeight:600, fontSize:16 }}>{v.name}</div>
                    <div style={{ color:C.slate, fontSize:12 }}>{v.agents} agents</div>
                  </div>
                </div>
                <div style={{ textAlign:'right' }}>
                  <div style={{ color:C.green, fontSize:11, fontWeight:600,
                    letterSpacing:'0.08em' }}>GOVERNED</div>
                  <div style={{ color:v.color, fontFamily:F.mono,
                    fontSize:16, fontWeight:700 }}>{v.penalty}</div>
                  <div style={{ color:C.slate, fontSize:10 }}>mitigated</div>
                </div>
              </div>
              <div style={{ display:'flex', alignItems:'center', gap:12 }}>
                <div style={{ flex:1, height:6, background:C.border, borderRadius:3, overflow:'hidden' }}>
                  <div style={{ height:'100%', width:'100%', background:C.border, borderRadius:3, position:'relative' }}>
                    <div style={{ position:'absolute', left:0, top:0, bottom:0,
                      width:v.before+'%', background:C.red, borderRadius:3 }}/>
                  </div>
                </div>
                <div style={{ color:C.slate, fontSize:12, whiteSpace:'nowrap' }}>
                  {v.before}% <span style={{ color:C.slate }}>→</span>{' '}
                  <span style={{ color:C.green, fontWeight:700 }}>{v.after}%</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{ background:C.surface, borderTop:'1px solid '+C.border,
        padding: m ? '48px 16px' : '80px 40px', textAlign:'center' }}>
        <h2 style={{ fontFamily:F.display, fontSize: m ? 40 : 64,
          color:C.white, margin:'0 0 12px', letterSpacing:'0.04em' }}>
          READY TO GOVERN YOUR AI?
        </h2>
        <p style={{ color:C.slate, fontSize:16, fontWeight:300,
          maxWidth:500, margin:'0 auto 36px', lineHeight:1.7 }}>
          From assessment to production in under 60 seconds.
          No credit card. No professional services.
        </p>
        <div style={{ display:'flex', gap:12, justifyContent:'center', flexWrap:'wrap' }}>
          <a href="#/demo" style={{ background:C.gold, color:C.bg, textDecoration:'none',
            padding:'16px 32px', borderRadius:8, fontSize:16, fontWeight:700,
            letterSpacing:'0.04em' }}>See Live Demo</a>
          <a href="#/onboard" style={{ background:'none', color:C.gold, textDecoration:'none',
            padding:'16px 32px', borderRadius:8, fontSize:16, fontWeight:500,
            border:'1px solid '+C.gold+'44' }}>Free Assessment →</a>
        </div>
      </section>

      {/* Footer */}
      <footer style={{ background:C.bg, borderTop:'1px solid '+C.border,
        padding: m ? '24px 16px' : '40px', textAlign:'center' }}>
        <div style={{ fontFamily:F.display, fontSize:18, color:C.gold,
          letterSpacing:'0.1em', marginBottom:16 }}>COREIDENTITY · CORE HOLDING CORP</div>
        <div style={{ display:'flex', gap:24, justifyContent:'center',
          flexWrap:'wrap', marginBottom:16 }}>
          {[['#/demo','Demo'],['#/pricing','Pricing'],['#/docs','API'],
            ['#/investor','Investors'],['#/dashboard','Dashboard']].map(([h,l]) => (
            <a key={h} href={h} style={{ color:C.slate, textDecoration:'none', fontSize:12 }}>{l}</a>
          ))}
        </div>
        <div style={{ color:C.slate, fontSize:11 }}>
          © 2026 Core Holding Corp · AI Governance Infrastructure
        </div>
      </footer>
    </div>
  );
}
