// PricingPage.jsx — Mobile-responsive
// Auto-generated by Script 25-F — DO NOT hand edit
import { useState } from 'react';
import { C, F, useWindowWidth } from '../chc-design.js';

const TIERS = [
  {
    key:'Starter', price:4500, agents:25, color:C.blue, popular:false,
    features:['Up to 25 AI agents','3 compliance frameworks','CCPA + Colorado AI Act + 1 vertical','Email support (48h SLA)','Governance score dashboard','API access — 10K calls/mo','Audit trail (90 days)'],
    missing:['Dedicated CSM','Custom frameworks','CIAG advisory hours','Priority support'],
  },
  {
    key:'Professional', price:12500, agents:100, color:C.gold, popular:true,
    features:['Up to 100 AI agents','All compliance frameworks','HIPAA · GLBA · ABA · CCPA · PCI-DSS…','Dedicated Customer Success Manager','Governance score dashboard','Monthly compliance reports','Audit trail (1 year)','API access — 100K calls/mo','4h CIAG advisory hours/month','Custom framework mapping','Priority support (4h SLA)','Bidirectional telemetry'],
    missing:['Unlimited agents','Full CIAG retainer','Source code escrow'],
  },
  {
    key:'Enterprise', price:35000, agents:null, color:C.purple, popular:false,
    features:['Unlimited AI agents','All frameworks + custom','Full CIAG advisory retainer','Executive governance reports','Real-time telemetry + alerting','API access — unlimited','Custom SLA (99.9% uptime)','Dedicated implementation team','Quarterly board-level reports','Regulatory response playbooks','Multi-region deployment','Source code escrow available'],
    missing:[],
  },
];

const PROFILES = {
  'Healthcare':         { perAgent:85000, tier:'Professional' },
  'Financial Services': { perAgent:45000, tier:'Enterprise'   },
  'Retail':             { perAgent:32000, tier:'Starter'      },
  'Legal':              { perAgent:38000, tier:'Professional' },
  'Insurance':          { perAgent:55000, tier:'Professional' },
  'Technology':         { perAgent:28000, tier:'Starter'      },
};

const FAQ = [
  { q:'How fast is deployment?', a:'CoreIdentity deploys to production in under 60 seconds via our CI/CD pipeline. Your agents are governed from the first execution.' },
  { q:'Can I use custom compliance frameworks?', a:'Professional and Enterprise tiers support custom framework definitions. Our CIAG team can map any regulatory requirement.' },
  { q:'What happens when an agent fails a policy check?', a:'The execution is blocked before it reaches the agent. You receive a detailed failure report with the specific policy that blocked it and recommended remediation.' },
  { q:'Is there a free trial?', a:'We offer a 30-day pilot at no cost for qualified organizations. Request access via the assessment wizard.' },
  { q:'How is the governance score calculated?', a:'Score = (policy_checks_passed / total_checks) × compliance_multiplier. Multiplier accounts for regulatory framework coverage and audit trail completeness.' },
  { q:'Does Starter include CIAG advisory?', a:'Starter does not include advisory hours. CIAG retainer starts at Professional (4h/mo). Standalone advisory assessments are available from $15K.' },
];

export default function PricingPage() {
  const w = useWindowWidth();
  const m = w < 768;
  const [annual, setAnnual] = useState(false);
  const [faqOpen, setFaqOpen] = useState(null);
  const [industry, setIndustry] = useState('Healthcare');
  const [agents, setAgents] = useState(18);

  const disc = annual ? 0.9 : 1;
  const p = PROFILES[industry];
  const exp = Math.round(agents * p.perAgent * 0.7);
  const tierPrice = p.tier === 'Enterprise' ? 35000 : p.tier === 'Professional' ? 12500 : 4500;
  const roi = Math.round((exp - tierPrice * 12) / (tierPrice * 12) * 100);

  return (
    <div style={{ background:C.bg, minHeight:'100vh', color:C.white,
      fontFamily:F.body, overflowX:'hidden' }}>
      <div style={{ maxWidth:1100, margin:'0 auto', padding: m ? '48px 16px' : '80px 40px' }}>

        {/* Header */}
        <div style={{ textAlign:'center', marginBottom: m ? 40 : 60 }}>
          <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
            textTransform:'uppercase', marginBottom:12 }}>Transparent Pricing</div>
          <h1 style={{ fontFamily:F.display, fontSize: m ? 44 : 72,
            color:C.white, margin:'0 0 16px', letterSpacing:'0.04em' }}>
            GOVERNANCE AT SCALE
          </h1>
          <p style={{ color:C.slate, fontSize:16, fontWeight:300,
            maxWidth:500, margin:'0 auto 28px', lineHeight:1.7 }}>
            From 25 agents to unlimited. Every tier includes full audit trail,
            real-time governance scores, and live regulatory enforcement.
          </p>
          {/* Billing toggle */}
          <div style={{ display:'inline-flex', alignItems:'center', gap:12,
            background:C.surface, border:'1px solid '+C.border,
            borderRadius:8, padding:'8px 16px' }}>
            <span style={{ color: !annual ? C.white : C.slate, fontSize:14, fontWeight:500 }}>Monthly</span>
            <div onClick={() => setAnnual(a => !a)} style={{
              width:44, height:24, background: annual ? C.gold : C.border,
              borderRadius:12, cursor:'pointer', position:'relative', transition:'background 0.2s',
            }}>
              <div style={{
                position:'absolute', top:3, left: annual ? 23 : 3,
                width:18, height:18, background:'white', borderRadius:'50%',
                transition:'left 0.2s',
              }}/>
            </div>
            <span style={{ color: annual ? C.white : C.slate, fontSize:14, fontWeight:500 }}>
              Annual <span style={{ color:C.green, fontSize:11 }}>-10%</span>
            </span>
          </div>
        </div>

        {/* Tier cards — SINGLE COLUMN on mobile */}
        <div style={{ display:'grid',
          gridTemplateColumns: m ? '1fr' : 'repeat(3,1fr)',
          gap: m ? 16 : 20, marginBottom: m ? 48 : 80 }}>
          {TIERS.map((tier) => (
            <div key={tier.key} style={{
              background: tier.popular ? C.gold+'0d' : C.surface,
              border: '2px solid ' + (tier.popular ? C.gold : C.border),
              borderRadius:12, padding: m ? '24px 20px' : '32px 28px',
              position:'relative',
            }}>
              {tier.popular && (
                <div style={{ position:'absolute', top:-14, left:'50%',
                  transform:'translateX(-50%)', background:C.gold, color:C.bg,
                  fontSize:10, fontWeight:700, padding:'4px 14px',
                  borderRadius:20, letterSpacing:'0.1em', whiteSpace:'nowrap' }}>
                  MOST POPULAR
                </div>
              )}
              <div style={{ marginBottom:20 }}>
                <div style={{ fontFamily:F.display, fontSize:28,
                  color:tier.popular ? C.gold : C.white, letterSpacing:'0.06em' }}>
                  {tier.key.toUpperCase()}
                </div>
                <div style={{ color:C.slate, fontSize:13, marginTop:2 }}>
                  {tier.agents ? `Up to ${tier.agents} agents` : 'Unlimited agents'}
                </div>
              </div>
              <div style={{ marginBottom:24 }}>
                <span style={{ fontFamily:F.mono, letterSpacing:'0', fontSize: m ? 32 : 36,
                  color: tier.popular ? C.gold : C.white, fontWeight:700 }}>
                  ${Math.round(tier.price * disc / 1000 * 10) / 10}K
                </span>
                <span style={{ color:C.slate, fontSize:14 }}>/month</span>
                {annual && <div style={{ color:C.green, fontSize:11, marginTop:4 }}>
                  ${Math.round(tier.price * disc * 12 / 1000)}K/year — save ${Math.round(tier.price * 0.1 * 12 / 1000)}K
                </div>}
              </div>
              {tier.key !== 'Enterprise' ? (
                <a href="#/onboard" style={{
                  display:'block', textAlign:'center',
                  background: tier.popular ? C.gold : C.border,
                  color: tier.popular ? C.bg : C.white,
                  textDecoration:'none', padding:'12px', borderRadius:8,
                  fontSize:14, fontWeight:700, letterSpacing:'0.04em', marginBottom:24,
                }}>Start 30-Day Trial</a>
              ) : (
                <a href="mailto:sales@coreholdingcorp.com" style={{
                  display:'block', textAlign:'center',
                  background:'none', color:C.purple,
                  textDecoration:'none', padding:'12px', borderRadius:8,
                  fontSize:14, fontWeight:600, border:'2px solid '+C.purple,
                  marginBottom:24,
                }}>Contact Sales</a>
              )}
              <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                {tier.features.map((f,i) => (
                  <div key={i} style={{ display:'flex', gap:8, alignItems:'flex-start' }}>
                    <span style={{ color:C.green, fontSize:13, flexShrink:0 }}>✓</span>
                    <span style={{ color:C.slate, fontSize:13, lineHeight:1.4 }}>{f}</span>
                  </div>
                ))}
                {tier.missing.map((f,i) => (
                  <div key={i} style={{ display:'flex', gap:8, alignItems:'flex-start', opacity:0.4 }}>
                    <span style={{ color:C.slate, fontSize:13, flexShrink:0 }}>✗</span>
                    <span style={{ color:C.slate, fontSize:13, lineHeight:1.4 }}>{f}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* ROI Calculator */}
        <div style={{ background:C.surface, border:'1px solid '+C.border,
          borderRadius:12, padding: m ? '24px 20px' : '40px', marginBottom: m ? 48 : 80 }}>
          <div style={{ color:C.gold, fontSize:11, letterSpacing:'0.2em',
            textTransform:'uppercase', marginBottom:8 }}>ROI Calculator</div>
          <h2 style={{ fontFamily:F.display, fontSize: m ? 32 : 44,
            color:C.white, margin:'0 0 24px', letterSpacing:'0.04em' }}>
            CALCULATE YOUR RETURN
          </h2>
          <div style={{ display:'grid',
            gridTemplateColumns: m ? '1fr' : '1fr 1fr', gap:20, marginBottom:28 }}>
            <div>
              <label style={{ color:C.slate, fontSize:11, textTransform:'uppercase',
                letterSpacing:'0.1em', display:'block', marginBottom:8 }}>Industry</label>
              <select value={industry} onChange={e => setIndustry(e.target.value)}
                style={{ width:'100%', background:C.bg, border:'1px solid '+C.border,
                  color:C.white, borderRadius:8, padding:'12px 16px', fontSize:14,
                  cursor:'pointer' }}>
                {Object.keys(PROFILES).map(k => <option key={k} value={k}>{k}</option>)}
              </select>
            </div>
            <div>
              <label style={{ color:C.slate, fontSize:11, textTransform:'uppercase',
                letterSpacing:'0.1em', display:'block', marginBottom:8 }}>
                AI Agents: <span style={{ color:C.gold, fontFamily:F.mono }}>{agents}</span>
              </label>
              <input type="range" min={1} max={150} value={agents}
                onChange={e => setAgents(Number(e.target.value))}
                style={{ width:'100%', accentColor:C.gold, marginTop:8 }}/>
            </div>
          </div>
          <div style={{ display:'grid',
            gridTemplateColumns: m ? '1fr' : 'repeat(3,1fr)', gap:16 }}>
            {[
              { label:'Est. Annual Exposure', value:'$'+(exp/1e6).toFixed(1)+'M', color:C.red   },
              { label:`${p.tier} Annual Cost`,  value:'$'+(tierPrice*disc*12/1000).toFixed(0)+'K', color:C.gold  },
              { label:'Annual ROI',            value:roi+'%',                    color:C.green },
            ].map((s,i) => (
              <div key={i} style={{ background:C.bg, border:'1px solid '+s.color+'44',
                borderRadius:8, padding:'20px 16px', borderTop:'3px solid '+s.color }}>
                <div style={{ color:C.slate, fontSize:11, textTransform:'uppercase',
                  letterSpacing:'0.08em', marginBottom:8 }}>{s.label}</div>
                <div style={{ fontFamily:F.display, fontSize: m ? 28 : 36,
                  color:s.color, letterSpacing:'0.04em' }}>{s.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div>
          <h2 style={{ fontFamily:F.display, fontSize: m ? 32 : 44,
            color:C.white, margin:'0 0 24px', letterSpacing:'0.04em' }}>FAQ</h2>
          {FAQ.map((item,i) => (
            <div key={i} style={{ borderBottom:'1px solid '+C.border }}>
              <div onClick={() => setFaqOpen(faqOpen === i ? null : i)}
                style={{ display:'flex', justifyContent:'space-between', alignItems:'center',
                  padding:'16px 0', cursor:'pointer' }}>
                <span style={{ color:C.white, fontSize:15, fontWeight:500,
                  paddingRight:16 }}>{item.q}</span>
                <span style={{ color:C.gold, fontSize:18, flexShrink:0 }}>
                  {faqOpen === i ? '−' : '+'}
                </span>
              </div>
              {faqOpen === i && (
                <div style={{ color:C.slate, fontSize:14, lineHeight:1.7,
                  paddingBottom:16 }}>{item.a}</div>
              )}
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div style={{ textAlign:'center', marginTop: m ? 48 : 80,
          padding: m ? '32px 0' : '60px 0', borderTop:'1px solid '+C.border }}>
          <h2 style={{ fontFamily:F.display, fontSize: m ? 36 : 56,
            color:C.white, margin:'0 0 24px', letterSpacing:'0.04em' }}>
            START YOUR 30-DAY PILOT
          </h2>
          <div style={{ display:'flex', gap:12, justifyContent:'center', flexWrap:'wrap' }}>
            <a href="#/onboard" style={{ background:C.gold, color:C.bg, textDecoration:'none',
              padding:'16px 32px', borderRadius:8, fontSize:16, fontWeight:700 }}>
              Free Assessment →
            </a>
            <a href="mailto:sales@coreholdingcorp.com" style={{ background:'none', color:C.white,
              textDecoration:'none', padding:'16px 32px', borderRadius:8, fontSize:16,
              fontWeight:500, border:'1px solid '+C.border }}>
              Talk to Sales
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
