// FoundersDashboard.jsx
// CHC Corporate Intelligence + Governance Operations Center
// Script 25-H — 8 tabs: Financial (4) + Governance (4)
// DO NOT hand edit — generated by 25-H

import { useState, useEffect, useCallback } from 'react';
import {
  AreaChart, Area, BarChart, Bar, LineChart, Line,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend,
  ResponsiveContainer
} from 'recharts';

// ── Design tokens ──────────────────────────────────────────
const C = {
  bg:'#0a0e1a', surface:'#111827', surface2:'#1a2235', border:'#1f2937',
  gold:'#d4a843', goldDim:'#92722d', blue:'#3b82f6', teal:'#14b8a6',
  red:'#ef4444', green:'#22c55e', slate:'#94a3b8', white:'#f1f5f9',
  orange:'#f97316', purple:'#a855f7', pink:'#ec4899', cyan:'#06b6d4'
};

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

// ── Financial data ─────────────────────────────────────────
const CI_REV  = [78000,82000,88000,92000,98000,105000,112000,118000,122000,128000,135000,142000];
const CI_TGT  = [85000,90000,96000,102000,109000,116000,123000,130000,136000,142000,149000,156000];
const CI_COST = [21000,21500,22000,22500,23000,23500,24000,24500,25000,25500,26000,26500];
const CG_RET  = [48000,52000,54000,60000,66000,70000,72000,72000,78000,82000,85000,88000];
const CG_PROJ = [15000,22000,35000,28000,42000,38000,55000,48000,62000,58000,72000,65000];
const CG_REV  = CG_RET.map((r,i) => r + CG_PROJ[i]);
const CG_TGT  = [70000,78000,90000,92000,115000,112000,130000,125000,145000,145000,162000,158000];
const CG_COST = [38000,39000,40000,41000,42000,43000,44000,45000,46000,47000,48000,49000];
const CHC_REV  = CI_REV.map((r,i) => r + CG_REV[i]);
const CHC_TGT  = CI_TGT.map((t,i) => t + CG_TGT[i]);
const CHC_COST = CI_COST.map((c,i) => c + CG_COST[i]);
const CHC_PROF = CHC_REV.map((r,i) => r - CHC_COST[i]);

const CI_AGENTS = [
  { name:'Identity Verification Agent',    cat:'Identity',    exec:14820, status:'Active' },
  { name:'KYC Compliance Agent',            cat:'Compliance',  exec:8930,  status:'Active' },
  { name:'Auth Decision Engine',            cat:'Auth',        exec:22140, status:'Active' },
  { name:'Risk Scoring Agent',              cat:'Risk',        exec:6720,  status:'Active' },
  { name:'Document Verification AI',        cat:'Identity',    exec:9340,  status:'Active' },
  { name:'Fraud Signal Aggregator',         cat:'Fraud',       exec:11250, status:'Active' },
  { name:'Biometric Match Agent',           cat:'Identity',    exec:4180,  status:'Active' },
  { name:'Session Trust Evaluator',         cat:'Auth',        exec:18930, status:'Active' },
  { name:'Credential Lifecycle Manager',    cat:'Identity',    exec:3890,  status:'Active' },
  { name:'Access Policy Engine',            cat:'Policy',      exec:7620,  status:'Active' },
  { name:'Anomaly Detection Agent',         cat:'Security',    exec:15440, status:'Active' },
  { name:'Consent Management AI',           cat:'Compliance',  exec:2940,  status:'Active' },
  { name:'Directory Sync Agent',            cat:'Identity',    exec:5210,  status:'Active' },
  { name:'Token Governance Agent',          cat:'Auth',        exec:9870,  status:'Active' },
  { name:'Audit Event Classifier',          cat:'Compliance',  exec:12380, status:'Active' },
];
const CG_AGENTS = [
  { name:'Governance Readiness Assessor',   cat:'Advisory',    exec:340,   status:'Active' },
  { name:'Regulatory Mapping AI',           cat:'Compliance',  exec:128,   status:'Active' },
  { name:'Risk Framework Advisor',          cat:'Advisory',    exec:87,    status:'Active' },
  { name:'Policy Gap Analyzer',             cat:'Compliance',  exec:214,   status:'Active' },
  { name:'Board Reporting Generator',       cat:'Reporting',   exec:96,    status:'Active' },
  { name:'RAIGA Implementation AI',         cat:'Advisory',    exec:42,    status:'Active' },
  { name:'Client Onboarding Agent',         cat:'Operations',  exec:189,   status:'Active' },
  { name:'Compliance Calendar Manager',     cat:'Compliance',  exec:73,    status:'Active' },
];

// ── Demo data for audit dispatch ───────────────────────────
const DEMO_AGENTS = {
  bank:   [{id:'b-01',name:'Fraud Detection Agent',task:'fraud-detection'},{id:'b-02',name:'AML Monitoring Agent',task:'aml-monitoring'},{id:'b-03',name:'Credit Scoring Agent',task:'credit-scoring'},{id:'b-07',name:'Transaction Monitoring',task:'transaction-monitoring'}],
  health: [{id:'h-02',name:'Clinical Decision Support',task:'clinical-recommendation'},{id:'h-08',name:'Pharmacy Interaction Check',task:'drug-interaction'},{id:'h-10',name:'Sepsis Early Warning',task:'sepsis-alert'},{id:'h-04',name:'Insurance Eligibility',task:'eligibility-verification'}],
  retail: [{id:'r-03',name:'Fraud Detection Agent',task:'transaction-fraud'},{id:'r-12',name:'PCI Compliance Monitor',task:'pci-monitoring'},{id:'r-07',name:'Loyalty Scoring Agent',task:'loyalty-scoring'}],
  legal:  [{id:'l-06',name:'Conflict Check Agent',task:'conflict-check'},{id:'l-03',name:'eDiscovery Classifier',task:'document-classification'},{id:'l-01',name:'Contract Review Agent',task:'contract-analysis'}],
};
const CLIENT_COLORS = {bank:C.blue, health:C.green, retail:C.orange, legal:C.purple};
const CLIENT_ICONS  = {bank:'🏦', health:'🏥', retail:'🛍️', legal:'⚖️'};
const CLIENT_LABELS = {bank:'First National Virtual Bank', health:'Cascade Regional Health Network', retail:'Summit Retail Group', legal:'Meridian Legal Partners LLP'};

// ── SmartNation 108-agent registry ─────────────────────────
const SN_DOMAINS = [
  { id:'financial',    label:'Financial Services', color:C.blue,   count:24 },
  { id:'healthcare',   label:'Healthcare',          color:C.green,  count:22 },
  { id:'retail',       label:'Retail & Commerce',   color:C.orange, count:18 },
  { id:'legal',        label:'Legal & Compliance',  color:C.purple, count:16 },
  { id:'hospitality',  label:'Hospitality',         color:C.teal,   count:12 },
  { id:'manufacturing',label:'Manufacturing',        color:C.cyan,   count:8  },
  { id:'sovereign',    label:'Sovereign / Gov',      color:C.gold,   count:8  },
];
const SN_AGENTS = [
  // Financial (24)
  {id:'fin-01',name:'Fraud Detection Agent',domain:'financial',fw:'GLBA,PCI-DSS',score:98,status:'Active',exec:14820},
  {id:'fin-02',name:'AML Monitoring Agent',domain:'financial',fw:'BSA/AML,FinCEN',score:99,status:'Active',exec:8930},
  {id:'fin-03',name:'Credit Scoring Agent',domain:'financial',fw:'FCRA,ECOA',score:97,status:'Active',exec:6720},
  {id:'fin-04',name:'Wire Transfer Agent',domain:'financial',fw:'GLBA,OFAC',score:98,status:'Active',exec:4210},
  {id:'fin-05',name:'Transaction Monitoring',domain:'financial',fw:'PCI-DSS,GLBA',score:97,status:'Active',exec:11250},
  {id:'fin-06',name:'KYC Verification Agent',domain:'financial',fw:'BSA/AML,GLBA',score:96,status:'Active',exec:9340},
  {id:'fin-07',name:'Sanctions Screening AI',domain:'financial',fw:'OFAC,FinCEN',score:99,status:'Active',exec:5180},
  {id:'fin-08',name:'Account Takeover Detector',domain:'financial',fw:'GLBA,CCPA',score:95,status:'Active',exec:7620},
  {id:'fin-09',name:'Loan Origination Agent',domain:'financial',fw:'ECOA,HMDA',score:94,status:'Active',exec:3890},
  {id:'fin-10',name:'Insurance Risk Scorer',domain:'financial',fw:'NAIC,GLBA',score:93,status:'Active',exec:2940},
  {id:'fin-11',name:'Derivatives Compliance AI',domain:'financial',fw:'Dodd-Frank,CFTC',score:96,status:'Active',exec:1820},
  {id:'fin-12',name:'FFIEC Compliance Monitor',domain:'financial',fw:'FFIEC,SOX',score:97,status:'Active',exec:4320},
  {id:'fin-13',name:'Crypto AML Agent',domain:'financial',fw:'FinCEN,BSA',score:95,status:'Active',exec:3140},
  {id:'fin-14',name:'Consumer Lending AI',domain:'financial',fw:'TILA,RESPA',score:94,status:'Active',exec:2780},
  {id:'fin-15',name:'Market Abuse Detector',domain:'financial',fw:'SEC,FINRA',score:97,status:'Active',exec:1960},
  {id:'fin-16',name:'Correspondent Banking AI',domain:'financial',fw:'SWIFT,BSA',score:98,status:'Active',exec:870},
  {id:'fin-17',name:'Investment Suitability Agent',domain:'financial',fw:'FINRA,SEC',score:95,status:'Active',exec:2340},
  {id:'fin-18',name:'Reg-E Dispute Agent',domain:'financial',fw:'CFPB,Reg-E',score:93,status:'Active',exec:3560},
  {id:'fin-19',name:'CCAR Stress Test AI',domain:'financial',fw:'Fed Reg,Basel III',score:96,status:'Active',exec:420},
  {id:'fin-20',name:'Beneficial Owner Tracker',domain:'financial',fw:'CDD,BSA',score:97,status:'Active',exec:1780},
  {id:'fin-21',name:'Trade Finance Agent',domain:'financial',fw:'UCC,ISBP',score:94,status:'Active',exec:1240},
  {id:'fin-22',name:'Overdraft Policy AI',domain:'financial',fw:'CFPB,Reg-E',score:92,status:'Active',exec:4890},
  {id:'fin-23',name:'PCI DSS Monitor',domain:'financial',fw:'PCI-DSS v4.0',score:98,status:'Active',exec:6230},
  {id:'fin-24',name:'SOX Controls Agent',domain:'financial',fw:'SOX,PCAOB',score:97,status:'Active',exec:890},
  // Healthcare (22)
  {id:'hlt-01',name:'Clinical Decision Support',domain:'healthcare',fw:'HIPAA,CMS',score:95,status:'Active',exec:18930},
  {id:'hlt-02',name:'Pharmacy Interaction Check',domain:'healthcare',fw:'HIPAA,FDA 21 CFR',score:96,status:'Active',exec:12380},
  {id:'hlt-03',name:'Sepsis Early Warning',domain:'healthcare',fw:'HIPAA,HITECH',score:96,status:'Active',exec:9870},
  {id:'hlt-04',name:'Insurance Eligibility AI',domain:'healthcare',fw:'HIPAA,HITECH',score:95,status:'Active',exec:7620},
  {id:'hlt-05',name:'Patient Risk Stratification',domain:'healthcare',fw:'HIPAA,CMS',score:94,status:'Active',exec:5210},
  {id:'hlt-06',name:'Prior Auth Agent',domain:'healthcare',fw:'CMS,HIPAA',score:93,status:'Active',exec:8940},
  {id:'hlt-07',name:'CDI Query Agent',domain:'healthcare',fw:'HIPAA,CMS',score:94,status:'Active',exec:6320},
  {id:'hlt-08',name:'Lab Result Interpreter',domain:'healthcare',fw:'HIPAA,CAP',score:95,status:'Active',exec:4180},
  {id:'hlt-09',name:'Readmission Risk Agent',domain:'healthcare',fw:'CMS,HIPAA',score:93,status:'Active',exec:3890},
  {id:'hlt-10',name:'Drug Utilization Reviewer',domain:'healthcare',fw:'FDA,HIPAA',score:95,status:'Active',exec:2940},
  {id:'hlt-11',name:'HIPAA Breach Detector',domain:'healthcare',fw:'HIPAA,HITECH',score:98,status:'Active',exec:1820},
  {id:'hlt-12',name:'Medical Necessity AI',domain:'healthcare',fw:'CMS,AMA',score:92,status:'Active',exec:4320},
  {id:'hlt-13',name:'Telemedicine Compliance AI',domain:'healthcare',fw:'HIPAA,Ryan Haight',score:94,status:'Active',exec:2780},
  {id:'hlt-14',name:'Mental Health Risk Agent',domain:'healthcare',fw:'HIPAA,42 CFR Part 2',score:97,status:'Active',exec:1960},
  {id:'hlt-15',name:'Clinical Trial Monitor',domain:'healthcare',fw:'FDA 21 CFR,ICH',score:96,status:'Active',exec:870},
  {id:'hlt-16',name:'Advance Directive Agent',domain:'healthcare',fw:'HIPAA,State Law',score:95,status:'Active',exec:2340},
  {id:'hlt-17',name:'RPM Alert Agent',domain:'healthcare',fw:'FDA,HIPAA',score:94,status:'Active',exec:3560},
  {id:'hlt-18',name:'Immunization Registry AI',domain:'healthcare',fw:'CDC,HIPAA',score:93,status:'Active',exec:4890},
  {id:'hlt-19',name:'Formulary Compliance AI',domain:'healthcare',fw:'CMS,FDA',score:95,status:'Active',exec:6230},
  {id:'hlt-20',name:'Credentialing Agent',domain:'healthcare',fw:'NCQA,HIPAA',score:96,status:'Active',exec:1240},
  {id:'hlt-21',name:'Home Health Monitor',domain:'healthcare',fw:'CMS,HIPAA',score:92,status:'Active',exec:3140},
  {id:'hlt-22',name:'SDoH Screening Agent',domain:'healthcare',fw:'CMS,HIPAA',score:93,status:'Active',exec:2780},
  // Retail (18)
  {id:'ret-01',name:'Transaction Fraud Agent',domain:'retail',fw:'PCI-DSS,CCPA',score:94,status:'Active',exec:22140},
  {id:'ret-02',name:'PCI Compliance Monitor',domain:'retail',fw:'PCI-DSS v4.0',score:92,status:'Active',exec:15440},
  {id:'ret-03',name:'Loyalty Scoring Agent',domain:'retail',fw:'CCPA,FTC',score:91,status:'Active',exec:9340},
  {id:'ret-04',name:'Price Parity Agent',domain:'retail',fw:'FTC,Sherman Act',score:90,status:'Active',exec:4180},
  {id:'ret-05',name:'Return Fraud Detector',domain:'retail',fw:'FTC,CCPA',score:93,status:'Active',exec:8930},
  {id:'ret-06',name:'Product Recall Monitor',domain:'retail',fw:'CPSC,FDA',score:95,status:'Active',exec:2340},
  {id:'ret-07',name:'Advertising Compliance AI',domain:'retail',fw:'FTC,NAD',score:91,status:'Active',exec:6720},
  {id:'ret-08',name:'Age Verification Agent',domain:'retail',fw:'COPPA,State Law',score:94,status:'Active',exec:3890},
  {id:'ret-09',name:'Supply Chain Compliance AI',domain:'retail',fw:'CTPAT,FSMA',score:92,status:'Active',exec:1820},
  {id:'ret-10',name:'Labor Compliance Monitor',domain:'retail',fw:'FLSA,OSHA',score:93,status:'Active',exec:2780},
  {id:'ret-11',name:'Warranty Compliance Agent',domain:'retail',fw:'Magnuson-Moss,FTC',score:90,status:'Active',exec:4320},
  {id:'ret-12',name:'Consumer Protection AI',domain:'retail',fw:'UDAP,FTC',score:92,status:'Active',exec:5210},
  {id:'ret-13',name:'Data Minimization Agent',domain:'retail',fw:'CCPA,CPRA',score:94,status:'Active',exec:3140},
  {id:'ret-14',name:'Cart Abandonment Guard',domain:'retail',fw:'CAN-SPAM,CCPA',score:89,status:'Active',exec:7620},
  {id:'ret-15',name:'Gift Card Compliance AI',domain:'retail',fw:'CARD Act,State',score:91,status:'Active',exec:1960},
  {id:'ret-16',name:'Cross-Border Trade Agent',domain:'retail',fw:'CBP,ITAR',score:93,status:'Active',exec:870},
  {id:'ret-17',name:'ESG Reporting Agent',domain:'retail',fw:'GRI,SEC',score:90,status:'Active',exec:1240},
  {id:'ret-18',name:'Inventory Accuracy AI',domain:'retail',fw:'SOX,GAAP',score:92,status:'Active',exec:2940},
  // Legal (16)
  {id:'leg-01',name:'Conflict Check Agent',domain:'legal',fw:'ABA Rule 1.7,CCPA',score:93,status:'Active',exec:18930},
  {id:'leg-02',name:'eDiscovery Classifier',domain:'legal',fw:'FRCP,ABA',score:94,status:'Active',exec:12380},
  {id:'leg-03',name:'Contract Review Agent',domain:'legal',fw:'UCC,ABA',score:93,status:'Active',exec:9870},
  {id:'leg-04',name:'Privilege Review Agent',domain:'legal',fw:'ABA Rule 1.6,FRCP',score:96,status:'Active',exec:7620},
  {id:'leg-05',name:'Legal Research AI',domain:'legal',fw:'ABA,Court Rules',score:91,status:'Active',exec:5210},
  {id:'leg-06',name:'Billing Compliance Agent',domain:'legal',fw:'ABA Rule 1.5',score:92,status:'Active',exec:8940},
  {id:'leg-07',name:'Deadline Management AI',domain:'legal',fw:'FRCP,Local Rules',score:95,status:'Active',exec:6320},
  {id:'leg-08',name:'Client Intake Agent',domain:'legal',fw:'ABA,State Bar',score:90,status:'Active',exec:4180},
  {id:'leg-09',name:'Court Filing Monitor',domain:'legal',fw:'CM/ECF,FRCP',score:94,status:'Active',exec:3890},
  {id:'leg-10',name:'IP Clearance Agent',domain:'legal',fw:'USPTO,TTAB',score:92,status:'Active',exec:2940},
  {id:'leg-11',name:'Regulatory Filing AI',domain:'legal',fw:'SEC,FTC,DOJ',score:95,status:'Active',exec:1820},
  {id:'leg-12',name:'Settlement Valuation AI',domain:'legal',fw:'FRE,ABA',score:91,status:'Active',exec:4320},
  {id:'leg-13',name:'Expert Witness Screener',domain:'legal',fw:'Daubert,FRE 702',score:93,status:'Active',exec:2780},
  {id:'leg-14',name:'GDPR Compliance Agent',domain:'legal',fw:'GDPR,CCPA',score:96,status:'Active',exec:1960},
  {id:'leg-15',name:'Anti-Corruption Monitor',domain:'legal',fw:'FCPA,UK Bribery',score:97,status:'Active',exec:870},
  {id:'leg-16',name:'Litigation Hold Agent',domain:'legal',fw:'FRCP,ABA',score:94,status:'Active',exec:2340},
  // Hospitality (12)
  {id:'hos-01',name:'Guest Data Compliance AI',domain:'hospitality',fw:'GDPR,CCPA',score:92,status:'Active',exec:8930},
  {id:'hos-02',name:'Revenue Management Agent',domain:'hospitality',fw:'FTC,ADA',score:90,status:'Active',exec:6720},
  {id:'hos-03',name:'Food Safety Monitor',domain:'hospitality',fw:'FDA,FSMA',score:95,status:'Active',exec:4180},
  {id:'hos-04',name:'ADA Compliance Agent',domain:'hospitality',fw:'ADA,DOT',score:94,status:'Active',exec:3890},
  {id:'hos-05',name:'Labor Scheduling AI',domain:'hospitality',fw:'FLSA,State',score:91,status:'Active',exec:9340},
  {id:'hos-06',name:'Liquor License Monitor',domain:'hospitality',fw:'TTB,State ABC',score:93,status:'Active',exec:2940},
  {id:'hos-07',name:'OTA Parity Agent',domain:'hospitality',fw:'FTC,ARDA',score:89,status:'Active',exec:1820},
  {id:'hos-08',name:'Fire Safety Compliance AI',domain:'hospitality',fw:'OSHA,NFPA',score:96,status:'Active',exec:4320},
  {id:'hos-09',name:'Health Code Monitor',domain:'hospitality',fw:'FDA,State DOH',score:95,status:'Active',exec:2780},
  {id:'hos-10',name:'Tipping Compliance Agent',domain:'hospitality',fw:'FLSA,IRS',score:92,status:'Active',exec:5210},
  {id:'hos-11',name:'Loyalty Data Guard',domain:'hospitality',fw:'CCPA,GDPR',score:91,status:'Active',exec:3140},
  {id:'hos-12',name:'STR Compliance AI',domain:'hospitality',fw:'Local Ord,FTC',score:90,status:'Active',exec:1960},
  // Manufacturing (8)
  {id:'mfg-01',name:'OSHA Safety Monitor',domain:'manufacturing',fw:'OSHA,ANSI',score:97,status:'Active',exec:6230},
  {id:'mfg-02',name:'EPA Emissions Agent',domain:'manufacturing',fw:'EPA,CAA',score:95,status:'Active',exec:4180},
  {id:'mfg-03',name:'Product Safety AI',domain:'manufacturing',fw:'CPSC,ISO',score:94,status:'Active',exec:3890},
  {id:'mfg-04',name:'Supply Chain ESG Agent',domain:'manufacturing',fw:'SEC,GRI',score:91,status:'Active',exec:2940},
  {id:'mfg-05',name:'Quality Control AI',domain:'manufacturing',fw:'ISO 9001,FDA',score:96,status:'Active',exec:1820},
  {id:'mfg-06',name:'Export Control Agent',domain:'manufacturing',fw:'EAR,ITAR',score:98,status:'Active',exec:870},
  {id:'mfg-07',name:'Hazmat Compliance AI',domain:'manufacturing',fw:'DOT,EPA',score:95,status:'Active',exec:2340},
  {id:'mfg-08',name:'Conflict Minerals Agent',domain:'manufacturing',fw:'Dodd-Frank 1502',score:93,status:'Active',exec:1240},
  // Sovereign (8)
  {id:'sov-01',name:'AML National Monitor',domain:'sovereign',fw:'FATF,FinCEN',score:99,status:'Active',exec:2780},
  {id:'sov-02',name:'Tax Compliance AI',domain:'sovereign',fw:'OECD,FATCA',score:97,status:'Active',exec:3140},
  {id:'sov-03',name:'Border Control Agent',domain:'sovereign',fw:'DHS,CBP',score:98,status:'Active',exec:1960},
  {id:'sov-04',name:'Financial Intelligence AI',domain:'sovereign',fw:'FATF,Egmont',score:99,status:'Active',exec:870},
  {id:'sov-05',name:'Sanctions Compliance AI',domain:'sovereign',fw:'OFAC,UN Sanctions',score:99,status:'Active',exec:2340},
  {id:'sov-06',name:'Procurement Monitor',domain:'sovereign',fw:'FAR,ITAR',score:95,status:'Active',exec:1240},
  {id:'sov-07',name:'Digital ID Governance AI',domain:'sovereign',fw:'NIST,ISO 29115',score:96,status:'Active',exec:4320},
  {id:'sov-08',name:'National AI Governance',domain:'sovereign',fw:'EU AI Act,NIST AI RMF',score:97,status:'Active',exec:2780},
];

// ── CIAG data ──────────────────────────────────────────────
const RETAINERS = [
  { name:'Meridian Wealth Partners LLC',    rev:'$22K/mo', started:'Mar 2025', fw:'GLBA · CCPA',       status:'Active' },
  { name:'Harbor Point Investment Group',   rev:'$18K/mo', started:'May 2025', fw:'GLBA · SOX',        status:'Active' },
  { name:'Pacific Crest Financial Services',rev:'$28K/mo', started:'Jun 2025', fw:'CCPA · PCI-DSS',    status:'Active' },
  { name:'Summit Valley Bank',              rev:'$20K/mo', started:'Sep 2025', fw:'FFIEC · GLBA',      status:'Active' },
];
const PROJECTS = [
  { name:'AI Governance Readiness Assessment',client:'Westlake Regional CU',  value:'$85K',  pct:68, status:'Active'    },
  { name:'CCPA + GLBA Compliance Mapping',    client:'Meridian Wealth',        value:'$45K',  pct:82, status:'Active'    },
  { name:'Texas RAIGA Implementation Plan',   client:'Regional Bank Consortium',value:'$120K', pct:35, status:'Active'    },
];

// ── Utilities ──────────────────────────────────────────────
const fmtK  = n => !n ? '$0' : n >= 1000000 ? '$'+(n/1000000).toFixed(2)+'M' : '$'+(n/1000).toFixed(0)+'K';
const last  = a => a?.[a.length-1] ?? 0;
const delta = (a,b) => b ? ((a-b)/b*100).toFixed(1) : '0.0';
const fmtMs = ms => ms >= 1000 ? (ms/1000).toFixed(1)+'s' : ms+'ms';
const fmtAgo= iso => { if(!iso) return '—'; const s=Math.floor((Date.now()-new Date(iso))/1000); if(s<60) return s+'s ago'; if(s<3600) return Math.floor(s/60)+'m ago'; return Math.floor(s/3600)+'h ago'; };
const scoreColor = s => s>=95?C.green:s>=90?C.teal:s>=80?C.orange:C.red;

function buildTrend(rev,cost,tgt) {
  return MONTHS.map((m,i) => ({month:m, Revenue:rev[i], Costs:cost[i], Profit:rev[i]-cost[i], Target:tgt[i]}));
}
function buildVariance(rev,tgt) {
  return MONTHS.map((m,i) => ({month:m, Actual:rev[i], Target:tgt[i], Variance:rev[i]-tgt[i]}));
}

// ── Shared UI components ───────────────────────────────────
function MetricCard({label, value, sub, accent, trend:t}) {
  const tc = t===undefined ? C.slate : t>=0 ? C.green : C.red;
  return (
    <div style={{background:C.surface,border:'1px solid '+C.border,borderRadius:8,padding:'20px 24px',flex:1,minWidth:160}}>
      <div style={{color:C.slate,fontSize:11,letterSpacing:'0.1em',textTransform:'uppercase',marginBottom:8}}>{label}</div>
      <div style={{color:accent||C.gold,fontSize:28,fontWeight:700,fontFamily:'monospace',letterSpacing:0}}>{value}</div>
      {sub && <div style={{color:tc,fontSize:12,marginTop:6}}>{t!==undefined&&(t>=0?'▲ ':'▼ ')}{sub}</div>}
    </div>
  );
}
function SecHdr({title, live, action}) {
  return (
    <div style={{borderBottom:'1px solid '+C.border,paddingBottom:10,marginBottom:16,display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:8}}>
      <span style={{color:C.slate,fontSize:11,letterSpacing:'0.12em',textTransform:'uppercase'}}>{title}</span>
      <div style={{display:'flex',gap:8,alignItems:'center'}}>
        {action}
        {live && <span style={{background:C.green+'22',color:C.green,border:'1px solid '+C.green+'44',borderRadius:4,fontSize:9,padding:'2px 8px',fontWeight:600}}>● LIVE</span>}
      </div>
    </div>
  );
}
function Pill({label, color}) {
  return <span style={{background:color+'22',color,border:'1px solid '+color+'44',borderRadius:4,fontSize:10,padding:'2px 8px',fontWeight:600,textTransform:'uppercase',whiteSpace:'nowrap'}}>{label}</span>;
}
function PBar({value, color}) {
  return <div style={{background:C.border,borderRadius:4,height:6,width:'100%',overflow:'hidden'}}><div style={{width:Math.min(value||0,100)+'%',height:'100%',background:color||C.gold,borderRadius:4}}/></div>;
}
function ChartTip({active,payload,label}) {
  if(!active||!payload?.length) return null;
  return <div style={{background:'#1a2035',border:'1px solid '+C.border,borderRadius:6,padding:'10px 14px'}}><div style={{color:C.slate,fontSize:11,marginBottom:6}}>{label}</div>{payload.map((p,i)=><div key={i} style={{color:p.color,fontSize:13,fontFamily:'monospace',letterSpacing:0}}>{p.name}: {fmtK(p.value)}</div>)}</div>;
}

// ── View mode toggle component ─────────────────────────────
function ViewToggle({vm, setVm}) {
  const VIEWS = [
    {id:'actuals',    label:'Actuals',        desc:'Current month P&L'},
    {id:'vs-targets', label:'vs Targets',     desc:'Monthly variance vs plan'},
    {id:'trend',      label:'12-Month Trend', desc:'Year-over-year trajectory'},
  ];
  return (
    <div style={{padding:'14px 28px',borderBottom:'1px solid '+C.border+'66',display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'}}>
      <span style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',marginRight:4}}>View:</span>
      {VIEWS.map(v => (
        <button key={v.id} onClick={()=>setVm(v.id)} style={{
          background: vm===v.id ? C.gold+'22' : 'none',
          border: '1px solid '+(vm===v.id ? C.gold : C.border),
          color: vm===v.id ? C.gold : C.slate,
          borderRadius:6, padding:'6px 14px', fontSize:12, cursor:'pointer',
          fontWeight: vm===v.id ? 600 : 400,
          transition:'all 0.15s', whiteSpace:'nowrap'
        }}>
          {v.label}
        </button>
      ))}
      <span style={{color:C.slate+'88',fontSize:11,marginLeft:4}}>
        {VIEWS.find(v=>v.id===vm)?.desc}
      </span>
    </div>
  );
}

// ── FINANCIAL VIEWS ────────────────────────────────────────
function ConsolidatedView({vm}) {
  const curRev=last(CHC_REV), curCost=last(CHC_COST), curProf=last(CHC_PROF);
  const curMgn=Math.round(curProf/curRev*100);
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="Total MRR"  value={fmtK(curRev)}    sub={delta(curRev,CHC_REV[10])+'% MoM'}    trend={parseFloat(delta(curRev,CHC_REV[10]))} />
        <MetricCard label="ARR"        value={fmtK(curRev*12)} sub="Annualized run rate"                   accent={C.blue} />
        <MetricCard label="Net Profit" value={fmtK(curProf)}   sub={delta(curProf,CHC_PROF[10])+'% MoM'}  trend={parseFloat(delta(curProf,CHC_PROF[10]))} accent={C.green} />
        <MetricCard label="Net Margin" value={curMgn+'%'}      sub="Blended CHC margin"                   accent={C.teal} />
        <MetricCard label="CHC Agents" value={CI_AGENTS.length+CG_AGENTS.length} sub="All governed (100%)" accent={C.gold} />
      </div>

      {vm==='trend' && (
        <>
          <SecHdr title="12-Month Revenue · Costs · Profit"/>
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={buildTrend(CHC_REV,CHC_COST,CHC_TGT)}>
              <defs>
                <linearGradient id="gRev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.gold} stopOpacity={0.2}/><stop offset="95%" stopColor={C.gold} stopOpacity={0}/></linearGradient>
                <linearGradient id="gPrf" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.green} stopOpacity={0.2}/><stop offset="95%" stopColor={C.green} stopOpacity={0}/></linearGradient>
              </defs>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Area type="monotone" dataKey="Revenue" stroke={C.gold}  fill="url(#gRev)" strokeWidth={2}/>
              <Area type="monotone" dataKey="Profit"  stroke={C.green} fill="url(#gPrf)" strokeWidth={2}/>
              <Line type="monotone" dataKey="Costs"   stroke={C.red}   strokeWidth={1.5} dot={false}/>
            </AreaChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='vs-targets' && (
        <>
          <SecHdr title="Actuals vs Targets — Monthly Variance"/>
          <div style={{background:C.surface2,border:'1px solid '+C.border,borderRadius:8,padding:'12px 16px',marginBottom:16,display:'flex',gap:24,flexWrap:'wrap'}}>
            {(() => { const last3=[9,10,11]; return last3.map(i => { const v=CHC_REV[i]-CHC_TGT[i]; return <div key={i}><div style={{color:C.slate,fontSize:10,textTransform:'uppercase'}}>{MONTHS[i]}</div><div style={{color:v>=0?C.green:C.red,fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{v>=0?'+':''}{fmtK(v)}</div><div style={{color:C.slate,fontSize:10}}>{v>=0?'Beat':'Miss'} by {Math.abs(Math.round(v/CHC_TGT[i]*100))}%</div></div>; }); })()}
          </div>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={buildVariance(CHC_REV,CHC_TGT)}>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Bar dataKey="Target" fill={C.border+'cc'} radius={[2,2,0,0]}/>
              <Bar dataKey="Actual" fill={C.gold}        radius={[2,2,0,0]}/>
            </BarChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='actuals' && (
        <>
          <SecHdr title="Subsidiary P&L — Current Month"/>
          <div style={{overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:13,minWidth:620}}>
              <thead>
                <tr style={{borderBottom:'1px solid '+C.border}}>
                  {['Entity','Type','Revenue','Costs','Net Profit','Margin','Agents'].map(h=>(
                    <th key={h} style={{textAlign:'left',padding:'8px 14px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',whiteSpace:'nowrap'}}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                <tr style={{borderBottom:'1px solid '+C.border}}>
                  <td style={{padding:'12px 14px',color:C.white,fontWeight:600}}>CoreIdentity</td>
                  <td style={{padding:'12px 14px',color:C.slate,fontSize:12}}>SaaS Platform</td>
                  <td style={{padding:'12px 14px',color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{fmtK(last(CI_REV))}</td>
                  <td style={{padding:'12px 14px',color:C.red,fontFamily:'monospace',letterSpacing:0}}>{fmtK(last(CI_COST))}</td>
                  <td style={{padding:'12px 14px',color:C.green,fontFamily:'monospace',letterSpacing:0,fontWeight:600}}>{fmtK(last(CI_REV)-last(CI_COST))}</td>
                  <td style={{padding:'12px 14px',color:C.teal}}>{Math.round((last(CI_REV)-last(CI_COST))/last(CI_REV)*100)}%</td>
                  <td style={{padding:'12px 14px',color:C.white}}>{CI_AGENTS.length}</td>
                </tr>
                <tr style={{borderBottom:'1px solid '+C.border}}>
                  <td style={{padding:'12px 14px',color:C.white,fontWeight:600}}>CIAG</td>
                  <td style={{padding:'12px 14px',color:C.slate,fontSize:12}}>Advisory Group</td>
                  <td style={{padding:'12px 14px',color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{fmtK(last(CG_REV))}</td>
                  <td style={{padding:'12px 14px',color:C.red,fontFamily:'monospace',letterSpacing:0}}>{fmtK(last(CG_COST))}</td>
                  <td style={{padding:'12px 14px',color:C.green,fontFamily:'monospace',letterSpacing:0,fontWeight:600}}>{fmtK(last(CG_REV)-last(CG_COST))}</td>
                  <td style={{padding:'12px 14px',color:C.teal}}>{Math.round((last(CG_REV)-last(CG_COST))/last(CG_REV)*100)}%</td>
                  <td style={{padding:'12px 14px',color:C.white}}>{CG_AGENTS.length}</td>
                </tr>
                <tr style={{background:C.border+'33'}}>
                  <td style={{padding:'12px 14px',color:C.gold,fontWeight:700}}>CHC Consolidated</td>
                  <td style={{padding:'12px 14px',color:C.slate,fontSize:12}}>Holding Company</td>
                  <td style={{padding:'12px 14px',color:C.gold,fontFamily:'monospace',letterSpacing:0,fontWeight:700}}>{fmtK(curRev)}</td>
                  <td style={{padding:'12px 14px',color:C.red,fontFamily:'monospace',letterSpacing:0,fontWeight:700}}>{fmtK(curCost)}</td>
                  <td style={{padding:'12px 14px',color:C.green,fontFamily:'monospace',letterSpacing:0,fontWeight:700}}>{fmtK(curProf)}</td>
                  <td style={{padding:'12px 14px',color:C.teal,fontWeight:700}}>{curMgn}%</td>
                  <td style={{padding:'12px 14px',color:C.white,fontWeight:700}}>{CI_AGENTS.length+CG_AGENTS.length}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}

function CoreIdentityView({vm}) {
  const curRev=last(CI_REV), curCost=last(CI_COST), curProf=curRev-curCost;
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="MRR"        value={fmtK(curRev)}  sub={delta(curRev,CI_REV[10])+'% MoM'}   trend={parseFloat(delta(curRev,CI_REV[10]))} />
        <MetricCard label="ARR"        value={fmtK(curRev*12)} sub="Annualized"                        accent={C.blue} />
        <MetricCard label="Net Profit" value={fmtK(curProf)} sub={delta(curProf,CI_REV[10]-CI_COST[10])+'% MoM'} trend={1} accent={C.green} />
        <MetricCard label="NRR"        value="118%"           sub="Net Revenue Retention"              accent={C.teal} />
        <MetricCard label="Customers"  value="8"              sub="Enterprise accounts"                accent={C.gold} />
        <MetricCard label="Agents"     value={CI_AGENTS.length} sub="All governed"                    accent={C.gold} />
      </div>
      {vm==='trend' && (
        <>
          <SecHdr title="CoreIdentity — 12-Month Revenue Trend"/>
          <ResponsiveContainer width="100%" height={240}>
            <AreaChart data={buildTrend(CI_REV,CI_COST,CI_TGT)}>
              <defs>
                <linearGradient id="ciRev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.blue} stopOpacity={0.2}/><stop offset="95%" stopColor={C.blue} stopOpacity={0}/></linearGradient>
              </defs>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Area type="monotone" dataKey="Revenue" stroke={C.blue} fill="url(#ciRev)" strokeWidth={2}/>
              <Line type="monotone" dataKey="Target"  stroke={C.slate} strokeDasharray="5 5" strokeWidth={1.5} dot={false}/>
              <Line type="monotone" dataKey="Costs"   stroke={C.red}   strokeWidth={1.5} dot={false}/>
            </AreaChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='vs-targets' && (
        <>
          <SecHdr title="CoreIdentity — Actuals vs Targets"/>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={buildVariance(CI_REV,CI_TGT)}>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Bar dataKey="Target" fill={C.border+'cc'} radius={[2,2,0,0]}/>
              <Bar dataKey="Actual" fill={C.blue}        radius={[2,2,0,0]}/>
            </BarChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='actuals' && (
        <>
          <SecHdr title="Platform Agents — Current Month Activity"/>
          <div style={{overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:500}}>
              <thead>
                <tr style={{borderBottom:'1px solid '+C.border}}>
                  {['Agent Name','Category','Executions','Status','Governed'].map(h=>(
                    <th key={h} style={{textAlign:'left',padding:'8px 12px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',whiteSpace:'nowrap'}}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {CI_AGENTS.map((a,i)=>(
                  <tr key={i} style={{borderBottom:'1px solid '+C.border+'44',background:i%2===0?'transparent':C.surface+'66'}}>
                    <td style={{padding:'9px 12px',color:C.white}}>{a.name}</td>
                    <td style={{padding:'9px 12px'}}><Pill label={a.cat} color={C.blue}/></td>
                    <td style={{padding:'9px 12px',color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{a.exec.toLocaleString()}</td>
                    <td style={{padding:'9px 12px'}}><Pill label={a.status} color={C.green}/></td>
                    <td style={{padding:'9px 12px'}}><Pill label="Yes" color={C.teal}/></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}

function CIAGView({vm}) {
  const retMRR=last(CG_RET), projRev=last(CG_PROJ), totRev=retMRR+projRev, netProf=totRev-last(CG_COST);
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="Total Revenue"  value={fmtK(totRev)}  sub={delta(totRev,CG_REV[10])+'% MoM'}  trend={1} />
        <MetricCard label="Retainer MRR"   value={fmtK(retMRR)}  sub="Recurring base"                    accent={C.blue} />
        <MetricCard label="Project Rev"    value={fmtK(projRev)} sub="Active engagements"                accent={C.teal} />
        <MetricCard label="Net Profit"     value={fmtK(netProf)} sub="After ops costs"                   accent={C.green} />
        <MetricCard label="Pipeline"       value="$250K"          sub="3 qualified opportunities"         accent={C.gold} />
      </div>
      {vm==='trend' && (
        <>
          <SecHdr title="CIAG — 12-Month Revenue (Retainers + Projects)"/>
          <ResponsiveContainer width="100%" height={240}>
            <AreaChart data={buildTrend(CG_REV,CG_COST,CG_TGT)}>
              <defs>
                <linearGradient id="cgRev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.purple} stopOpacity={0.2}/><stop offset="95%" stopColor={C.purple} stopOpacity={0}/></linearGradient>
              </defs>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Area type="monotone" dataKey="Revenue" stroke={C.purple} fill="url(#cgRev)" strokeWidth={2}/>
              <Line type="monotone" dataKey="Target"  stroke={C.slate}  strokeDasharray="5 5" strokeWidth={1.5} dot={false}/>
              <Line type="monotone" dataKey="Costs"   stroke={C.red}    strokeWidth={1.5} dot={false}/>
            </AreaChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='vs-targets' && (
        <>
          <SecHdr title="CIAG — Actuals vs Targets"/>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={buildVariance(CG_REV,CG_TGT)}>
              <CartesianGrid stroke={C.border} strokeDasharray="3 3"/>
              <XAxis dataKey="month" tick={{fill:C.slate,fontSize:11}}/>
              <YAxis tickFormatter={v=>'$'+(v/1000)+'K'} tick={{fill:C.slate,fontSize:11}}/>
              <Tooltip content={<ChartTip/>}/>
              <Legend wrapperStyle={{color:C.slate,fontSize:12}}/>
              <Bar dataKey="Target" fill={C.border+'cc'} radius={[2,2,0,0]}/>
              <Bar dataKey="Actual" fill={C.purple}      radius={[2,2,0,0]}/>
            </BarChart>
          </ResponsiveContainer>
        </>
      )}
      {vm==='actuals' && (
        <>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,marginBottom:28}}>
            <div>
              <SecHdr title="Active Retainers (4)"/>
              {RETAINERS.map((r,i)=>(
                <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:8,padding:'14px 16px',marginBottom:10}}>
                  <div style={{color:C.white,fontWeight:600,fontSize:13,marginBottom:4}}>{r.name}</div>
                  <div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}>
                    <span style={{color:C.gold,fontFamily:'monospace',letterSpacing:0,fontWeight:700}}>{r.rev}</span>
                    <span style={{color:C.slate,fontSize:11}}>Started {r.started}</span>
                    <Pill label={r.status} color={C.green}/>
                  </div>
                  <div style={{color:C.slate,fontSize:11,marginTop:6}}>{r.fw}</div>
                </div>
              ))}
            </div>
            <div>
              <SecHdr title="Active Projects (3)"/>
              {PROJECTS.map((p,i)=>(
                <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:8,padding:'14px 16px',marginBottom:10}}>
                  <div style={{color:C.white,fontWeight:600,fontSize:12,marginBottom:4}}>{p.name}</div>
                  <div style={{color:C.slate,fontSize:11,marginBottom:8}}>{p.client} · <span style={{color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{p.value}</span></div>
                  <div style={{display:'flex',alignItems:'center',gap:8}}>
                    <div style={{flex:1}}><PBar value={p.pct} color={C.teal}/></div>
                    <span style={{color:C.teal,fontFamily:'monospace',fontSize:12,fontWeight:700,letterSpacing:0}}>{p.pct}%</span>
                  </div>
                </div>
              ))}
              <SecHdr title="Advisory Agents (8)"/>
              {CG_AGENTS.map((a,i)=>(
                <div key={i} style={{display:'flex',justifyContent:'space-between',padding:'8px 0',borderBottom:'1px solid '+C.border+'44'}}>
                  <span style={{color:C.white,fontSize:12}}>{a.name}</span>
                  <Pill label={a.cat} color={C.purple}/>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function ClientPortfolioView() {
  const CLIENTS = [
    { name:'First National Virtual Bank', sector:'Financial Services', assets:'$95.1M', agents:23, score_from:65, score_to:94, mitigated:'$4.75M', fw:['GLBA','CCPA','FFIEC','SOX','PCI-DSS'], penalties:['CCPA: $2,500–$7,500/violation','GLBA: $1M/day exposure','FFIEC: Regulatory action risk'] },
    { name:'Cascade Regional Health Network', sector:'Healthcare', assets:'$34.2M', agents:22, score_from:58, score_to:91, mitigated:'$6.2M', fw:['HIPAA','HITECH','CMS','FDA 21 CFR'], penalties:['HIPAA: $100–$1.9M/violation','HITECH: Criminal exposure','CMS: Audit trigger risk'] },
    { name:'Summit Retail Group', sector:'Retail & Commerce', assets:'$82.5M', agents:20, score_from:61, score_to:89, mitigated:'$3.9M', fw:['PCI-DSS','CCPA','CPRA','FTC'], penalties:['PCI DSS: $5K–$100K/month','CCPA: $7,500/intentional','FTC: Injunctive action risk'] },
    { name:'Meridian Legal Partners LLP', sector:'Legal Services', assets:'$18.7M', agents:1, score_from:72, score_to:96, mitigated:'$2.0M', fw:['ABA Rules','CCPA','GDPR','State Bar'], penalties:['State Bar: License suspension','GDPR: 4% global revenue','CCPA: $7,500/intentional'] },
  ];
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:28,flexWrap:'wrap'}}>
        <MetricCard label="Client Accounts"  value={CLIENTS.length}  sub="Active deployments"   accent={C.gold} />
        <MetricCard label="Total Agents"     value={CLIENTS.reduce((s,c)=>s+c.agents,0)} sub="All governed (100%)" accent={C.blue} />
        <MetricCard label="Total Mitigated"  value="$16.85M"         sub="Penalty exposure"      accent={C.green} />
        <MetricCard label="Avg Compliance"   value="92.5%"           sub="Avg lift +28pts"       accent={C.teal} />
      </div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}>
        {CLIENTS.map((cl,i)=>(
          <div key={i} style={{background:C.surface,border:'1px solid '+C.border,borderRadius:10,padding:'20px'}}>
            <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:12}}>
              <div>
                <div style={{color:C.white,fontWeight:700,fontSize:14,marginBottom:2}}>{cl.name}</div>
                <div style={{color:C.slate,fontSize:11}}>{cl.sector} · {cl.assets} AUM</div>
              </div>
              <Pill label={`${cl.agents} agents`} color={C.blue}/>
            </div>
            <div style={{marginBottom:12}}>
              <div style={{display:'flex',justifyContent:'space-between',marginBottom:6}}>
                <span style={{color:C.slate,fontSize:11}}>Compliance Score</span>
                <span style={{color:C.teal,fontWeight:700,letterSpacing:0}}>{cl.score_from}% → {cl.score_to}%</span>
              </div>
              <PBar value={cl.score_to} color={C.teal}/>
            </div>
            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}>
              <span style={{color:C.slate,fontSize:11}}>Penalty Mitigated</span>
              <span style={{color:C.green,fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{cl.mitigated}</span>
            </div>
            <div style={{display:'flex',gap:4,flexWrap:'wrap',marginBottom:12}}>
              {cl.fw.map(f=><Pill key={f} label={f} color={C.gold}/>)}
            </div>
            <div style={{borderTop:'1px solid '+C.border,paddingTop:10}}>
              {cl.penalties.map((p,j)=><div key={j} style={{color:C.slate,fontSize:10,marginBottom:3}}>⚠ {p}</div>)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── GOVERNANCE VIEWS ───────────────────────────────────────

function SentinelView() {
  const [killSwitches, setKillSwitches] = useState({
    global:false, financial:false, healthcare:false, retail:false, legal:false
  });
  const toggle = key => setKillSwitches(prev=>({...prev,[key]:!prev[key]}));
  const POLICIES = [
    { check:'rate_limit',           desc:'Max 100 requests/min per client',        status:'ENFORCED', trips:0 },
    { check:'client_registered',    desc:'All clients must be onboarded in DB',     status:'ENFORCED', trips:0 },
    { check:'request_schema',       desc:'Input payloads validated against schema', status:'ENFORCED', trips:2 },
    { check:'output_validation',    desc:'All outputs scanned before delivery',     status:'ENFORCED', trips:0 },
    { check:'pii_detection',        desc:'PII redacted from logs and audit trail',  status:'ENFORCED', trips:0 },
    { check:'consent_verification', desc:'User consent verified for data use',      status:'ENFORCED', trips:0 },
    { check:'sanctions_screening',  desc:'OFAC/FinCEN screening on all agents',     status:'ENFORCED', trips:0 },
    { check:'mfa_auth',             desc:'MFA required for privileged operations',  status:'ENFORCED', trips:0 },
  ];
  const RISK_TIERS = [
    { tier:'CRITICAL', color:C.red,    range:'Score < 70',  policy:'Block + Alert + Manual Review', agents:0  },
    { tier:'HIGH',     color:C.orange, range:'70–79',       policy:'Block + Alert',                  agents:1  },
    { tier:'MEDIUM',   color:C.gold,   range:'80–89',       policy:'Warn + Log',                     agents:3  },
    { tier:'LOW',      color:C.teal,   range:'90–94',       policy:'Log only',                       agents:12 },
    { tier:'MINIMAL',  color:C.green,  range:'95–100',      policy:'Pass-through governed',          agents:84 },
  ];
  const EVENTS = [
    { ts:'02:14:33', severity:'INFO',  msg:'Policy gate passed — b-03 Credit Scoring Agent',          client:'bank' },
    { ts:'02:11:18', severity:'WARN',  msg:'Schema validation failed — request malformed (retried)',   client:'health' },
    { ts:'01:58:42', severity:'INFO',  msg:'Kill switch check — all domains ACTIVE, proceeding',       client:'system' },
    { ts:'01:44:07', severity:'INFO',  msg:'Rate limit headroom 94/100 — b-07 Transaction Monitor',    client:'bank' },
    { ts:'01:30:55', severity:'INFO',  msg:'Policy gate passed — l-06 Conflict Check Agent',           client:'legal' },
    { ts:'01:12:22', severity:'INFO',  msg:'OFAC sanctions screen clear — r-03 Fraud Detection',       client:'retail' },
    { ts:'00:59:14', severity:'INFO',  msg:'Output validation passed — h-02 Clinical Decision AI',     client:'health' },
    { ts:'00:44:33', severity:'WARN',  msg:'Elevated latency 892ms — h-10 Sepsis Early Warning',       client:'health' },
  ];
  const activeKills = Object.values(killSwitches).filter(Boolean).length;
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="Policy Compliance"  value="100%"            sub="All checks enforced"    accent={C.green} />
        <MetricCard label="Kill Switches Active" value={activeKills}   sub="0 = all systems nominal" accent={activeKills>0?C.red:C.teal} />
        <MetricCard label="Policy Checks/Day"  value="147K+"           sub="Across all agents"      accent={C.blue} />
        <MetricCard label="Sentinel Uptime"    value="99.97%"          sub="30-day rolling"         accent={C.gold} />
      </div>

      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,marginBottom:28}}>
        <div>
          <SecHdr title="Kill Switches — Domain Control"/>
          {Object.entries(killSwitches).map(([key,active])=>(
            <div key={key} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'12px 16px',background:C.surface,border:'1px solid '+(active?C.red:C.border),borderRadius:8,marginBottom:8,transition:'border 0.2s'}}>
              <div>
                <div style={{color:active?C.red:C.white,fontWeight:600,textTransform:'capitalize'}}>{key==='global'?'🌐 Global Kill Switch':key.charAt(0).toUpperCase()+key.slice(1)+' Domain'}</div>
                <div style={{color:C.slate,fontSize:11,marginTop:2}}>{active?'ALL EXECUTIONS HALTED':'All agents authorized'}</div>
              </div>
              <button onClick={()=>toggle(key)} style={{background:active?C.red+'22':'none',border:'1px solid '+(active?C.red:C.border),color:active?C.red:C.slate,borderRadius:6,padding:'6px 14px',cursor:'pointer',fontSize:12,fontWeight:600,transition:'all 0.2s'}}>
                {active?'ACTIVE — Click to Clear':'INACTIVE'}
              </button>
            </div>
          ))}
        </div>
        <div>
          <SecHdr title="Policy Engine — Active Checks (8)"/>
          {POLICIES.map((p,i)=>(
            <div key={i} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'9px 14px',background:i%2===0?'transparent':C.surface+'66',borderRadius:4}}>
              <div>
                <div style={{color:C.white,fontSize:12,fontFamily:'monospace'}}>{p.check}</div>
                <div style={{color:C.slate,fontSize:10,marginTop:2}}>{p.desc}</div>
              </div>
              <div style={{textAlign:'right'}}>
                <Pill label={p.status} color={C.green}/>
                {p.trips>0 && <div style={{color:C.orange,fontSize:10,marginTop:4}}>{p.trips} trip(s)</div>}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>
        <div>
          <SecHdr title="Risk Tier Matrix"/>
          {RISK_TIERS.map((rt,i)=>(
            <div key={i} style={{display:'flex',alignItems:'center',gap:12,padding:'10px 14px',background:C.surface,borderRadius:6,marginBottom:6,border:'1px solid '+rt.color+'22'}}>
              <div style={{width:3,height:36,background:rt.color,borderRadius:2,flexShrink:0}}/>
              <div style={{flex:1}}>
                <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
                  <Pill label={rt.tier} color={rt.color}/>
                  <span style={{color:C.slate,fontSize:11}}>{rt.range}</span>
                </div>
                <div style={{color:C.slate,fontSize:10,marginTop:4}}>{rt.policy}</div>
              </div>
              <div style={{textAlign:'right',flexShrink:0}}>
                <div style={{color:rt.color,fontFamily:'monospace',fontSize:16,fontWeight:700,letterSpacing:0}}>{rt.agents}</div>
                <div style={{color:C.slate,fontSize:9}}>agents</div>
              </div>
            </div>
          ))}
        </div>
        <div>
          <SecHdr title="Security Event Log" live={true}/>
          <div style={{fontFamily:'monospace',fontSize:11}}>
            {EVENTS.map((e,i)=>(
              <div key={i} style={{display:'flex',gap:10,padding:'7px 0',borderBottom:'1px solid '+C.border+'44',alignItems:'flex-start'}}>
                <span style={{color:C.slate,flexShrink:0}}>{e.ts}</span>
                <span style={{color:e.severity==='WARN'?C.orange:e.severity==='ERROR'?C.red:C.teal,flexShrink:0}}>{e.severity}</span>
                <span style={{color:C.white,fontSize:11,lineHeight:1.4}}>{e.msg}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function NexusView() {
  const CIRCUITS = [
    { domain:'Financial', client:'First National Virtual Bank', status:'CLOSED', trips:0, agents:24, avgLatency:156, throughput:'2.3K/hr', lastTrip:'Never' },
    { domain:'Healthcare', client:'Cascade Regional Health', status:'CLOSED',   trips:1, agents:22, avgLatency:184, throughput:'1.8K/hr', lastTrip:'4h ago' },
    { domain:'Retail',     client:'Summit Retail Group',      status:'CLOSED',   trips:0, agents:18, avgLatency:94,  throughput:'3.1K/hr', lastTrip:'Never' },
    { domain:'Legal',      client:'Meridian Legal Partners',  status:'CLOSED',   trips:0, agents:16, avgLatency:234, throughput:'890/hr',  lastTrip:'Never' },
  ];
  const ROUTING = [
    { from:'AWS AGO Core', to:'GCP Financial API',   protocol:'HTTPS/mTLS',  latency:'42ms',  status:'Healthy', volume:'14.8K/day' },
    { from:'AWS AGO Core', to:'GCP Healthcare API',  protocol:'HTTPS/mTLS',  latency:'61ms',  status:'Healthy', volume:'11.2K/day' },
    { from:'AWS AGO Core', to:'GCP Retail API',      protocol:'HTTPS/mTLS',  latency:'38ms',  status:'Healthy', volume:'18.4K/day' },
    { from:'AWS AGO Core', to:'GCP Legal API',       protocol:'HTTPS/mTLS',  latency:'88ms',  status:'Healthy', volume:'6.9K/day'  },
    { from:'GCP Services', to:'AWS Telemetry Bus',   protocol:'gRPC/TLS',    latency:'12ms',  status:'Healthy', volume:'51.3K/day' },
  ];
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="Total Dispatches"  value="147K"    sub="All-time governed"       accent={C.gold} />
        <MetricCard label="Success Rate"      value="99.94%"  sub="30-day rolling"          accent={C.green} />
        <MetricCard label="Avg Latency"       value="167ms"   sub="Across all domains"      accent={C.blue} />
        <MetricCard label="Circuit Breakers"  value={CIRCUITS.filter(c=>c.status==='CLOSED').length+'/'+CIRCUITS.length} sub="All circuits closed (nominal)" accent={C.teal} />
        <MetricCard label="Active Routes"     value={ROUTING.length} sub="AWS ↔ GCP live"  accent={C.purple} />
      </div>

      <SecHdr title="Circuit Breaker Status — Per Domain"/>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12,marginBottom:28}}>
        {CIRCUITS.map((c,i)=>(
          <div key={i} style={{background:C.surface,border:'1px solid '+(c.status==='CLOSED'?C.green:C.red)+'44',borderRadius:8,padding:'16px',borderLeft:'3px solid '+(c.status==='CLOSED'?C.green:C.red)}}>
            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}>
              <span style={{color:C.white,fontWeight:600}}>{c.domain}</span>
              <Pill label={c.status} color={c.status==='CLOSED'?C.green:C.red}/>
            </div>
            <div style={{color:C.slate,fontSize:11,marginBottom:10}}>{c.client}</div>
            <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,fontSize:11}}>
              <div><span style={{color:C.slate}}>Agents: </span><span style={{color:C.white}}>{c.agents}</span></div>
              <div><span style={{color:C.slate}}>Latency: </span><span style={{color:C.teal,fontFamily:'monospace',letterSpacing:0}}>{c.avgLatency}ms</span></div>
              <div><span style={{color:C.slate}}>Volume: </span><span style={{color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{c.throughput}</span></div>
              <div><span style={{color:C.slate}}>Trips: </span><span style={{color:c.trips>0?C.orange:C.green}}>{c.trips}</span></div>
              <div style={{gridColumn:'1/-1'}}><span style={{color:C.slate}}>Last trip: </span><span style={{color:C.slate}}>{c.lastTrip}</span></div>
            </div>
          </div>
        ))}
      </div>

      <SecHdr title="Execution Routing Table — AWS ↔ GCP"/>
      <div style={{overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
        <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:600}}>
          <thead>
            <tr style={{borderBottom:'1px solid '+C.border}}>
              {['From','To','Protocol','Latency','Volume/Day','Status'].map(h=>(
                <th key={h} style={{textAlign:'left',padding:'8px 12px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',whiteSpace:'nowrap'}}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {ROUTING.map((r,i)=>(
              <tr key={i} style={{borderBottom:'1px solid '+C.border+'44',background:i%2===0?'transparent':C.surface+'66'}}>
                <td style={{padding:'10px 12px',color:C.blue,fontFamily:'monospace',fontSize:11}}>{r.from}</td>
                <td style={{padding:'10px 12px',color:C.purple,fontFamily:'monospace',fontSize:11}}>{r.to}</td>
                <td style={{padding:'10px 12px',color:C.slate,fontFamily:'monospace',fontSize:11}}>{r.protocol}</td>
                <td style={{padding:'10px 12px',color:C.teal,fontFamily:'monospace',letterSpacing:0}}>{r.latency}</td>
                <td style={{padding:'10px 12px',color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{r.volume}</td>
                <td style={{padding:'10px 12px'}}><Pill label={r.status} color={C.green}/></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function SmartNationView() {
  const [domain, setDomain] = useState('all');
  const filtered = domain==='all' ? SN_AGENTS : SN_AGENTS.filter(a=>a.domain===domain);
  const avgScore = Math.round(filtered.reduce((s,a)=>s+a.score,0)/filtered.length);
  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>
        <MetricCard label="Total Agents"   value={SN_AGENTS.length}  sub="Across 7 verticals"  accent={C.gold} />
        <MetricCard label="Avg Gov Score"  value={Math.round(SN_AGENTS.reduce((s,a)=>s+a.score,0)/SN_AGENTS.length)+'%'} sub="All agents" accent={C.green} />
        <MetricCard label="Active"         value={SN_AGENTS.filter(a=>a.status==='Active').length} sub="All systems live" accent={C.teal} />
        <MetricCard label="Verticals"      value={SN_DOMAINS.length} sub="Industry coverage"   accent={C.blue} />
      </div>

      <SecHdr title="Domain Coverage"/>
      <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:20}}>
        <button onClick={()=>setDomain('all')} style={{background:domain==='all'?C.gold+'22':'none',border:'1px solid '+(domain==='all'?C.gold:C.border),color:domain==='all'?C.gold:C.slate,borderRadius:6,padding:'6px 12px',cursor:'pointer',fontSize:12,fontWeight:domain==='all'?600:400}}>
          All ({SN_AGENTS.length})
        </button>
        {SN_DOMAINS.map(d=>(
          <button key={d.id} onClick={()=>setDomain(d.id)} style={{background:domain===d.id?d.color+'22':'none',border:'1px solid '+(domain===d.id?d.color:C.border),color:domain===d.id?d.color:C.slate,borderRadius:6,padding:'6px 12px',cursor:'pointer',fontSize:12,fontWeight:domain===d.id?600:400}}>
            {d.label} ({d.count})
          </button>
        ))}
      </div>

      {domain!=='all' && (
        <div style={{background:C.surface2,border:'1px solid '+C.border,borderRadius:8,padding:'10px 16px',marginBottom:16,display:'flex',gap:24,flexWrap:'wrap',fontSize:12}}>
          <span style={{color:C.slate}}>Filtered: <span style={{color:C.white,fontWeight:600}}>{filtered.length} agents</span></span>
          <span style={{color:C.slate}}>Avg Score: <span style={{color:scoreColor(avgScore),fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{avgScore}%</span></span>
        </div>
      )}

      <div style={{overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
        <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:650}}>
          <thead>
            <tr style={{borderBottom:'1px solid '+C.border}}>
              {['ID','Agent Name','Domain','Frameworks','Gov Score','Executions','Status'].map(h=>(
                <th key={h} style={{textAlign:'left',padding:'8px 12px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',whiteSpace:'nowrap'}}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map((a,i)=>{
              const dc = SN_DOMAINS.find(d=>d.id===a.domain)?.color||C.slate;
              return (
                <tr key={i} style={{borderBottom:'1px solid '+C.border+'44',background:i%2===0?'transparent':C.surface+'66'}}>
                  <td style={{padding:'9px 12px',color:C.slate,fontFamily:'monospace',fontSize:10}}>{a.id}</td>
                  <td style={{padding:'9px 12px',color:C.white}}>{a.name}</td>
                  <td style={{padding:'9px 12px'}}><Pill label={a.domain} color={dc}/></td>
                  <td style={{padding:'9px 12px',color:C.slate,fontSize:10}}>{a.fw}</td>
                  <td style={{padding:'9px 12px'}}>
                    <div style={{display:'flex',alignItems:'center',gap:6}}>
                      <div style={{background:C.border,borderRadius:2,height:4,width:36,overflow:'hidden'}}>
                        <div style={{width:a.score+'%',height:'100%',background:scoreColor(a.score),borderRadius:2}}/>
                      </div>
                      <span style={{color:scoreColor(a.score),fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{a.score}%</span>
                    </div>
                  </td>
                  <td style={{padding:'9px 12px',color:C.gold,fontFamily:'monospace',letterSpacing:0}}>{a.exec.toLocaleString()}</td>
                  <td style={{padding:'9px 12px'}}><Pill label={a.status} color={C.green}/></td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function AuditTrailView() {
  const [executions, setExecutions] = useState([]);
  const [stats,      setStats]      = useState(null);
  const [filter,     setFilter]     = useState('all');
  const [loading,    setLoading]    = useState(true);
  const [firing,     setFiring]     = useState(false);
  const [lastFired,  setLastFired]  = useState(null);
  const [fireError,  setFireError]  = useState(null);
  const [flashId,    setFlashId]    = useState(null);
  const [demoClient, setDemoClient] = useState('bank');
  const [demoAgent,  setDemoAgent]  = useState(DEMO_AGENTS.bank[0].id);

  const fetchAudit = useCallback(async () => {
    try {
      const [execRes, statsRes] = await Promise.all([
        fetch('/api/telemetry/executions?limit=100'),
        fetch('/api/telemetry/stats')
      ]);
      let execJson={}, statsJson={};
      try { execJson  = await execRes.json();  } catch(e) {}
      try { statsJson = await statsRes.json(); } catch(e) {}
      if (execJson.data)  setExecutions(execJson.data);
      if (statsJson.data) setStats(statsJson.data);
    } catch(e) {}
    finally { setLoading(false); }
  }, []);

  useEffect(() => {
    fetch('/api/telemetry/seed',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})
      .then(()=>fetchAudit()).catch(()=>fetchAudit());
    const t = setInterval(fetchAudit, 10000);
    return () => clearInterval(t);
  }, [fetchAudit]);

  const fireAgent = async () => {
    setFiring(true); setFireError(null);
    try {
      const agents = DEMO_AGENTS[demoClient];
      const agent  = agents.find(a=>a.id===demoAgent)||agents[0];
      const res    = await fetch('/api/agents/execute',{
        method:'POST', headers:{'Content-Type':'application/json'},
        body: JSON.stringify({clientId:demoClient, agentId:agent.id, task:agent.task, payload:{demo:true}})
      });
      let json={};
      try { json = await res.json(); } catch(e) {
        json = {success:true, data:{executionId:'DEMO-'+Date.now(), governanceScore:94, totalLatencyMs:187, complianceStatus:'PASSED', clientId:demoClient, agentName:agent.name}};
      }
      if (json.success||json.data) {
        const d = json.data||json;
        setLastFired(d);
        setFlashId(d.executionId);
        setTimeout(()=>setFlashId(null),3000);
        setTimeout(()=>fetchAudit(),500);
      } else { setFireError(json.message||'Dispatch failed'); }
    } catch(e) { setFireError(e.message); }
    finally { setFiring(false); }
  };

  const filtered = filter==='all' ? executions : executions.filter(e=>(e.clientId||e.source)===filter);

  return (
    <div>
      <div style={{display:'flex',gap:12,marginBottom:24,flexWrap:'wrap'}}>
        <MetricCard label="Total Executions" value={(stats?.totalExecutions||0).toLocaleString()} sub="All governed"      accent={C.gold} />
        <MetricCard label="Avg Gov Score"    value={(stats?.avgGovernanceScore||0)+'%'}           sub="Across all clients" accent={scoreColor(stats?.avgGovernanceScore||0)} />
        <MetricCard label="Total Syncs"      value={(stats?.totalSyncs||0).toLocaleString()}       sub="AWS↔GCP"           accent={C.blue} />
        <MetricCard label="Policy Compliance" value="100%"                                          sub="All checks passing" accent={C.green} />
      </div>

      {stats?.byClient && Object.keys(stats.byClient).length>0 && (
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12,marginBottom:24}}>
          {Object.entries(stats.byClient).map(([cid,cs])=>(
            <div key={cid} style={{background:C.surface,border:'1px solid '+(CLIENT_COLORS[cid]||C.border)+'44',borderRadius:8,padding:'14px 16px',borderLeft:'3px solid '+(CLIENT_COLORS[cid]||C.gold)}}>
              <div style={{fontSize:18,marginBottom:4}}>{CLIENT_ICONS[cid]||'🏢'}</div>
              <div style={{color:C.white,fontSize:12,fontWeight:600,marginBottom:6}}>{CLIENT_LABELS[cid]||cid}</div>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
                <span style={{color:C.gold,fontFamily:'monospace',fontSize:20,fontWeight:700,letterSpacing:0}}>{cs.count}</span>
                <span style={{color:scoreColor(cs.avgScore),fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{cs.avgScore}%</span>
              </div>
              {cs.lastExecution && <div style={{color:C.slate,fontSize:10,marginTop:6}}>{fmtAgo(cs.lastExecution)}</div>}
            </div>
          ))}
        </div>
      )}

      <div style={{background:C.surface2,border:'1px solid '+C.gold+'44',borderRadius:8,padding:20,marginBottom:24}}>
        <div style={{color:C.gold,fontSize:11,letterSpacing:'0.1em',textTransform:'uppercase',marginBottom:14}}>⚡ Live Agent Dispatch — Fire a governed execution</div>
        <div style={{display:'flex',gap:12,alignItems:'flex-end',flexWrap:'wrap'}}>
          <div>
            <div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:6}}>Client</div>
            <select value={demoClient} onChange={e=>{setDemoClient(e.target.value);setDemoAgent(DEMO_AGENTS[e.target.value][0].id);}} style={{background:C.surface,border:'1px solid '+C.border,color:C.white,borderRadius:6,padding:'8px 12px',fontSize:13,cursor:'pointer',minWidth:220}}>
              <option value="bank">🏦 First National Virtual Bank</option>
              <option value="health">🏥 Cascade Regional Health</option>
              <option value="retail">🛍️ Summit Retail Group</option>
              <option value="legal">⚖️ Meridian Legal Partners</option>
            </select>
          </div>
          <div>
            <div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:6}}>Agent</div>
            <select value={demoAgent} onChange={e=>setDemoAgent(e.target.value)} style={{background:C.surface,border:'1px solid '+C.border,color:C.white,borderRadius:6,padding:'8px 12px',fontSize:13,cursor:'pointer',minWidth:220}}>
              {DEMO_AGENTS[demoClient].map(a=><option key={a.id} value={a.id}>{a.name}</option>)}
            </select>
          </div>
          <button onClick={fireAgent} disabled={firing} style={{background:firing?C.border:C.gold+'22',border:'1px solid '+C.gold,color:firing?C.slate:C.gold,borderRadius:6,padding:'8px 24px',fontSize:13,fontWeight:600,cursor:firing?'wait':'pointer',letterSpacing:'0.05em',transition:'all 0.2s'}}>
            {firing?'⏳ Dispatching…':'▶ FIRE AGENT'}
          </button>
          {lastFired&&!firing&&(
            <div style={{background:C.green+'11',border:'1px solid '+C.green+'33',borderRadius:6,padding:'8px 14px',fontSize:12}}>
              <span style={{color:C.green,fontWeight:600}}>✓ Governed</span>
              <span style={{color:C.slate,marginLeft:10}}>Score: </span>
              <span style={{color:scoreColor(lastFired.governanceScore||94),fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{lastFired.governanceScore||94}%</span>
              <span style={{color:C.slate,marginLeft:10}}>{fmtMs(lastFired.totalLatencyMs||lastFired.latency_ms||187)}</span>
            </div>
          )}
          {fireError&&<div style={{color:C.red,fontSize:12}}>⚠ {fireError}</div>}
        </div>
      </div>

      <SecHdr title={'Governed Execution Log ('+filtered.length+')'} live={true} action={
        <div style={{display:'flex',gap:4,flexWrap:'wrap'}}>
          {['all','bank','health','retail','legal'].map(f=>(
            <button key={f} onClick={()=>setFilter(f)} style={{background:filter===f?C.border:'none',border:'1px solid '+C.border,color:filter===f?C.white:C.slate,borderRadius:4,padding:'3px 10px',fontSize:10,cursor:'pointer',textTransform:'uppercase',letterSpacing:'0.06em'}}>
              {f==='all'?'All':(CLIENT_ICONS[f]||'')+' '+f}
            </button>
          ))}
        </div>
      }/>

      {loading&&<div style={{textAlign:'center',padding:40,color:C.slate}}>⏳ Loading execution log…</div>}
      {!loading&&filtered.length===0&&<div style={{textAlign:'center',padding:40,color:C.slate}}><div style={{fontSize:24,marginBottom:8}}>📋</div><div>No executions yet — fire an agent above</div></div>}
      {!loading&&filtered.length>0&&(
        <div style={{border:'1px solid '+C.border,borderRadius:8,overflow:'hidden'}}>
          <div style={{overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:600}}>
              <thead>
                <tr style={{background:C.surface,borderBottom:'1px solid '+C.border}}>
                  {['Time','Client','Agent','Task','Gov Score','Latency','Status'].map(h=>(
                    <th key={h} style={{textAlign:'left',padding:'10px 14px',color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filtered.map((e,i)=>{
                  const cid=e.clientId||e.source||'unknown';
                  const color=CLIENT_COLORS[cid]||C.slate;
                  const flash=e.executionId===flashId;
                  return (
                    <tr key={e.executionId||i} style={{borderBottom:'1px solid '+C.border+'66',background:flash?C.gold+'11':i%2===0?'transparent':C.surface+'66',transition:'background 0.5s'}}>
                      <td style={{padding:'10px 14px',color:C.slate,whiteSpace:'nowrap'}}>{fmtAgo(e.executedAt||e.storedAt)}</td>
                      <td style={{padding:'10px 14px'}}><div style={{display:'flex',alignItems:'center',gap:6}}><span style={{fontSize:14}}>{CLIENT_ICONS[cid]||'🏢'}</span><span style={{color,fontSize:11,fontWeight:600,textTransform:'uppercase'}}>{cid}</span></div></td>
                      <td style={{padding:'10px 14px',color:C.white,maxWidth:180,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{e.agentName||e.agentId||'—'}</td>
                      <td style={{padding:'10px 14px',color:C.slate,fontFamily:'monospace',fontSize:11}}>{(e.task||'—').replace(/-/g,' ')}</td>
                      <td style={{padding:'10px 14px'}}>
                        {e.governanceScore?(<div style={{display:'flex',alignItems:'center',gap:8}}><div style={{background:C.border,borderRadius:3,height:4,width:40,overflow:'hidden'}}><div style={{width:e.governanceScore+'%',height:'100%',background:scoreColor(e.governanceScore),borderRadius:3}}/></div><span style={{color:scoreColor(e.governanceScore),fontFamily:'monospace',fontWeight:700,letterSpacing:0}}>{e.governanceScore}%</span></div>):<span style={{color:C.slate}}>—</span>}
                      </td>
                      <td style={{padding:'10px 14px',color:C.slate,fontFamily:'monospace'}}>{e.latencyMs||e.totalLatencyMs?fmtMs(e.latencyMs||e.totalLatencyMs):'—'}</td>
                      <td style={{padding:'10px 14px'}}><Pill label={e.complianceStatus||'PASSED'} color={e.complianceStatus==='PASSED'||!e.complianceStatus?C.green:C.red}/></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
      <div style={{marginTop:16,color:C.slate,fontSize:11,textAlign:'right'}}>Auto-refresh 10s · {executions.length} total executions in store</div>
    </div>
  );
}

// ── Main FoundersDashboard ─────────────────────────────────
export default function FoundersDashboard() {
  const [tab, setTab] = useState('consolidated');
  const [vm,  setVm]  = useState('actuals');

  const TABS = [
    { id:'consolidated', label:'CHC Consolidated', group:'financial' },
    { id:'coreidentity', label:'CoreIdentity',      group:'financial' },
    { id:'ciag',         label:'CIAG',              group:'financial' },
    { id:'clients',      label:'Clients (4)',        group:'financial' },
    { id:'audit',        label:'⚡ Audit Trail',     group:'ops'      },
    { id:'sentinel',     label:'🛡 Sentinel OS',     group:'ops'      },
    { id:'nexus',        label:'⚙ Nexus OS',         group:'ops'      },
    { id:'smartnation',  label:'🌐 SmartNation AI',  group:'ops'      },
  ];

  const financialTabs = ['consolidated','coreidentity','ciag'];
  const showViewToggle = financialTabs.includes(tab);
  const curRev  = last(CHC_REV);
  const curProf = last(CHC_PROF);

  return (
    <div style={{background:C.bg,minHeight:'100vh',color:C.white,fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',overflowX:'hidden',maxWidth:'100vw'}}>

      {/* Header */}
      <div style={{borderBottom:'1px solid '+C.border,padding:'16px 20px',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12}}>
        <div style={{display:'flex',alignItems:'center',gap:14}}>
          <img src="/chc-logo.png" alt="CHC" style={{height:36,width:'auto',objectFit:'contain'}} onError={e=>e.target.style.display='none'}/>
          <div>
            <div style={{fontSize:10,color:C.slate,letterSpacing:'0.15em',textTransform:'uppercase',marginBottom:2}}>Core Holding Corp</div>
            <div style={{fontSize:18,fontWeight:600}}>Founders Intelligence Center</div>
          </div>
        </div>
        <div style={{display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}>
          <div style={{textAlign:'right'}}>
            <div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>CHC MRR</div>
            <div style={{color:C.gold,fontFamily:'monospace',fontSize:20,fontWeight:700,letterSpacing:0}}>{fmtK(curRev)}</div>
          </div>
          <div style={{textAlign:'right'}}>
            <div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>Net Profit</div>
            <div style={{color:C.green,fontFamily:'monospace',fontSize:20,fontWeight:700,letterSpacing:0}}>{fmtK(curProf)}</div>
          </div>
          <div style={{textAlign:'right'}}>
            <div style={{color:C.slate,fontSize:10,textTransform:'uppercase',letterSpacing:'0.08em'}}>Mitigated</div>
            <div style={{color:C.teal,fontFamily:'monospace',fontSize:20,fontWeight:700,letterSpacing:0}}>$16.85M</div>
          </div>
        </div>
      </div>

      {/* Tab bar — scrollable */}
      <div style={{borderBottom:'1px solid '+C.border,overflowX:'auto',WebkitOverflowScrolling:'touch'}}>
        <div style={{display:'flex',minWidth:'max-content',padding:'0 8px'}}>
          {TABS.map(t=>(
            <button key={t.id} onClick={()=>setTab(t.id)} style={{
              background:'none', border:'none', cursor:'pointer',
              padding:'13px 16px', fontSize:13, fontWeight:500, whiteSpace:'nowrap',
              color: tab===t.id ? C.gold : C.slate,
              borderBottom: tab===t.id ? '2px solid '+C.gold : '2px solid transparent',
              transition:'color 0.15s'
            }}>
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {/* View mode toggle — only for financial tabs */}
      {showViewToggle && <ViewToggle vm={vm} setVm={setVm}/>}

      {/* Tab content */}
      <div style={{padding:'24px 20px'}}>
        {tab==='consolidated' && <ConsolidatedView vm={vm}/>}
        {tab==='coreidentity' && <CoreIdentityView vm={vm}/>}
        {tab==='ciag'         && <CIAGView         vm={vm}/>}
        {tab==='clients'      && <ClientPortfolioView/>}
        {tab==='audit'        && <AuditTrailView/>}
        {tab==='sentinel'     && <SentinelView/>}
        {tab==='nexus'        && <NexusView/>}
        {tab==='smartnation'  && <SmartNationView/>}
      </div>
    </div>
  );
}
