// Nav.jsx — Mobile-responsive navigation
// Auto-generated by Script 25-F — DO NOT hand edit
import { useState } from 'react';
import { C, F, useWindowWidth } from '../chc-design.js';

const LINKS = [
  ['#/demo','Live Demo'],
  ['#/pricing','Pricing'],
  ['#/docs','API Docs'],
  ['#/investor','Investors'],
];

export default function Nav({ route }) {
  const w = useWindowWidth();
  const isMobile = w < 768;
  const [open, setOpen] = useState(false);

  const linkStyle = (h) => ({
    color: route === h.slice(1) ? C.gold : C.slate,
    textDecoration: 'none',
    padding: '8px 14px',
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    background: route === h.slice(1) ? C.gold+'11' : 'none',
    border: route === h.slice(1) ? '1px solid '+C.gold+'33' : '1px solid transparent',
    display: 'block',
  });

  return (
    <>
      <nav style={{
        background: C.bg+'f0', backdropFilter: 'blur(12px)',
        borderBottom: '1px solid '+C.border,
        padding: isMobile ? '0 16px' : '0 40px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        height: 60, position: 'sticky', top: 0, zIndex: 100,
        fontFamily: F.body,
      }}>
        {/* Logo */}
        <a href="#/" style={{ textDecoration:'none', display:'flex', alignItems:'center', gap:10, flexShrink:0 }}>
          <div style={{ width:28, height:28, background:C.gold, borderRadius:4,
            display:'flex', alignItems:'center', justifyContent:'center',
            fontSize:14, fontWeight:700, color:C.bg, flexShrink:0 }}>C</div>
          {!isMobile && (
            <div>
              <div style={{ color:C.white, fontFamily:F.display, fontSize:16, letterSpacing:'0.08em' }}>COREIDENTITY</div>
              <div style={{ color:C.slate, fontSize:9, letterSpacing:'0.15em', textTransform:'uppercase', marginTop:-2 }}>by Core Holding Corp</div>
            </div>
          )}
          {isMobile && (
            <div style={{ color:C.white, fontFamily:F.display, fontSize:15, letterSpacing:'0.08em' }}>COREIDENTITY</div>
          )}
        </a>

        {/* Desktop nav links */}
        {!isMobile && (
          <div style={{ display:'flex', gap:4, alignItems:'center' }}>
            {LINKS.map(([h,l]) => (
              <a key={h} href={h} style={linkStyle(h)}>{l}</a>
            ))}
          </div>
        )}

        {/* Right side */}
        <div style={{ display:'flex', alignItems:'center', gap:8 }}>
          {!isMobile && (
            <a href="#/onboard" style={{
              background:C.gold, color:C.bg, textDecoration:'none',
              padding:'9px 20px', borderRadius:6, fontSize:13, fontWeight:700,
              letterSpacing:'0.04em', flexShrink:0,
            }}>Free Assessment →</a>
          )}
          {isMobile && (
            <button onClick={() => setOpen(o => !o)} style={{
              background:'none', border:'1px solid '+C.border,
              color:C.white, borderRadius:6, padding:'8px 12px',
              cursor:'pointer', fontSize:18, lineHeight:1,
            }}>{open ? '✕' : '☰'}</button>
          )}
        </div>
      </nav>

      {/* Mobile drawer */}
      {isMobile && open && (
        <div style={{
          position:'fixed', top:60, left:0, right:0, zIndex:99,
          background:C.bg2, borderBottom:'1px solid '+C.border,
          padding:'12px 16px', display:'flex', flexDirection:'column', gap:4,
        }}>
          {LINKS.map(([h,l]) => (
            <a key={h} href={h} onClick={() => setOpen(false)} style={{
              ...linkStyle(h), padding:'12px 16px', fontSize:15,
            }}>{l}</a>
          ))}
          <a href="#/onboard" onClick={() => setOpen(false)} style={{
            display:'block', marginTop:8, background:C.gold, color:C.bg,
            textDecoration:'none', padding:'12px 16px', borderRadius:6,
            fontSize:15, fontWeight:700, letterSpacing:'0.04em', textAlign:'center',
          }}>Free Assessment →</a>
          <a href="#/dashboard" onClick={() => setOpen(false)} style={{
            display:'block', marginTop:4, background:'none', color:C.slate,
            textDecoration:'none', padding:'10px 16px', borderRadius:6,
            fontSize:13, textAlign:'center', border:'1px solid '+C.border,
          }}>Founders Dashboard</a>
        </div>
      )}
    </>
  );
}
