// Auto-generated by Script 18 v2 — DO NOT hand edit
// Generated: 2026-02-26T22:28:27Z
module.exports = {
  gcpVirtualBank: {
    baseUrl: 'https://chc-virtual-bank-554248182051.us-central1.run.app',
    apiKey: 'chc-bank-dev-key-2026',
    name: 'First National Virtual Bank',
    vertical: 'financial_services',
    timeout: 10000,
    retryAttempts: 3,
    endpoints: {
      health:      '/health',
      bank:        '/api/bank',
      customers:   '/api/customers',
      transactions:'/api/transactions',
      compliance:  '/api/compliance',
      audit:       '/api/audit',
      stressTest:  '/api/stress-test',
      register:    '/api/governance/register'
    }
  }
};
