// Auto-generated by Script 29 — DO NOT hand edit
module.exports = {
  gcpVirtualBank: {
    baseUrl: 'https://chc-virtual-bank-lvuq2yqbma-uc.a.run.app',
    apiKey: 'chc-bank-dev-key-2026',
    name: 'First National Virtual Bank',
    vertical: 'financial_services',
    timeout: 10000, retryAttempts: 3,
    endpoints: { health:"/health", bank:"/api/bank", customers:"/api/customers",
      transactions:"/api/transactions", compliance:"/api/compliance",
      audit:"/api/audit", stressTest:"/api/stress-test", register:"/api/governance/register" }
  },
  chcHealthNetwork: {
    baseUrl: 'https://chc-health-network-lvuq2yqbma-uc.a.run.app',
    apiKey: 'chc-health-dev-key-2026',
    name: 'Regional Health Network', vertical: 'healthcare',
    timeout: 10000, retryAttempts: 3,
    endpoints: { health:"/health", hospital:"/api/hospital", patients:"/api/patients",
      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }
  },
  chcLegalPartners: {
    baseUrl: 'https://chc-legal-partners-lvuq2yqbma-uc.a.run.app',
    apiKey: 'chc-legal-dev-key-2026',
    name: 'Legal Partners Group', vertical: 'legal',
    timeout: 10000, retryAttempts: 3,
    endpoints: { health:"/health", firm:"/api/firm", cases:"/api/cases",
      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }
  },
  chcRetailGroup: {
    baseUrl: 'https://chc-retail-group-lvuq2yqbma-uc.a.run.app',
    apiKey: 'chc-retail-dev-key-2026',
    name: 'Metro Retail Group', vertical: 'retail',
    timeout: 10000, retryAttempts: 3,
    endpoints: { health:"/health", store:"/api/store", inventory:"/api/inventory",
      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }
  }
};