#!/usr/bin/env node
/**
 * Script 27 — Portal Mobile Nav Restore
 * ───────────────────────────────────────
 * Replaces the desktop-only sidebar with a mobile-first
 * sticky top nav + hamburger drawer — matching the original
 * Nav.jsx pattern exactly, adapted for portal sections.
 *
 * Idempotent · Zero hand edits · Ends with npm run build
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const REPO = path.join(process.env.HOME, 'coreidentity-dashboard');
const run = (cmd) => { console.log(`  $ ${cmd.slice(0,100)}`); execSync(cmd, { cwd: REPO, stdio: 'inherit' }); };
const wf  = (rel, c) => { fs.writeFileSync(path.join(REPO, rel), c, 'utf8'); console.log(`  ✓ wrote ${rel}`); };

// ── Step 1: Write PortalNav.jsx ──────────────────────────────
console.log('\n── Step 1: Write PortalNav.jsx ──────────────────────────────');

const portalNav = `// PortalNav.jsx — Mobile-responsive portal navigation
// Auto-generated by Script 27 — DO NOT hand edit
import { useState } from 'react';
import { C, F, useWindowWidth } from '../chc-design.js';

const NAV_SECTIONS = [
  ['/#/dashboard',   '🏛',  'Founders'],
  ['/#/agents',      '🤖',  'Agents'],
  ['/#/sentinel',    '🛡',  'Sentinel OS'],
  ['/#/nexus',       '⚡',  'Nexus OS'],
  ['/#/smartnation', '🌐',  'SmartNation AI'],
  ['/#/governance',  '📋',  'Governance'],
  ['/#/workflows',   '🔄',  'Workflows'],
  ['/#/analytics',   '📊',  'Analytics'],
  ['/#/settings',    '⚙',   'Settings'],
];

export default function PortalNav({ route, onNavigate, userEmail, onLogout }) {
  const w = useWindowWidth();
  const isMobile = w < 900;
  const [open, setOpen] = useState(false);

  const isActive = (h) => route === h.replace('/#', '/#');

  const linkStyle = (h) => ({
    color: isActive(h) ? C.gold : C.slate,
    textDecoration: 'none',
    padding: isMobile ? '14px 16px' : '6px 12px',
    borderRadius: 6,
    fontSize: isMobile ? 15 : 13,
    fontWeight: isActive(h) ? 600 : 400,
    background: isActive(h) ? C.gold + '15' : 'none',
    border: isActive(h) ? '1px solid ' + C.gold + '33' : '1px solid transparent',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  });

  const navigate = (h) => {
    window.location.hash = h.replace('/#', '#');
    if (onNavigate) onNavigate(h);
    setOpen(false);
  };

  return (
    <>
      {/* Sticky top nav bar */}
      <nav style={{
        background: C.bg + 'f2',
        backdropFilter: 'blur(12px)',
        borderBottom: '1px solid ' + C.border,
        padding: isMobile ? '0 16px' : '0 24px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: 56,
        position: 'sticky',
        top: 0,
        zIndex: 100,
        fontFamily: F.body,
        gap: 16,
      }}>
        {/* Logo + wordmark */}
        <button
          onClick={() => navigate('/#/dashboard')}
          style={{
            background: 'none', border: 'none', cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0, padding: 0,
          }}
        >
          <img
            src="/chc-logo.png"
            alt="CHC"
            style={{ width: 28, height: 28, objectFit: 'contain', background: 'transparent' }}
          />
          <div>
            <div style={{ color: C.white, fontFamily: F.display, fontSize: 13, letterSpacing: '0.08em', lineHeight: 1.1 }}>
              CORE HOLDING CORP
            </div>
            <div style={{ color: C.gold, fontSize: 10, letterSpacing: '0.12em', textTransform: 'uppercase', lineHeight: 1.1 }}>
              Governance Portal
            </div>
          </div>
        </button>

        {/* Desktop inline nav links */}
        {!isMobile && (
          <div style={{ display: 'flex', gap: 2, alignItems: 'center', flex: 1, justifyContent: 'center', flexWrap: 'nowrap', overflow: 'hidden' }}>
            {NAV_SECTIONS.map(([h, icon, label]) => (
              <button
                key={h}
                onClick={() => navigate(h)}
                style={linkStyle(h)}
              >
                <span style={{ fontSize: 14 }}>{icon}</span>
                <span>{label}</span>
              </button>
            ))}
          </div>
        )}

        {/* Right side */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
          {!isMobile && (
            <button
              onClick={onLogout}
              style={{
                background: 'none',
                border: '1px solid ' + C.border,
                color: C.slate,
                borderRadius: 6,
                padding: '6px 12px',
                cursor: 'pointer',
                fontSize: 12,
                fontFamily: F.body,
              }}
            >
              Sign out
            </button>
          )}
          {isMobile && (
            <button
              onClick={() => setOpen(o => !o)}
              style={{
                background: 'none',
                border: '1px solid ' + C.border,
                color: C.white,
                borderRadius: 6,
                padding: '8px 12px',
                cursor: 'pointer',
                fontSize: 18,
                lineHeight: 1,
              }}
            >
              {open ? '✕' : '☰'}
            </button>
          )}
        </div>
      </nav>

      {/* Mobile drawer */}
      {isMobile && open && (
        <div style={{
          position: 'fixed',
          top: 56,
          left: 0,
          right: 0,
          bottom: 0,
          zIndex: 99,
          background: C.bg2 || '#111118',
          borderTop: '1px solid ' + C.border,
          padding: '8px 12px',
          display: 'flex',
          flexDirection: 'column',
          gap: 2,
          overflowY: 'auto',
        }}>
          {NAV_SECTIONS.map(([h, icon, label]) => (
            <button
              key={h}
              onClick={() => navigate(h)}
              style={{
                ...linkStyle(h),
                padding: '14px 16px',
                fontSize: 15,
                borderRadius: 8,
              }}
            >
              <span style={{ fontSize: 18, width: 24, textAlign: 'center' }}>{icon}</span>
              <span>{label}</span>
            </button>
          ))}

          {/* Divider + user info + sign out */}
          <div style={{ borderTop: '1px solid ' + C.border, marginTop: 8, paddingTop: 12 }}>
            {userEmail && (
              <div style={{ color: C.slate, fontSize: 12, padding: '4px 16px', marginBottom: 8 }}>
                {userEmail}
              </div>
            )}
            <button
              onClick={() => { setOpen(false); onLogout(); }}
              style={{
                display: 'block',
                width: '100%',
                padding: '12px 16px',
                background: 'none',
                border: '1px solid ' + C.border,
                borderRadius: 8,
                color: '#ef4444',
                fontSize: 14,
                cursor: 'pointer',
                fontFamily: F.body,
                textAlign: 'left',
              }}
            >
              Sign out
            </button>
          </div>
        </div>
      )}
    </>
  );
}
`;

wf('src/components/PortalNav.jsx', portalNav);

// ── Step 2: Rewrite App.jsx to use PortalNav ─────────────────
console.log('\n── Step 2: Rewrite App.jsx with PortalNav ───────────────────');

const newApp = `// App.jsx — CoreIdentity Governance Portal
// Auto-generated by Script 27 — DO NOT hand edit
import React, { useState, useEffect, createContext, useContext } from 'react';
import { useAuth } from './context/AuthContext';
import { injectFonts } from './chc-design.js';
import PortalNav from './components/PortalNav.jsx';
import LoginPage from './pages/LoginPage.jsx';

// ── Page imports ──────────────────────────────────────────────
import FoundersDashboard from './pages/FoundersDashboard.jsx';
import AgentCatalog      from './pages/AgentCatalog.jsx';
import Sentinel          from './pages/Sentinel.jsx';
import NexusOS           from './pages/NexusOS.jsx';
import SmartNation       from './pages/SmartNation.jsx';
import Governance        from './pages/Governance.jsx';
import Workflows         from './pages/Workflows.jsx';
import Analytics         from './pages/Analytics.jsx';
import SettingsPage      from './pages/SettingsPage.jsx';
import MarketingPage     from './pages/MarketingPage.jsx';
import DemoPage          from './pages/DemoPage.jsx';
import OnboardPage       from './pages/OnboardPage.jsx';
import InvestorPage      from './pages/InvestorPage.jsx';
import PricingPage       from './pages/PricingPage.jsx';
import ReportsPage       from './pages/ReportsPage.jsx';
import DocsPage          from './pages/DocsPage.jsx';

// ── Notifications context ─────────────────────────────────────
const NotificationContext = createContext({ notifications: [], addNotification: () => {} });
export const useNotifications = () => useContext(NotificationContext);

// ── Route maps ────────────────────────────────────────────────
const PORTAL_PAGES = {
  '/#/dashboard':   FoundersDashboard,
  '/#/agents':      AgentCatalog,
  '/#/sentinel':    Sentinel,
  '/#/nexus':       NexusOS,
  '/#/smartnation': SmartNation,
  '/#/governance':  Governance,
  '/#/workflows':   Workflows,
  '/#/analytics':   Analytics,
  '/#/settings':    SettingsPage,
};

const PUBLIC_PAGES = {
  '/':           MarketingPage,
  '/#/demo':     DemoPage,
  '/#/onboard':  OnboardPage,
  '/#/investor': InvestorPage,
  '/#/pricing':  PricingPage,
  '/#/reports':  ReportsPage,
  '/#/docs':     DocsPage,
};

const PUBLIC_ROUTES = new Set(Object.keys(PUBLIC_PAGES));

function isPortalDomain() {
  return window.location.hostname === 'portal.coreholdingcorp.com';
}

function getRoute() {
  const hash = window.location.hash || '';
  const route = (!hash || hash === '#') ? '/' : '/#' + hash.slice(1);
  // On portal domain, redirect root to dashboard
  if (route === '/' && isPortalDomain()) {
    window.location.replace('/#/dashboard');
    return '/#/dashboard';
  }
  return route;
}

// ── Root app ──────────────────────────────────────────────────
export default function App() {
  const { user, loading, logout } = useAuth();
  const [route, setRoute] = useState(getRoute);

  useEffect(() => {
    injectFonts();
    const onHash = () => setRoute(getRoute());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  if (loading) {
    return (
      <div style={{ minHeight:'100vh', background:'#070c18', display:'flex', alignItems:'center', justifyContent:'center' }}>
        <div style={{ color:'#d4af37', fontSize:14, fontFamily:'system-ui' }}>Loading…</div>
      </div>
    );
  }

  // Public/marketing routes
  if (PUBLIC_ROUTES.has(route)) {
    const Page = PUBLIC_PAGES[route] || MarketingPage;
    return <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}><Page /></div>;
  }

  // Portal routes — require auth
  if (!user) return <LoginPage />;

  const Page = PORTAL_PAGES[route] || FoundersDashboard;

  return (
    <NotificationContext.Provider value={{ notifications: [], addNotification: () => {} }}>
      <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}>
        <PortalNav
          route={route}
          onNavigate={setRoute}
          userEmail={user?.email}
          onLogout={logout}
        />
        <Page />
      </div>
    </NotificationContext.Provider>
  );
}
`;

wf('src/App.jsx', newApp);

// ── Step 3: Build gate ────────────────────────────────────────
console.log('\n── Step 3: Build gate ───────────────────────────────────────');
run('node scripts/api_preflight_audit.mjs 2>/dev/null || true');
run('npm run build');

// ── Step 4: Commit and push ───────────────────────────────────
console.log('\n── Step 4: Commit and push ──────────────────────────────────');
run('git add -A');
const dirty = execSync('git status --porcelain', { cwd: REPO }).toString().trim();
if (dirty) {
  run('git commit -m "feat: Script 27 — restore mobile-first portal nav (sticky top + hamburger drawer)"');
  run('git push origin main');
  console.log('\n  ✓ Pushed — Cloudflare Pages deploying');
} else {
  console.log('  ✓ Already clean');
}

console.log(`
============================================================
 Script 27 Complete — Mobile Nav Restored

 Changes:
   ✓ PortalNav.jsx — sticky top bar + hamburger drawer
   ✓ Mobile: hamburger → full-screen drawer with all 9 sections
   ✓ Desktop: inline nav links in top bar
   ✓ App.jsx — clean routing, no sidebar
   ✓ Matches original Nav.jsx mobile pattern exactly
   ✓ CHC logo, gold "Governance Portal" wordmark
   ✓ User email + sign out in mobile drawer

 Live at: https://portal.coreholdingcorp.com
============================================================
`);
