#!/usr/bin/env node
/**
 * Script 29 — GCP Virtual Companies Pipeline + Telemetry Fix
 * Idempotent · Zero hand edits · Ends with npm run build
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const REPO   = path.join(process.env.HOME, 'coreidentity-dashboard');
const REGION = 'us-east-2';

const run = (cmd) => { console.log(`  $ ${cmd.slice(0,100)}`); execSync(cmd, { cwd: REPO, stdio: 'inherit' }); };
const rf  = (rel) => fs.readFileSync(path.join(REPO, rel), 'utf8');
const wf  = (rel, c) => { fs.writeFileSync(path.join(REPO, rel), c, 'utf8'); console.log(`  wrote ${rel}`); };

// ── STEP 1: integrations.js ─────────────────────────────────────────────────
console.log('\n── Step 1: integrations.js ──────────────────────────────────────────────');
let integ = rf('api/src/config/integrations.js');
if (!integ.includes('chcHealthNetwork')) {
  wf('api/src/config/integrations.js', [
    '// Auto-generated by Script 29 — DO NOT hand edit',
    'module.exports = {',
    '  gcpVirtualBank: {',
    "    baseUrl: 'https://chc-virtual-bank-lvuq2yqbma-uc.a.run.app',",
    "    apiKey: 'chc-bank-dev-key-2026',",
    "    name: 'First National Virtual Bank',",
    "    vertical: 'financial_services',",
    '    timeout: 10000, retryAttempts: 3,',
    '    endpoints: { health:"/health", bank:"/api/bank", customers:"/api/customers",',
    '      transactions:"/api/transactions", compliance:"/api/compliance",',
    '      audit:"/api/audit", stressTest:"/api/stress-test", register:"/api/governance/register" }',
    '  },',
    '  chcHealthNetwork: {',
    "    baseUrl: 'https://chc-health-network-lvuq2yqbma-uc.a.run.app',",
    "    apiKey: 'chc-health-dev-key-2026',",
    "    name: 'Regional Health Network', vertical: 'healthcare',",
    '    timeout: 10000, retryAttempts: 3,',
    '    endpoints: { health:"/health", hospital:"/api/hospital", patients:"/api/patients",',
    '      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }',
    '  },',
    '  chcLegalPartners: {',
    "    baseUrl: 'https://chc-legal-partners-lvuq2yqbma-uc.a.run.app',",
    "    apiKey: 'chc-legal-dev-key-2026',",
    "    name: 'Legal Partners Group', vertical: 'legal',",
    '    timeout: 10000, retryAttempts: 3,',
    '    endpoints: { health:"/health", firm:"/api/firm", cases:"/api/cases",',
    '      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }',
    '  },',
    '  chcRetailGroup: {',
    "    baseUrl: 'https://chc-retail-group-lvuq2yqbma-uc.a.run.app',",
    "    apiKey: 'chc-retail-dev-key-2026',",
    "    name: 'Metro Retail Group', vertical: 'retail',",
    '    timeout: 10000, retryAttempts: 3,',
    '    endpoints: { health:"/health", store:"/api/store", inventory:"/api/inventory",',
    '      compliance:"/api/compliance", audit:"/api/audit", register:"/api/governance/register" }',
    '  }',
    '};',
  ].join('\n'));
} else { console.log('  already done'); }

// ── STEP 2: HTTP clients ────────────────────────────────────────────────────
console.log('\n── Step 2: GCP HTTP clients ─────────────────────────────────────────────');

function makeClient(name, configKey, extraMethods) {
  return `// ${name} — Script 29
const https = require('https');
const { ${configKey}: config } = require('../config/integrations');
function httpRequest(url, opts={}) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const req = https.request({
      hostname: u.hostname, path: u.pathname+u.search,
      method: opts.method||'GET',
      headers: { 'x-api-key': config.apiKey, 'Content-Type':'application/json', 'User-Agent':'CoreIdentity-AGO/1.0' },
      timeout: config.timeout
    }, (res) => {
      let d=''; res.on('data', c=>d+=c);
      res.on('end', ()=>{ try { resolve({status:res.statusCode,ok:res.statusCode<300,data:JSON.parse(d)}); } catch(e){resolve({status:res.statusCode,ok:false,data:{error:d}});} });
    });
    req.on('error', reject); req.on('timeout', ()=>{req.destroy(); reject(new Error('Timeout'));});
    if (opts.body) req.write(JSON.stringify(opts.body)); req.end();
  });
}
async function withRetry(fn) {
  for (let i=0; i<(config.retryAttempts||3); i++) {
    try { const r=await fn(); if(r.ok) return r; } catch(e){ if(i===(config.retryAttempts||3)-1) throw e; }
    await new Promise(r=>setTimeout(r, Math.pow(2,i)*500));
  }
  throw new Error('Max retries exceeded');
}
const client = {
  health:           () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.health)),
  getCompliance:    () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.compliance)),
  getAuditLog:      () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.audit)),
  registerGovernance: (n=23, frameworks) => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.register,{method:'POST',body:{platform:'CoreIdentity',agentCount:n,frameworks}})),
${extraMethods}
};
module.exports = client;
module.exports.config = config;
`;
}

wf('api/src/integrations/healthNetworkClient.js', makeClient('healthNetworkClient','chcHealthNetwork',
  "  getHospital: () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.hospital)),\n  getPatients: () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.patients)),"
));
wf('api/src/integrations/legalPartnersClient.js', makeClient('legalPartnersClient','chcLegalPartners',
  "  getFirm:  () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.firm)),\n  getCases: () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.cases)),"
));
wf('api/src/integrations/retailGroupClient.js', makeClient('retailGroupClient','chcRetailGroup',
  "  getStore:     () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.store)),\n  getInventory: () => withRetry(()=>httpRequest(config.baseUrl+config.endpoints.inventory)),"
));

// ── STEP 3: liveData.js ─────────────────────────────────────────────────────
console.log('\n── Step 3: liveData.js — 5-company aggregation ─────────────────────────');
const GUARD = '/* script-29 */';
let ld = rf('api/src/routes/liveData.js');
if (!ld.includes(GUARD)) {
  wf('api/src/routes/liveData.js', `// Live Data — /api/live-data  ${GUARD}
const express             = require('express');
const router              = express.Router();
const chcCorporate        = require('../integrations/chcCorporateClient');
const gcpBank             = require('../integrations/gcpBankClient');
const healthNetwork       = require('../integrations/healthNetworkClient');
const legalPartners       = require('../integrations/legalPartnersClient');
const retailGroup         = require('../integrations/retailGroupClient');

function ok(r){ return r.status==='fulfilled' && r.value?.ok; }

function clientCard(id, name, vertical, compR, auditR, meta) {
  const comp  = ok(compR)  ? (compR.value.data.data  || compR.value.data)  : {};
  const audit = ok(auditR) ? (auditR.value.data.data || auditR.value.data) : {};
  return {
    id, name, vertical,
    complianceBefore: meta.before || 65,
    complianceAfter:  comp?.summary?.overallScore || comp?.overallScore || meta.score || 90,
    complianceStatus: comp?.summary?.status || 'compliant',
    penaltyExposure:  meta.penalty,
    penaltyMitigated: meta.penalty,
    criticalFindings: comp?.data?.criticalFindings || audit?.criticalFindings || 0,
    frameworks:       meta.frameworks,
    onboarded:        'Feb 2026',
    liveDataSource:   meta.url,
    fetchedAt:        new Date().toISOString()
  };
}

router.get('/', async (req, res) => {
  const t0 = Date.now();
  const [coR,ciR,cgR,finR,agR, biR,bcR,baR, hcR,haR, lcR,laR, rcR,raR] =
    await Promise.allSettled([
      chcCorporate.getCompany(), chcCorporate.getCoreIdentity(), chcCorporate.getCIAG(),
      chcCorporate.getFinancials(), chcCorporate.getAgents(),
      gcpBank.getBankInfo(), gcpBank.getCompliance(), gcpBank.getAuditLog(),
      healthNetwork.getCompliance(), healthNetwork.getAuditLog(),
      legalPartners.getCompliance(), legalPartners.getAuditLog(),
      retailGroup.getCompliance(), retailGroup.getAuditLog()
    ]);
  const results={}, errors={};
  if(ok(coR))  results.company      = coR.value.data; else errors.company='unavailable';
  if(ok(ciR))  results.coreIdentity = ciR.value.data?.data||ciR.value.data; else errors.coreIdentity='unavailable';
  if(ok(cgR))  results.ciag         = cgR.value.data?.data||cgR.value.data; else errors.ciag='unavailable';
  if(ok(finR)) results.financials   = finR.value.data?.data||finR.value.data; else errors.financials='unavailable';
  if(ok(agR))  results.agents       = agR.value.data; else errors.agents='unavailable';
  const clients = [
    { ...clientCard('fnvb','First National Virtual Bank','Financial Services',bcR,baR,
        {before:65,score:94,penalty:'$4.75M',frameworks:['GLBA','CCPA','FFIEC','SOX','PCI-DSS'],
         url:'https://chc-virtual-bank-lvuq2yqbma-uc.a.run.app'}),
      totalAssets: ok(biR)?biR.value.data.totalAssets:null,
      aiAgentsActive: ok(biR)?biR.value.data.aiAgentsActive:null },
    clientCard('rhn','Regional Health Network','Healthcare',hcR,haR,
      {before:62,score:91,penalty:'$3.2M',frameworks:['HIPAA','HITECH','SOC2'],
       url:'https://chc-health-network-lvuq2yqbma-uc.a.run.app'}),
    clientCard('lpg','Legal Partners Group','Legal',lcR,laR,
      {before:70,score:93,penalty:'$2.8M',frameworks:['SOC2','GDPR','ISO27001'],
       url:'https://chc-legal-partners-lvuq2yqbma-uc.a.run.app'}),
    clientCard('mrg','Metro Retail Group','Retail',rcR,raR,
      {before:58,score:89,penalty:'$1.9M',frameworks:['PCI-DSS','CCPA','SOC2'],
       url:'https://chc-retail-group-lvuq2yqbma-uc.a.run.app'}),
  ];
  results.clients = clients;
  const hasErrors = Object.keys(errors).length > 0;
  res.json({
    success: !hasErrors, partial: hasErrors && Object.keys(results).length>0,
    data: results, errors: hasErrors?errors:undefined,
    latencyMs: Date.now()-t0, fetchedAt: new Date().toISOString()
  });
});

router.get('/clients', async (req, res) => {
  const [bcR,baR,biR,hcR,haR,lcR,laR,rcR,raR] = await Promise.allSettled([
    gcpBank.getCompliance(), gcpBank.getAuditLog(), gcpBank.getBankInfo(),
    healthNetwork.getCompliance(), healthNetwork.getAuditLog(),
    legalPartners.getCompliance(), legalPartners.getAuditLog(),
    retailGroup.getCompliance(), retailGroup.getAuditLog()
  ]);
  res.json({ success:true, clients:[
    { ...clientCard('fnvb','First National Virtual Bank','Financial Services',bcR,baR,{before:65,score:94,penalty:'$4.75M',frameworks:['GLBA','CCPA','FFIEC'],url:'https://chc-virtual-bank-lvuq2yqbma-uc.a.run.app'}), totalAssets:ok(biR)?biR.value.data.totalAssets:null },
    clientCard('rhn','Regional Health Network','Healthcare',hcR,haR,{before:62,score:91,penalty:'$3.2M',frameworks:['HIPAA','HITECH','SOC2'],url:'https://chc-health-network-lvuq2yqbma-uc.a.run.app'}),
    clientCard('lpg','Legal Partners Group','Legal',lcR,laR,{before:70,score:93,penalty:'$2.8M',frameworks:['SOC2','GDPR','ISO27001'],url:'https://chc-legal-partners-lvuq2yqbma-uc.a.run.app'}),
    clientCard('mrg','Metro Retail Group','Retail',rcR,raR,{before:58,score:89,penalty:'$1.9M',frameworks:['PCI-DSS','CCPA','SOC2'],url:'https://chc-retail-group-lvuq2yqbma-uc.a.run.app'}),
  ], fetchedAt: new Date().toISOString() });
});

module.exports = router;
`);
} else { console.log('  already at v29'); }

// ── STEP 4: telemetry authenticate fix ─────────────────────────────────────
console.log('\n── Step 4: telemetry authenticate fix ───────────────────────────────────');
let srv = rf('api/src/server.js');
if (srv.includes("app.use('/api/telemetry',      telemetryRouter)")) {
  srv = srv.replace("app.use('/api/telemetry',      telemetryRouter);",
                    "app.use('/api/telemetry', authenticate, telemetryRouter);");
  wf('api/src/server.js', srv);
} else { console.log('  telemetry line not in expected form — skipping'); }

// ── STEP 5: syntax + build ──────────────────────────────────────────────────
console.log('\n── Step 5: syntax + build ───────────────────────────────────────────────');
run('node --check api/src/server.js');
run('node --check api/src/routes/liveData.js');
run('node --check api/src/integrations/healthNetworkClient.js');
run('node --check api/src/integrations/legalPartnersClient.js');
run('node --check api/src/integrations/retailGroupClient.js');
run('npm run build');

// ── STEP 6: commit + push ───────────────────────────────────────────────────
console.log('\n── Step 6: commit + push ────────────────────────────────────────────────');
run('git add -A');
const dirty = execSync('git status --porcelain', { cwd: REPO }).toString().trim();
if (dirty) {
  run('git commit -m "feat: Script 29 — GCP 5-company live data pipeline (health, legal, retail)"');
  run('git push origin main');
} else { console.log('  nothing to commit'); }

// ── STEP 7: ECS redeploy ────────────────────────────────────────────────────
console.log('\n── Step 7: ECS redeploy ─────────────────────────────────────────────────');
try {
  execSync(`aws ecs update-service --cluster coreidentity-dev --service sentinel --force-new-deployment --region ${REGION}`, {stdio:'pipe'});
  console.log('  ECS redeploy triggered — wait ~90s');
} catch(e) { console.warn('  ECS redeploy failed:', e.message); }

console.log(`
Done — Script 29 complete.
Wait 90s then: curl -s https://api.coreidentity.coreholdingcorp.com/api/live-data | python3 -c "import sys,json; d=json.load(sys.stdin); print('clients:', len(d['data'].get('clients',[])), '| partial:', d.get('partial'))"
Expected: clients: 4 | partial: False
`);
