// GCP Integration Test — Auto-generated by Script 18 v2
// Generated: 2026-02-26T22:28:27Z

const gcpBankClient = require('../integrations/gcpBankClient');

async function runTests() {
  let passed = 0; let failed = 0;

  async function test(name, fn) {
    try {
      const result = await fn();
      console.log('  ✓', name);
      passed++;
    } catch (err) {
      console.log('  ✗', name, '-', err.message);
      failed++;
    }
  }

  console.log('\n=== CoreIdentity → GCP Bank Integration Tests ===\n');
  await test('Health check',           async () => { const r = await gcpBankClient.health(); if (!r.ok) throw new Error('status ' + r.status); });
  await test('Bank info',              async () => { const r = await gcpBankClient.getBankInfo(); if (!r.ok) throw new Error('status ' + r.status); });
  await test('Customers',              async () => { const r = await gcpBankClient.getCustomers(); if (!r.ok) throw new Error('status ' + r.status); });
  await test('Compliance + penalties', async () => { const r = await gcpBankClient.getCompliance(); if (!r.data.data.penaltyExposure) throw new Error('no penalty data'); });
  await test('Audit log',              async () => { const r = await gcpBankClient.getAuditLog(); if (r.data.ungoverned === undefined) throw new Error('no ungoverned data'); });
  await test('Governance registration',async () => { const r = await gcpBankClient.registerGovernance(); if (r.data.governanceScore !== 94) throw new Error('unexpected score'); });
  await test('Stress test reachable',  async () => { const r = await gcpBankClient.stressTest(); if (r.status !== 200 && r.status !== 503) throw new Error('bad status ' + r.status); });

  console.log('\n=== Results ===');
  console.log('  Passed:', passed, '| Failed:', failed);
  console.log('  Status:', failed === 0 ? '✓ ALL PASSED' : '✗ FAILURES DETECTED');
  if (failed > 0) process.exit(1);
}

runTests().catch(err => { console.error(err.message); process.exit(1); });
