// App.jsx — CoreIdentity Governance Portal
// Auto-generated by Script 27 — DO NOT hand edit
import React, { useState, useEffect, createContext, useContext } from 'react';
import { useAuth } from './context/AuthContext';
import { injectFonts } from './chc-design.js';
import PortalNav from './components/PortalNav.jsx';
import LoginPage from './pages/LoginPage.jsx';

// ── Page imports ──────────────────────────────────────────────
import FoundersDashboard from './pages/FoundersDashboard.jsx';
import AgentCatalog      from './pages/AgentCatalog.jsx';
import Sentinel          from './pages/Sentinel.jsx';
import NexusOS           from './pages/NexusOS.jsx';
import SmartNation       from './pages/SmartNation.jsx';
import Governance        from './pages/Governance.jsx';
import Workflows         from './pages/Workflows.jsx';
import MCPDemo   from './pages/MCPDemo';
import LiveDemo   from './pages/LiveDemo';
import Analytics  from './pages/Analytics.jsx';
import SettingsPage      from './pages/SettingsPage.jsx';
import MarketingPage     from './pages/MarketingPage.jsx';
import DemoPage          from './pages/DemoPage.jsx';
import OnboardPage       from './pages/OnboardPage.jsx';
import InvestorPage      from './pages/InvestorPage.jsx';
import PricingPage       from './pages/PricingPage.jsx';
import ReportsPage       from './pages/ReportsPage.jsx';
import DocsPage          from './pages/DocsPage.jsx';

// ── Notifications context ─────────────────────────────────────
/* patch-33 */
const NotificationContext = createContext({ notifications: [], addNotification: () => {}, removeNotification: () => {} });
export const useNotifications = () => useContext(NotificationContext);

// ── Route maps ────────────────────────────────────────────────
const PORTAL_PAGES = {
  '/#/dashboard':   FoundersDashboard,
  '/#/agents':      AgentCatalog,
  '/#/sentinel':    Sentinel,
  '/#/nexus':       NexusOS,
  '/#/smartnation': SmartNation,
  '/#/governance':  Governance,
  '/#/workflows':   Workflows,
  '/#/mcp-demo':    MCPDemo,
  '/#/live-demo':   LiveDemo,
  '/#/ciag-intake': CIAGIntake,
  '/#/analytics':   Analytics,
  '/#/settings':    SettingsPage,
};

const PUBLIC_PAGES = {
  '/':           MarketingPage,
  '/#/demo':     DemoPage,
  '/#/onboard':  OnboardPage,
  '/#/investor': InvestorPage,
  '/#/pricing':  PricingPage,
  '/#/reports':  ReportsPage,
  '/#/docs':     DocsPage,
};

const PUBLIC_ROUTES = new Set(Object.keys(PUBLIC_PAGES));

function isPortalDomain() {
  return window.location.hostname === 'portal.coreholdingcorp.com';
}

function getRoute() {
  const hash = window.location.hash || '';
  const route = (!hash || hash === '#') ? '/' : '/#' + hash.slice(1);
  // On portal domain, redirect root to dashboard
  if (route === '/' && isPortalDomain()) {
    window.location.replace('/#/dashboard');
    return '/#/dashboard';
  }
  return route;
}

// ── Root app ──────────────────────────────────────────────────
// ── Real notification system ─────────────────────────────────────────────────
const TOAST_COLORS = {
  success: { bg: '#166534', border: '#22c55e', icon: '✓' },
  error:   { bg: '#7f1d1d', border: '#ef4444', icon: '✕' },
  warning: { bg: '#78350f', border: '#f59e0b', icon: '⚠' },
  info:    { bg: '#1e3a5f', border: '#3b82f6', icon: 'ℹ' },
};

function NotificationContextWrapper({ children }) {
  const [notifications, setNotifications] = React.useState([]);

  function addNotification(message, type = 'info') {
    const id = Date.now() + Math.random();
    setNotifications(prev => [...prev.slice(-4), { id, message, type }]);
    setTimeout(() => removeNotification(id), type === 'error' ? 6000 : 4000);
  }

  function removeNotification(id) {
    setNotifications(prev => prev.filter(n => n.id !== id));
  }

  return (
    <NotificationContext.Provider value={{ notifications, addNotification, removeNotification }}>
      {children}
      {/* Toast container */}
      <div style={{
        position: 'fixed', bottom: 20, right: 16, zIndex: 9999,
        display: 'flex', flexDirection: 'column', gap: 8,
        maxWidth: 'calc(100vw - 32px)', width: 340,
        pointerEvents: 'none'
      }}>
        {notifications.map(n => {
          const s = TOAST_COLORS[n.type] || TOAST_COLORS.info;
          return (
                <div key={n.id} style={{
              background: s.bg, border: '1px solid ' + s.border,
              borderRadius: 8, padding: '10px 14px',
              display: 'flex', alignItems: 'flex-start', gap: 8,
              boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
              pointerEvents: 'auto', cursor: 'pointer',
              color: '#fff', fontSize: 13, lineHeight: 1.4,
              animation: 'slideIn 0.2s ease'
            }} onClick={() => removeNotification(n.id)}>
              <span style={{ fontSize: 14, fontWeight: 700, flexShrink: 0, color: s.border }}>{s.icon}</span>
              <span>{n.message}</span>
            </div>
          );
        })}
      </div>
      <style>{'`@keyframes slideIn { from { opacity:0; transform:translateX(20px); } to { opacity:1; transform:translateX(0); } }`'}</style>
    </NotificationContext.Provider>
  );
}



export default function App() {
  const { user, loading, logout } = useAuth();
  const [route, setRoute] = useState(getRoute);

  useEffect(() => {
    injectFonts();
    const onHash = () => setRoute(getRoute());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  if (loading) {
    return (
      <div style={{ minHeight:'100vh', background:'#070c18', display:'flex', alignItems:'center', justifyContent:'center' }}>
        <div style={{ color:'#d4af37', fontSize:14, fontFamily:'system-ui' }}>Loading…</div>
      </div>
    );
  }

  // Public/marketing routes
  if (PUBLIC_ROUTES.has(route)) {
    const Page = PUBLIC_PAGES[route] || MarketingPage;
    return <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}><Page /></div>;
  }

  // Portal routes — require auth
  if (!user) return <LoginPage />;

  const Page = PORTAL_PAGES[route] || FoundersDashboard;

  return (
    <NotificationContextWrapper>
      <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}>
        <PortalNav
          route={route}
          onNavigate={setRoute}
          userEmail={user?.email}
          onLogout={logout}
        />
        <Page />
      </div>
    </NotificationContextWrapper>
  );
}
// Sun Mar  1 05:34:25 EST 2026
