// App.jsx — CoreIdentity Governance Portal
// Auto-generated by Script 27 — DO NOT hand edit
import React, { useState, useEffect, createContext, useContext } from 'react';
import { useAuth } from './context/AuthContext';
import { injectFonts } from './chc-design.js';
import PortalNav from './components/PortalNav.jsx';
import LoginPage from './pages/LoginPage.jsx';

// ── Page imports ──────────────────────────────────────────────
import FoundersDashboard from './pages/FoundersDashboard.jsx';
import AgentCatalog      from './pages/AgentCatalog.jsx';
import Sentinel          from './pages/Sentinel.jsx';
import NexusOS           from './pages/NexusOS.jsx';
import SmartNation       from './pages/SmartNation.jsx';
import Governance        from './pages/Governance.jsx';
import Workflows         from './pages/Workflows.jsx';
import Analytics         from './pages/Analytics.jsx';
import SettingsPage      from './pages/SettingsPage.jsx';
import MarketingPage     from './pages/MarketingPage.jsx';
import DemoPage          from './pages/DemoPage.jsx';
import OnboardPage       from './pages/OnboardPage.jsx';
import InvestorPage      from './pages/InvestorPage.jsx';
import PricingPage       from './pages/PricingPage.jsx';
import ReportsPage       from './pages/ReportsPage.jsx';
import DocsPage          from './pages/DocsPage.jsx';

// ── Notifications context ─────────────────────────────────────
const NotificationContext = createContext({ notifications: [], addNotification: () => {} });
export const useNotifications = () => useContext(NotificationContext);

// ── Route maps ────────────────────────────────────────────────
const PORTAL_PAGES = {
  '/#/dashboard':   FoundersDashboard,
  '/#/agents':      AgentCatalog,
  '/#/sentinel':    Sentinel,
  '/#/nexus':       NexusOS,
  '/#/smartnation': SmartNation,
  '/#/governance':  Governance,
  '/#/workflows':   Workflows,
  '/#/analytics':   Analytics,
  '/#/settings':    SettingsPage,
};

const PUBLIC_PAGES = {
  '/':           MarketingPage,
  '/#/demo':     DemoPage,
  '/#/onboard':  OnboardPage,
  '/#/investor': InvestorPage,
  '/#/pricing':  PricingPage,
  '/#/reports':  ReportsPage,
  '/#/docs':     DocsPage,
};

const PUBLIC_ROUTES = new Set(Object.keys(PUBLIC_PAGES));

function isPortalDomain() {
  return window.location.hostname === 'portal.coreholdingcorp.com';
}

function getRoute() {
  const hash = window.location.hash || '';
  const route = (!hash || hash === '#') ? '/' : '/#' + hash.slice(1);
  // On portal domain, redirect root to dashboard
  if (route === '/' && isPortalDomain()) {
    window.location.replace('/#/dashboard');
    return '/#/dashboard';
  }
  return route;
}

// ── Root app ──────────────────────────────────────────────────
export default function App() {
  const { user, loading, logout } = useAuth();
  const [route, setRoute] = useState(getRoute);

  useEffect(() => {
    injectFonts();
    const onHash = () => setRoute(getRoute());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  if (loading) {
    return (
      <div style={{ minHeight:'100vh', background:'#070c18', display:'flex', alignItems:'center', justifyContent:'center' }}>
        <div style={{ color:'#d4af37', fontSize:14, fontFamily:'system-ui' }}>Loading…</div>
      </div>
    );
  }

  // Public/marketing routes
  if (PUBLIC_ROUTES.has(route)) {
    const Page = PUBLIC_PAGES[route] || MarketingPage;
    return <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}><Page /></div>;
  }

  // Portal routes — require auth
  if (!user) return <LoginPage />;

  const Page = PORTAL_PAGES[route] || FoundersDashboard;

  return (
    <NotificationContext.Provider value={{ notifications: [], addNotification: () => {} }}>
      <div style={{ minHeight:'100vh', background:'#070c18', fontFamily:"'DM Sans','Segoe UI',sans-serif" }}>
        <PortalNav
          route={route}
          onNavigate={setRoute}
          userEmail={user?.email}
          onLogout={logout}
        />
        <Page />
      </div>
    </NotificationContext.Provider>
  );
}
