// App.jsx — CHC Hash Router
// Auto-generated by Script 25-A — DO NOT hand edit
import { useState, useEffect } from 'react';
import { injectFonts }         from './chc-design.js';
import Nav                     from './components/Nav.jsx';
import FoundersDashboard       from './components/FoundersDashboard.jsx';
import MarketingPage           from './pages/MarketingPage.jsx';
import DemoPage                from './pages/DemoPage.jsx';
import OnboardPage             from './pages/OnboardPage.jsx';
import InvestorPage            from './pages/InvestorPage.jsx';
import PricingPage             from './pages/PricingPage.jsx';
import ReportsPage             from './pages/ReportsPage.jsx';
import DocsPage                from './pages/DocsPage.jsx';

const BARE = new Set(['/dashboard']);

const getRoute = () => {
  const h = window.location.hash.replace(/^#/, '') || '/';
  return h.startsWith('/') ? h : '/' + h;
};

const PAGES = {
  '/':          MarketingPage,
  '/dashboard': FoundersDashboard,
  '/demo':      DemoPage,
  '/onboard':   OnboardPage,
  '/investor':  InvestorPage,
  '/pricing':   PricingPage,
  '/reports':   ReportsPage,
  '/docs':      DocsPage,
};

export default function App() {
  const [route, setRoute] = useState(getRoute);
  useEffect(() => {
    injectFonts();
    const handler = () => setRoute(getRoute());
    window.addEventListener('hashchange', handler);
    return () => window.removeEventListener('hashchange', handler);
  }, []);
  const Page = PAGES[route] || MarketingPage;
  const bare = BARE.has(route);
  return (
    <div style={{ minHeight: '100vh', background: '#070c18', fontFamily: "'DM Sans','Segoe UI',sans-serif" }}>
      {!bare && <Nav route={route} />}
      <Page />
    </div>
  );
}
