// CHC Corporate API Client
// Auto-generated by Script 20 v2 — DO NOT hand edit

const https = require('https');

const CONFIG = {
  baseUrl: 'https://chc-corporate-api-lvuq2yqbma-uc.a.run.app',
  apiKey:  'chc-corp-dev-key-2026',
  timeout: 10000,
  retries: 3
};

function httpRequest(url, options = {}) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const req = https.request({
      hostname: u.hostname,
      path: u.pathname + u.search,
      method: options.method || 'GET',
      headers: { 'x-api-key': CONFIG.apiKey, 'Content-Type': 'application/json', 'User-Agent': 'CoreIdentity-AWS/1.0' },
      timeout: CONFIG.timeout
    }, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try { resolve({ status: res.statusCode, ok: res.statusCode < 300, data: JSON.parse(data) }); }
        catch(e) { resolve({ status: res.statusCode, ok: false, data: { error: data } }); }
      });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
    if (options.body) req.write(JSON.stringify(options.body));
    req.end();
  });
}

async function withRetry(fn) {
  for (let i = 0; i < CONFIG.retries; i++) {
    try { const r = await fn(); if (r.ok) return r; }
    catch(e) { if (i === CONFIG.retries - 1) throw e; }
    await new Promise(r => setTimeout(r, Math.pow(2, i) * 500));
  }
  throw new Error('Max retries exceeded');
}

const chcCorporateClient = {
  health:          ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/health')),
  getCompany:      ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/company')),
  getCoreIdentity: ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/coreidentity')),
  getCIAG:         ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/ciag')),
  getFinancials:   ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/financials')),
  getAgents:       ()  => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/agents')),
  syncGovernance:  (p) => withRetry(() => httpRequest(CONFIG.baseUrl + '/api/governance/sync', { method:'POST', body: p }))
};

module.exports = chcCorporateClient;
